(function () {
  'use strict';
  const E = window.WaferEngine, V = window.WaferVisuals;
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icons = {
    layers:'M12 3 2 8l10 5 10-5-10-5ZM2 12l10 5 10-5M2 16l10 5 10-5',
    compass:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20ZM16 8l-3 5-5 3 3-5 5-3Z',
    chart:'M4 3v17h17M8 15l4-5 4 3 5-8', book:'M3 4h6q3 0 3 3v14q0-3-3-3H3V4Zm18 0h-6q-3 0-3 3v14q0-3 3-3h6V4Z',
    database:'M21 5c0 4-18 4-18 0s18-4 18 0ZM3 5v7c0 4 18 4 18 0V5M3 12v7c0 4 18 4 18 0v-7',
    help:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20ZM9 9a3 3 0 1 1 4 3v2M12 17h.01',
    save:'M4 3h13l4 4v14H3V3h1ZM7 3v6h9V3M7 21v-8h10v8', download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',
    target:'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18ZM12 17a5 5 0 1 0 0-10 5 5 0 0 0 0 10ZM12 11v2',
    reset:'M3 10a9 9 0 1 1 1 8M3 4v6h6',bulb:'M9 18h6M9 21h6M8 15a7 7 0 1 1 8 0l-1 3H9l-1-3Z',
    play:'m8 5 11 7-11 7V5Z',pause:'M8 5v14M16 5v14',split:'M12 3v18M4 5h4v14H4V5ZM16 5h4v14h-4V5Z',
    activity:'M2 12h5l3-8 4 16 3-8h5',grid:'M3 3h7v7H3V3ZM14 3h7v7h-7V3ZM3 14h7v7H3v-7ZM14 14h7v7h-7v-7Z',
    coin:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20ZM15 7h-4a3 3 0 0 0 0 6h2a2 2 0 0 1 0 4H8M12 5v14',
    clock:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 0 20ZM12 6v6l4 2',close:'m6 6 12 12M6 18 18 6'
  };
  const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name] || icons.layers}"/></svg>`;
  const paintIcons = () => $$('[data-icon]').forEach(el => {el.innerHTML=icon(el.dataset.icon);});
  const KEY='waferflow-v2';
  const validMission = id => E.missions.some(m=>m.id===id);
  let saved = {}, storageFailed = false;
  try { saved=JSON.parse(localStorage.getItem(KEY)||'{}'); if(!saved || typeof saved!=='object') saved={}; } catch { saved={}; }
  const validEntry = r => r && validMission(r.missionId) && r.params && typeof r.params==='object' && Object.keys(E.fields).every(k => typeof r.params[k]==='number' && Number.isFinite(r.params[k])) && typeof r.id==='string';
  let history = Array.isArray(saved.history) ? saved.history.filter(validEntry).slice(-200).map(r=>({...r,params:E.normalize(r.params),hypothesis:String(r.hypothesis||'').slice(0,500)})) : [];
  let recipes = Array.isArray(saved.recipes) ? saved.recipes.filter(validEntry).slice(-50).map(r=>({...r,params:E.normalize(r.params),name:String(r.name||'이름 없는 레시피').slice(0,60)})) : [];
  let missionId = validMission(saved.missionId) ? saved.missionId : 'residue';
  let params = E.normalize(saved.params || E.missions.find(m=>m.id===missionId).defaults);
  let stageIndex = 3, view='scene', compare=false, page='lab', running=false, playing=false, progress=1, frame=0, playbackStart=0;
  let baseline=E.simulate(mission().defaults,missionId), result=baseline, preview=E.simulate(params,missionId), selectedRun='BASELINE', analysis=null, toastTimer;
  if (saved.lastResult?.missionId===missionId && saved.lastResult.params && Object.keys(E.fields).every(k=>Number.isFinite(saved.lastResult.params[k]))) {
    result=E.simulate(saved.lastResult.params,missionId);selectedRun=String(saved.lastResult.label||'저장된 실행').slice(0,40);
  }
  function mission(){return E.missions.find(m=>m.id===missionId);}
  function setText(id,value){$(id).textContent=value;}
  function persist(){try{localStorage.setItem(KEY,JSON.stringify({version:2,missionId,params,history,recipes,hypothesis:$('#hypothesis').value,lastResult:{params:result.params,missionId:result.missionId,label:selectedRun}}));}catch{if(!storageFailed){toast('저장 공간이 부족합니다. 리포트를 내보내 보관하세요.');storageFailed=true;}}}
  function toast(message){setText('#toast',message);$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
  function changed(p,base=mission().defaults){return Object.keys(E.fields).filter(k=>Math.abs(p[k]-base[k])>0.001).map(k=>`${E.fields[k].label} ${p[k]} ${E.fields[k].unit}`).join(' · ')||'기준 레시피';}
  function shortChanges(p){const text=changed(p);return text.length>60?text.slice(0,57)+'…':text;}
  function stopPlayback(){playing=false;cancelAnimationFrame(frame);$('#playProcess').innerHTML=icon('play');$('#playProcess').setAttribute('aria-label','공정 순서 재생');}
  function setStage(index,fromPlayback=false){if(!fromPlayback){stopPlayback();if(window.WaferMachine){window.WaferMachine.selectStage(index);return;}}stageIndex=index;progress=fromPlayback?0:1;renderStage();renderVisual();}
  function renderMission(){
    const m=mission();setText('#missionTitle',m.title);setText('#missionDescription',m.description);setText('#missionLevel',m.level+' · '+m.subtitle);setText('#missionCode',m.code);$('#missionTarget').innerHTML=`${m.target}<span>% ↗</span>`;
    setText('#targetLabel',`목표 ≥ ${m.target}%`);setText('#budgetLabel',`목표 예산 ≤ $${m.budget}`);
  }
  function renderStage(){
    const stage=E.stages[stageIndex];
    $('#processRibbon').innerHTML=E.stages.map((s,i)=>`<button class="ribbon-step ${i===stageIndex?'active':''}" data-stage="${i}" aria-pressed="${i===stageIndex}"><span class="ribbon-meta"><span>${String(i+1).padStart(2,'0')}</span><span>${s.short}</span></span><strong>${s.name}</strong></button>`).join('');
    setText('#stageEnglish',stage.english.toUpperCase());setText('#stageName',stage.name);setText('#stageDescription',stage.description);setText('#sceneId',`${stage.short} / ${String(stageIndex+1).padStart(2,'0')}`);setText('#sceneCaption',stage.english.toUpperCase());setText('#equipmentLabel',stage.equipment);setText('#playbackTitle',`${String(stageIndex+1).padStart(2,'0')} · ${stage.name}`);setText('#stageFraction',`${stageIndex+1} / 8`);
    $('#playbackDots').innerHTML=E.stages.map((s,i)=>`<i class="${i===stageIndex?'active':''}"></i>`).join('');
    $('#parameterControls').innerHTML=stage.fields.map(k=>{const f=E.fields[k];return `<div class="parameter"><div class="parameter-top"><label for="param-${k}">${f.label}</label><output for="param-${k}" class="parameter-value" id="value-${k}">${params[k]}<small>${f.unit}</small></output></div><input id="param-${k}" type="range" data-param="${k}" min="${f.min}" max="${f.max}" step="${f.step}" value="${params[k]}" style="--pct:${(params[k]-f.min)/(f.max-f.min)*100}%" ${running?'disabled':''}><div class="range-labels"><span>${f.min} ${f.unit}</span><span>${f.max} ${f.unit}</span></div></div>`;}).join('') || '<p class="empty-state">감광막 제거 후 단면과 불량 맵을 확인하세요. 이 단계의 제거 조건은 고정되어 있습니다.</p>';
  }
  function updatePreview(){preview=E.simulate(params,missionId);renderVisual();renderReasoning();renderDraft();persist();}
  function renderDraft(){const dirty=JSON.stringify(params)!==JSON.stringify(result.params);setText('#draftStatus',dirty?'설정 변경됨 · 실행해 결과를 기록하세요.':'현재 조건의 결과가 표시되어 있습니다.');$('#draftDot').classList.toggle('dirty',dirty);setText('#previewLabel',dirty?'설정 미리보기':'현재 레시피');}
  function renderVisual(){
    const render=(r,base=false)=>view==='map'?V.map(r,!base):view==='section'?V.section(r,stageIndex,progress):V.scene(r,stageIndex,progress);
    $('#visualization').innerHTML=compare?`<div class="svg-compare"><div><p>BASELINE · ${baseline.yield}%</p>${render(baseline,true)}</div><div><p>CURRENT · ${preview.yield}%</p>${render(preview)}</div></div>`:render(preview);
    if(view==='map') $('#visualization').insertAdjacentHTML('beforeend','<p id="dieInspector" class="inspect-caption">다이를 선택해 불량 유형과 식각 깊이를 확인하세요.</p>');
    // IDs in independent inline SVGs must be unique in comparison mode.
    $$('#visualization svg').forEach((svg,i)=>{[...svg.querySelectorAll('[id]')].forEach(el=>{const old=el.id,newId=`viz${i}-${old}`;el.id=newId;svg.querySelectorAll('*').forEach(node=>{for(const attr of [...node.attributes])if(attr.value.includes(`url(#${old})`))node.setAttribute(attr.name,attr.value.replaceAll(`url(#${old})`,`url(#${newId})`));});});});
  }
  function renderReasoning(){
    const r=preview;
    const good=r.yield>=mission().target;
    const tips={
      '과식각':{title:'가장자리가 먼저 반응하고 있어요.',description:'이 모델에서는 높은 RF 파워와 긴 식각 시간이 가장자리 손상 확률을 키웁니다. 식각량과 잔류막 사이의 균형을 확인하세요.',chain:['RF 파워 · 식각량 증가','가장자리의 제거 편차 증가','파워 또는 시간을 한 변수씩 비교']},
      '잔류막':{title:'패턴이 완전히 열리지 않았어요.',description:'노광·베이크·현상 조건이 부족하면 PR 잔사가 남습니다. 산화막이 식각량보다 두꺼운 경우도 함께 확인하세요.',chain:['PR 현상 또는 산화막 제거 부족','개구부에 PR / 산화막 잔류','노광부터 단면을 따라가며 확인']},
      '패턴 편차':{title:'마스크와 다른 패턴이 만들어져요.',description:'초점, 노광량, 베이크 조건이 패턴 폭 편차에 영향을 주었습니다. 공정창 분석으로 안정적인 구간을 찾아보세요.',chain:['광학 · 베이크 조건의 편차','현상 후 개구 폭 CD 변화','초점과 노광량의 공정창 비교']},
      '배경 결함':{title:'패턴이 안정적으로 형성되었어요.',description:'주요 조건은 목표 범위에 가깝습니다. 남은 결함은 합성 배경 결함일 수 있습니다. 반복 분석에서 변동을 확인하세요.',chain:['안정된 공정 조건','잔사와 과식각 감소','같은 레시피의 반복 실험 확인']}
    };
    const tip=tips[r.dominant];setText('#causeTitle',tip.title);setText('#causeDescription',tip.description);$('#causalChain').innerHTML=tip.chain.map((s,i)=>`${i?'<div class="chain-arrow">↓</div>':''}<div class="chain-item">${s}</div>`).join('');
    setText('#hintContent',mission().hint);
    setText('#goalTitle',result.passed?'✓ 최근 실행에서 미션 목표 달성':'○ 미션 진행 중');setText('#goalDescription',result.passed?'가설과 결과를 리포트에 남기고 다음 미션에 도전하세요.':`최근 실행 ${result.yield}% · 목표 ${mission().target}% / $${mission().budget} 이하`);
  }
  function renderMetrics(){const r=result;setText('#yieldValue',r.yield.toFixed(1));const delta=r.yield-baseline.yield;setText('#yieldDelta',selectedRun==='BASELINE'?'기준 레시피':`${delta>=0?'+':''}${delta.toFixed(1)}%p`);$('#yieldDelta').classList.toggle('negative',delta<0);setText('#defectValue',r.bad);setText('#dieTotal',`전체 ${r.total}개 다이`);setText('#defectPattern',r.dominant);setText('#costValue',r.cost.toFixed(2));setText('#timeValue',r.cycleTime.toFixed(1));setText('#resultOrigin',selectedRun);setText('#runLabel',selectedRun);$('#yieldProgress').style.width=r.yield+'%';}
  function renderHistory(){
    const runs=history.filter(r=>r.missionId===missionId);setText('#experimentCount',`${runs.length} runs`);setText('#noteCount',history.length);
    const rows=[...runs.slice(-4).reverse(),{id:'baseline',params:mission().defaults,hypothesis:'공정 조건을 바꾸기 전 비교 기준',missionId}];
    $('#historyBody').innerHTML=rows.map(r=>{const output=E.simulate(r.params,r.missionId);const isBase=r.id==='baseline';return `<tr><td>${isBase?'BASELINE':esc(r.label)}${isBase?'':'<small>'+esc(r.time?.slice(11,16)||'')+'</small>'}</td><td title="${esc(changed(r.params))}">${esc(shortChanges(r.params))}</td><td class="table-hypothesis">${esc(r.hypothesis||'가설을 기록하지 않았습니다.')}</td><td class="mono">${output.yield.toFixed(1)}%</td><td class="mono">$${output.cost.toFixed(2)}</td><td><span class="result-pill ${output.passed?'success':''}">${output.passed?'목표 달성':'개선 중'}</span></td><td><button class="row-restore" data-restore="${esc(r.id)}">불러오기 ↗</button></td></tr>`;}).join('');
  }
  function renderAll(){renderMission();renderStage();renderVisual();renderReasoning();renderMetrics();renderHistory();renderDraft();}
  async function runSimulation(){
    if(running)return;stopPlayback();running=true;const snapshot={...params},hypothesis=$('#hypothesis').value.trim();$('#runSimulation').disabled=true;$$('[data-param]').forEach(i=>i.disabled=true);document.body.classList.add('running');setText('#runText','전체 공정 계산 중…');
    await new Promise(resolve=>setTimeout(resolve,650));
    result=E.simulate(snapshot,missionId);const number=history.filter(r=>r.missionId===missionId).length+1;selectedRun=`RUN ${String(number).padStart(3,'0')}`;
    history.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),label:selectedRun,time:new Date().toISOString(),missionId,params:snapshot,hypothesis,modelVersion:E.version});history=history.slice(-200);
    preview=result;running=false;$('#runSimulation').disabled=false;document.body.classList.remove('running');setText('#runText','전체 공정 실행');renderAll();persist();toast(result.passed?'미션 목표 달성! 실험이 포트폴리오 노트에 저장되었습니다.':'실험 완료 · 조건과 결과를 기록했습니다.');
  }
  function loadMission(id){if(running)return;stopPlayback();window.WaferMachine?.pause();missionId=id;params=E.normalize(mission().defaults);baseline=E.simulate(params,id);result=baseline;preview=result;selectedRun='BASELINE';stageIndex=mission().focusStage;compare=false;$('#compareToggle').setAttribute('aria-pressed','false');$('#hypothesis').value='';$('#hintContent').hidden=true;renderAll();showPage('lab');persist();}
  function restoreRun(id){if(running)return;const entry=id==='baseline'?{params:mission().defaults,missionId,hypothesis:'',label:'BASELINE'}:history.find(r=>r.id===id);if(!entry)return;stopPlayback();missionId=entry.missionId;params=E.normalize(entry.params);baseline=E.simulate(mission().defaults,missionId);result=E.simulate(params,missionId);preview=result;selectedRun=entry.label;$('#hypothesis').value=entry.hypothesis;renderAll();showPage('lab');persist();toast('레시피와 해당 실행 결과를 불러왔습니다.');}
  const names={lab:'공정 시뮬레이터',missions:'불량 분석 미션',analytics:'실험 · 통계 분석',notebook:'포트폴리오 노트',research:'공정 지식 · 리서치'};
  function showPage(next){if(!names[next])return;stopPlayback();window.WaferMachine?.pause();page=next;$$('.page').forEach(el=>el.hidden=el.id!==`page-${next}`);$$('.nav-item').forEach(el=>{el.classList.toggle('active',el.dataset.page===next);if(el.dataset.page===next)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});setText('#pageBreadcrumb',names[next]);if(next==='missions')renderMissions();if(next==='notebook')renderNotebook();if(next==='analytics')analyze();if(next==='research')renderResearch();}
  function renderMissions(){$('#missionCards').innerHTML=E.missions.map(m=>`<article class="mission-card ${m.id===missionId?'active':''}"><span>${m.code} / ${m.level}</span><div class="mission-art"><div class="mini-wafer ${m.id}"></div></div><h2>${m.title}</h2><p>${m.description}</p><div class="mission-goals"><span>수율 ≥ ${m.target}%</span><span>가상 비용 ≤ $${m.budget}</span></div><button class="button ${m.id===missionId?'secondary':'primary'}" data-mission="${m.id}">${m.id===missionId?'기준 조건으로 다시 시작':'이 미션 시작하기'} ↗</button></article>`).join('');}
  function renderNotebook(){
    const passed=new Set(history.filter(r=>E.simulate(r.params,r.missionId).passed).map(r=>r.missionId));
    $('#reportSummary').innerHTML=`<div class="report-stat"><span>기록된 실험</span><strong>${history.length}</strong></div><div class="report-stat"><span>목표 달성 미션</span><strong>${passed.size} / 3</strong></div><div class="report-stat"><span>저장한 레시피</span><strong>${recipes.length}</strong></div>`;
    $('#savedRecipes').innerHTML=recipes.length?recipes.slice().reverse().map(r=>`<article class="saved-recipe"><div><h3>${esc(r.name)}</h3><p>${esc(changed(r.params,E.missions.find(m=>m.id===r.missionId).defaults))}</p><small>${esc(r.time?.slice(0,10))} · ${r.missionId.toUpperCase()}</small></div><button class="button secondary" data-load-recipe="${esc(r.id)}">레시피 불러오기 ↗</button></article>`).join(''):'<div class="empty-state">실습실의 ‘레시피 저장’으로 다시 사용할 조건을 보관하세요.</div>';
    $('#reportCards').innerHTML=history.length?history.slice().reverse().map(r=>{const out=E.simulate(r.params,r.missionId);return `<article class="report-card"><div><h3>${esc(r.label)} · ${E.missions.find(m=>m.id===r.missionId).title}</h3><p class="hypothesis-text">${esc(r.hypothesis||'이 실험에는 가설이 기록되지 않았습니다.')}</p><p>${esc(changed(r.params,E.missions.find(m=>m.id===r.missionId).defaults))}</p><small>${esc(r.time)} · ${E.version} · SEED ${out.seed}</small></div><div class="report-result">${out.yield}%<small>$${out.cost.toFixed(2)} · ${out.bad} / ${out.total} 불량</small><button class="row-restore" data-restore="${esc(r.id)}">이 실험 불러오기 ↗</button></div></article>`;}).join(''):'<div class="empty-state">아직 기록된 실험이 없습니다. 조건을 바꾸고 ‘전체 공정 실행’을 눌러 첫 기록을 만드세요.</div>';
  }
  function lineChart(points){const x=i=>48+i*440/(points.length-1),y=v=>188-v*1.5;return `<svg viewBox="0 0 520 225" class="chart-svg" role="img" aria-label="변수별 합성 수율 공정창"><path d="M48 30v158h445" fill="none" stroke="#425762"/>${[0,25,50,75,100].map(v=>`<path d="M48 ${y(v)}h440" stroke="#2f444e" stroke-dasharray="3 5"/><text x="17" y="${y(v)+3}">${v}%</text>`).join('')}<polyline points="${points.map((p,i)=>`${x(i)},${y(p.yield)}`).join(' ')}" fill="none" stroke="#cce990" stroke-width="2"/>${points.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p.yield)}" r="4" fill="#cce990"/><text x="${x(i)}" y="207" text-anchor="middle">${p.value}</text>`).join('')}</svg>`;}
  function histogramChart(hist){const max=Math.max(...hist.counts,1);return `<svg viewBox="0 0 520 210" class="chart-svg" role="img" aria-label="웨이퍼 내 식각 깊이 빈도 분포">${hist.counts.map((n,i)=>`<rect x="${42+i*57}" y="${165-n/max*128}" width="42" height="${n/max*128}" rx="2" fill="#68b5a4"/><text x="${63+i*57}" y="${155-n/max*128}" text-anchor="middle">${n}</text>`).join('')}<path d="M34 165h470" stroke="#4a626b"/><text x="36" y="190">${hist.min} nm</text><text x="410" y="190">${hist.max} nm</text></svg>`;}
  function analyze(){
    const key=$('#sweepParameter').value||'dose';const snapshot={...params};const output=E.simulate(snapshot,missionId);analysis={version:E.version,source:'synthetic-educational-model',missionId,params:snapshot,key,sweep:E.sweep(snapshot,missionId,key),repeat:E.monteCarlo(snapshot,missionId),histogram:output.histogram,distribution:output.distribution,createdAt:new Date().toISOString()};
    const a=analysis;setText('#analysisContext',`${mission().code} · 현재 설정 기준 · ${E.fields[key].unit}`);
    $('#analysisOutput').innerHTML=`<div class="analysis-grid"><article class="panel analysis-panel"><h2>공정창 · ${E.fields[key].label}</h2><p>나머지 조건과 시드를 고정하고 9개 값을 비교합니다. 아래 표에서 조건을 실습실에 적용할 수 있습니다.</p>${lineChart(a.sweep)}</article><article class="panel analysis-panel"><h2>웨이퍼 내 식각 깊이 분포</h2><p>${output.total}개 합성 다이의 최종 식각 깊이 · 평균 ${a.histogram.mean} nm · 모집단 표준편차 ${a.histogram.sigma} nm</p>${histogramChart(a.histogram)}</article><article class="panel analysis-panel"><h2>30회 시드 반복 · 수율 변동</h2><p>레시피를 고정하고 배경 난수만 변경합니다. 제조 변동의 실측 분포가 아닙니다.</p><div class="analysis-stats"><div><strong>${a.repeat.mean}%</strong><small>표본 평균 수율</small></div><div><strong>${a.repeat.sd}</strong><small>표본 표준편차 (%p)</small></div><div><strong>30</strong><small>합성 웨이퍼</small></div></div><p>평균의 정규 근사 95% 구간: ${a.repeat.interval[0]}–${a.repeat.interval[1]}%<br>최솟값–최댓값: ${a.repeat.min}–${a.repeat.max}%<br>이 구간은 실제 팹 수율이나 모델의 정확도를 보증하지 않습니다.</p></article><article class="panel analysis-panel"><h2>합성 불량 유형 집계</h2><p>관측된 불량 다이에 가장 높은 모델 위험 요인을 붙인 분류입니다. 실제 불량 원인의 추정 알고리즘은 아닙니다.</p><div class="table-scroll"><table class="stats-table"><thead><tr><th>유형</th><th>다이 수</th><th>전체 다이 대비</th></tr></thead><tbody>${a.distribution.map(d=>`<tr><td>${d.kind}</td><td>${d.count}</td><td>${(d.count/output.total*100).toFixed(1)}%</td></tr>`).join('')}</tbody></table></div></article></div><section class="panel stats-table"><div class="panel-heading"><h2>9조건 실험표</h2><span class="mono">ONE FACTOR AT A TIME</span></div><div class="table-scroll"><table><thead><tr><th>${E.fields[key].label}</th><th>모델 수율</th><th>가상 비용</th><th>미션 목표</th><th>실습 연결</th></tr></thead><tbody>${a.sweep.map((r,i)=>`<tr><td>${r.value} ${E.fields[key].unit}</td><td>${r.yield}%</td><td>$${r.cost.toFixed(2)}</td><td>${r.passed?'달성':'미달성'}</td><td><button data-sweep="${i}" class="row-restore">이 조건 적용 ↗</button></td></tr>`).join('')}</tbody></table></div></section>`;
  }
  function renderResearch(){
    const products=[['Synopsys Sentaurus','공정·소자 수치 해석','이온주입·확산·산화 및 2D/3D 공정 모델링','https://www.synopsys.com/manufacturing/tcad/process-simulation.html'],['Silvaco Victory Process','TCAD 공정 시뮬레이션','레이아웃 기반 공정·구조와 제조성 검토','https://silvaco.com/tcad/victory-process-3d/'],['Lam SEMulator3D','3D 가상 공정','공정 흐름, 구조 변화, 수율·공정창 분석','https://www.lamresearch.com/product/semulator3d/'],['COMSOL Plasma Module','플라즈마 다중물리 해석','방전·수송·표면 반응에 따른 식각 및 증착','https://www.comsol.com/plasma-module'],['ASML Computational Lithography','계산 리소그래피','장비·시험 웨이퍼로 보정한 패터닝 모델','https://www.asml.com/en/products/computational-lithography'],['KLA PROLITH','리소그래피·패터닝','광학·재료·공정 조건에 따른 패턴 시뮬레이션','https://www.spts.com/products/software-solutions/semiconductor'],['Purdue vFabLab','가상 클린룸 교육','장비와 제조 공정의 가상 실습','https://engineering.purdue.edu/Engr/AboutUs/News/Spotlights/2023/2023-1113-vfablab']];
    $('#researchContent').innerHTML=`<div class="wide-note"><div><h2>이 프로젝트의 위치: 공정을 관찰하고 설명하는 포트폴리오 실습실</h2><p>3D 공정, 가상 교육, 수율 분석 자체는 기존 제품에도 있습니다. 이 프로젝트는 브라우저에서 포토 공정의 장면·단면·불량 맵·실험 근거를 함께 연결하는 경험을 차별화 가설로 삼습니다. 세계 최초 또는 실제 TCAD 정확도를 주장하지 않습니다.</p></div></div><section class="panel research-table"><div class="panel-heading"><h2>상용·공개 도구 비교</h2></div><div class="table-scroll"><table><thead><tr><th>도구</th><th>주요 범위</th><th>공개된 기능 요약</th><th>공식 자료</th></tr></thead><tbody>${products.map(p=>`<tr><td>${p[0]}</td><td>${p[1]}</td><td>${p[2]}</td><td><a href="${p[3]}" target="_blank" rel="noopener noreferrer">확인 ↗</a></td></tr>`).join('')}</tbody></table></div></section><div class="research-grid"><article class="panel research-card"><span class="tiny-label">01 / PHOTOLITHOGRAPHY</span><h2>포토 공정의 원리</h2><p>웨이퍼 준비, PR 도포, 소프트베이크, 노광, 선택적 PEB, 현상으로 이어지는 흐름을 참고했습니다. 현재 화면에는 앞뒤의 산화·식각·PR 제거를 포함합니다. 화면의 8단계는 ‘반도체 8대 공정’ 전체와 다릅니다.</p><a href="https://www.cleanroom.byu.edu/SOP_05PR" target="_blank" rel="noopener noreferrer">BYU Cleanroom · Photolithography ↗</a><br><a href="https://www.microchemicals.com/DOWNLOADS/Application-Notes/" target="_blank" rel="noopener noreferrer">MicroChemicals · 공정·불량 원리 ↗</a></article><article class="panel research-card"><span class="tiny-label">02 / PUBLIC PDK ≠ FAB RECIPE</span><h2>공개 PDK와 공정 IP의 경계</h2><p>SKY130의 공개 설계 규칙과 레이어 자료는 확장 조사 대상으로 정리했습니다. PDK는 제조 장비 레시피 전체가 아니며, 이 앱이 SKY130을 실행하거나 검증한 것은 아닙니다. 비공개 IP는 포함하지 않습니다.</p><a href="https://skywater-pdk.readthedocs.io/en/main/rules.html" target="_blank" rel="noopener noreferrer">SKY130 · 공개 설계 규칙 ↗</a></article><article class="panel research-card"><span class="tiny-label">03 / MODEL PROVENANCE</span><h2>공개 원리 + 교육용 계수</h2><p>산화막은 Deal–Grove 형태를, PR 두께는 회전 속도의 역제곱근 관계를 사용합니다. 식각·현상·CD·비용·수율 계수는 자체 교육용 가정입니다. 365 nm, 500 nm CD 예시는 특정 팹 공정이나 공정 노드를 뜻하지 않습니다.</p><a href="https://ocw.mit.edu/courses/6-774-physics-of-microfabrication-front-end-processing-fall-2004/resources/mit6_774f04_lec06_mp4/" target="_blank" rel="noopener noreferrer">MIT OCW · 산화 모델 ↗</a><br><a href="https://www.asml.com/en/technology/lithography-principles/lenses-and-mirrors" target="_blank" rel="noopener noreferrer">ASML · 광학과 해상도 원리 ↗</a></article><article class="panel research-card"><span class="tiny-label">04 / DATA & STATISTICS</span><h2>통계가 어디서 나왔는가</h2><p>수율·히스토그램·불량 집계·30회 반복 통계는 engine.js가 생성한 합성 다이로 계산합니다. WM-811K 같은 실측 데이터셋은 현재 가져오지 않았습니다. 모델 검증용 실제 데이터 연계는 다음 개발 단계입니다.</p></article></div>`;
  }
  function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function exportReport(){
    const r=result;const notes=history.filter(h=>h.missionId===missionId);const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WaferFlow 실험 리포트</title><style>body{font:14px/1.9 system-ui,sans-serif;max-width:950px;margin:45px auto;padding:0 25px;color:#173332}h1{font-size:30px}h2{margin-top:34px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border:1px solid #cdd9d4;text-align:left}small{color:#54736c}.summary{padding:20px;background:#eff5e7;font-size:19px}.scene-svg{max-width:500px}.scene-svg text{fill:#435f5d}p{overflow-wrap:anywhere}@media print{body{margin:0;max-width:none}tr{break-inside:avoid}}</style><h1>WaferFlow · 공정 실험 리포트</h1><p>${esc(mission().title)}</p><small>생성 ${new Date().toISOString()} · ${E.version} · SEED ${r.seed} · 교육용 합성 모델</small><p class="summary">${esc(selectedRun)} · 수율 ${r.yield}% · 불량 ${r.bad}/${r.total} · 가상 비용 $${r.cost.toFixed(2)}</p><p>이 리포트는 최근 표시된 실행 결과를 기준으로 합니다. 실행 전 미리보기 변경은 포함하지 않습니다. 실제 장비 결과나 제조용 검증 자료가 아닙니다.</p><h2>재현 조건</h2><table><tr><th>변수</th><th>값</th></tr>${Object.entries(r.params).map(([k,v])=>`<tr><td>${E.fields[k].label}</td><td>${v} ${E.fields[k].unit}</td></tr>`).join('')}</table><h2>웨이퍼 맵</h2>${V.map(r,false)}<h2>가설과 실험 기록</h2>${notes.map(h=>{const o=E.simulate(h.params,h.missionId);return `<article><h3>${esc(h.label)} · ${o.yield}% · $${o.cost.toFixed(2)}</h3><p>${esc(h.hypothesis||'가설 미기록')}</p><small>${esc(changed(h.params))} · ${esc(h.time)}</small></article>`;}).join('')||'<p>아직 실행한 실험이 없습니다.</p>'}<h2>모델 해석</h2><p>공개 공정 원리를 참고한 단순화 모델입니다. 수율과 불량 유형은 다이별 합성 판정으로 계산하며, 가상 비용은 임의의 학습용 비용 함수입니다. 변수를 바꾸는 사고 과정을 설명하는 용도입니다.</p><p>공정 참고: <a href="https://www.cleanroom.byu.edu/SOP_05PR">BYU Cleanroom</a> · <a href="https://www.microchemicals.com/DOWNLOADS/Application-Notes/">MicroChemicals</a></p></html>`;
    download(`waferflow-${missionId}-report.html`,html,'text/html;charset=utf-8');toast('실험 리포트를 저장했습니다. 브라우저에서 열어 PDF로 인쇄할 수 있습니다.');
  }
  function exportCSV(){if(!history.length){toast('먼저 전체 공정을 실행해 실험을 기록하세요.');return;}const cell=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};const keys=Object.keys(E.fields);const rows=[['run','mission','time','hypothesis','model_version','seed','yield_percent','failed_dies','total_dies','virtual_cost_usd',...keys],...history.map(h=>{const r=E.simulate(h.params,h.missionId);return[h.label,h.missionId,h.time,h.hypothesis,E.version,r.seed,r.yield,r.bad,r.total,r.cost,...keys.map(k=>h.params[k])];})];download('waferflow-experiments.csv','\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');toast('전체 실험 CSV를 저장했습니다.');}
  function openInfo(kind){$('#dialogContent').innerHTML=kind==='guide'?'<h2>웨이퍼 위에서 시작하는 첫 실험</h2><ol><li>상단에서 공정 단계를 선택하고, 재생 버튼으로 전체 흐름을 확인하세요.</li><li>노광에서는 빛을 받은 PR의 상태가 변하고, 현상에서 그 부분이 제거됩니다.</li><li>공정 장면·웨이퍼 단면·불량 맵을 오가며 잔사와 패턴을 관찰하세요.</li><li>한 변수를 바꾸고 가설을 기록한 뒤 전체 공정을 실행하세요.</li><li>기준 비교와 통계 분석으로 근거를 확인하고 리포트를 내보내세요.</li></ol><p>이 시뮬레이터는 포토 공정과 인접 단계를 시각화합니다. 실장비 조작 화면 또는 물리 해석 TCAD는 아닙니다.</p>':'<h2>관찰을 위한 모델, 재현 가능한 실험</h2><p>공개 원리를 참고해 독립적으로 작성한 교육용 시뮬레이터입니다. 장면은 공정의 개념을 보여주는 비축척 시각화입니다.</p><h3>수치의 출처</h3><p>산화·스핀 코팅의 함수 형태는 공개 원리를 참고했습니다. 파라미터, 불량 확률, 비용 계수는 학습을 위한 자체 가정입니다. 공개 PDK나 실제 팹 데이터를 실행한 결과가 아닙니다.</p><h3>실행과 미리보기</h3><p>장면·단면·불량 맵과 단서는 현재 설정의 미리보기입니다. 하단 KPI와 기록은 마지막으로 실행한 조건입니다. 동일 조건과 시드에서는 동일 결과가 나옵니다.</p><h3>통계 해석</h3><p>반복 분석의 구간은 합성 표본 평균에 대한 정규 근사입니다. 실제 공정 수율, 모델 오차 또는 양산 품질의 신뢰구간이 아닙니다.</p><p>상세 출처는 ‘공정 지식 · 리서치’에서 확인하세요.</p>';$('#infoDialog').showModal();}
  document.addEventListener('click',event=>{
    const b=event.target.closest('button');if(!b)return;
    if(b.dataset.page){showPage(b.dataset.page);return;}
    if(b.dataset.stage!==undefined){setStage(Number(b.dataset.stage));return;}
    if(b.dataset.view){view=b.dataset.view;$$('[data-view]').forEach(el=>{const selected=el.dataset.view===view;el.classList.toggle('selected',selected);el.setAttribute('aria-pressed',String(selected));});renderVisual();return;}
    if(b.dataset.mission){loadMission(b.dataset.mission);return;}
    if(b.dataset.restore){restoreRun(b.dataset.restore);return;}
    if(b.dataset.loadRecipe){if(running)return;const r=recipes.find(item=>item.id===b.dataset.loadRecipe);if(!r)return;loadMission(r.missionId);params=E.normalize(r.params);renderStage();updatePreview();toast('저장 레시피 적용 · 실행하면 새 결과가 기록됩니다.');return;}
    if(b.dataset.sweep!==undefined&&analysis){if(running)return;missionId=analysis.missionId;baseline=E.simulate(mission().defaults,missionId);params={...analysis.params,[analysis.key]:analysis.sweep[Number(b.dataset.sweep)].value};params=E.normalize(params);stageIndex=E.stages.findIndex(s=>s.fields.includes(analysis.key));showPage('lab');renderAll();updatePreview();toast('스윕 조건을 적용했습니다. 전체 공정을 실행해 기록하세요.');return;}
    if(b.classList.contains('close-dialog'))b.closest('dialog').close();
  });
  $('#parameterControls').addEventListener('input',event=>{const key=event.target.dataset.param;if(!key||running)return;stopPlayback();window.WaferMachine?.pause();progress=1;params[key]=Number(event.target.value);const f=E.fields[key];event.target.style.setProperty('--pct',`${(params[key]-f.min)/(f.max-f.min)*100}%`);$(`#value-${key}`).innerHTML=`${params[key]}<small>${f.unit}</small>`;updatePreview();});
  $('#visualization').addEventListener('click',event=>{const die=event.target.closest('[data-die]');if(!die)return;const d=preview.dies[Number(die.dataset.die)];setText('#dieInspector',`다이 (${d.x}, ${d.y}) · ${d.kind} · 식각 ${d.depth} nm · 잔류 ${d.residue} nm · CD ${d.cd} nm`);});
  $('#runSimulation').addEventListener('click',runSimulation);
  $('#resetRecipe').addEventListener('click',()=>{if(running)return;stopPlayback();params=E.normalize(mission().defaults);renderStage();updatePreview();toast('현재 미션의 기본 조건으로 되돌렸습니다.');});
  $('#compareToggle').addEventListener('click',()=>{compare=!compare;$('#compareToggle').setAttribute('aria-pressed',String(compare));renderVisual();});
  $('#hintButton').addEventListener('click',()=>{$('#hintContent').hidden=!$('#hintContent').hidden;});
  $('#hypothesis').value=typeof saved.hypothesis==='string'?saved.hypothesis.slice(0,500):'';
  $('#hypothesis').addEventListener('input',persist);
  $('#guideButton').addEventListener('click',()=>openInfo('guide'));$('#modelInfo').addEventListener('click',()=>openInfo('model'));$('#footerModelInfo').addEventListener('click',()=>showPage('research'));
  $('#saveRecipe').addEventListener('click',()=>{$('#recipeName').value=`${mission().subtitle} · 레시피 ${recipes.length+1}`;$('#saveDialog').showModal();});
  $('#saveForm').addEventListener('submit',event=>{event.preventDefault();const name=$('#recipeName').value.trim();if(!name){$('#recipeName').setCustomValidity('레시피 이름을 입력하세요.');$('#recipeName').reportValidity();return;}recipes.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name,missionId,params:{...params},time:new Date().toISOString()});recipes=recipes.slice(-50);persist();$('#saveDialog').close();toast('레시피를 포트폴리오 노트에 저장했습니다.');});$('#recipeName').addEventListener('input',()=>$('#recipeName').setCustomValidity(''));
  $('#exportReport').addEventListener('click',exportReport);$('#exportAll').addEventListener('click',exportCSV);
  $('#sweepParameter').innerHTML=Object.entries(E.fields).map(([key,f])=>`<option value="${key}" ${key==='dose'?'selected':''}>${f.label}</option>`).join('');
  $('#runAnalysis').addEventListener('click',analyze);$('#sweepParameter').addEventListener('change',analyze);$('#exportStats').addEventListener('click',()=>{if(!analysis)analyze();download('waferflow-synthetic-statistics.json',JSON.stringify(analysis,null,2),'application/json');toast('모델·조건·시드를 포함한 통계 JSON을 저장했습니다.');});
  $('#playProcess').addEventListener('click',()=>{if(playing){stopPlayback();return;}playing=true;stageIndex=0;progress=0;playbackStart=performance.now();renderStage();$('#playProcess').innerHTML=icon('pause');$('#playProcess').setAttribute('aria-label','공정 재생 일시정지');let lastDraw=0;function tick(now){if(!playing)return;const elapsed=now-playbackStart;const index=Math.min(7,Math.floor(elapsed/2600));if(index!==stageIndex)setStage(index,true);progress=Math.min(1,(elapsed%2600)/2600);if(now-lastDraw>90){renderVisual();setText('#playbackDescription',`공정 흐름 재생 · ${Math.round(progress*100)}% (설명용 시간)`);lastDraw=now;}if(elapsed>=20800){progress=1;stopPlayback();renderVisual();setText('#playbackDescription','전체 흐름 완료 · 조건을 바꾸고 실험해 보세요.');return;}frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);});
  document.addEventListener('keydown',event=>{if(event.key==='Enter'&&page==='lab'&&!event.target.closest('input,textarea,button,select,dialog,a')){event.preventDefault();runSimulation();}});
  window.WaferAppBridge={snapshot:()=>({params:{...params},result:preview,stageIndex,missionId}),loadRecipe:entry=>{if(!entry||!validMission(entry.scenario)||!entry.params||!Object.keys(E.fields).every(k=>Number.isFinite(entry.params[k])))throw new Error('지원하지 않는 검토 레시피입니다.');stopPlayback();window.WaferMachine?.pause();missionId=entry.scenario;params=E.normalize(entry.params);baseline=E.simulate(mission().defaults,missionId);result=baseline;preview=E.simulate(params,missionId);selectedRun='BASELINE';$('#hypothesis').value=String(entry.reason||'').slice(0,500);stageIndex=3;progress=1;renderAll();showPage('lab');persist();},selectStage:index=>{stopPlayback();stageIndex=index;progress=1;renderStage();renderVisual();}};
  paintIcons();$$('.nav-item').forEach(el=>el.setAttribute('aria-label',names[el.dataset.page]));renderAll();
})();
