/* Evidence evaluation: explicit provenance, LOT-grouped chronological holdout, no release authority. */
(function(root){
  'use strict';
  const M=root.MemoryFab,VERSION='wf-evidence-0.1.0',SCHEMA='waferflow-process-evidence-v1';
  const field=(label,unit,min,max,value)=>({label,unit,min,max,default:value});
  const profiles={
    har:{name:'HAR 식각 깊이',metric:'etch_depth_nm',unit:'nm',defaultStep:'C02',inputs:{target_nm:field('목표 깊이','nm',1,100000,4200),power_w:field('RF 파워','W',600,1400,1000),pressure_mtorr:field('압력','mTorr',8,35,15),time_s:field('처리 시간','s',90,180,120)},limits:{mae:30,bias:20,maxError:80}},
    cvd:{name:'CVD 막 두께',metric:'film_nm',unit:'nm',defaultStep:'B01',inputs:{target_nm:field('목표 두께','nm',1,100000,400),temperature_c:field('온도','°C',300,500,400),flow_sccm:field('가스 유량','sccm',70,130,100)},limits:{mae:5,bias:3,maxError:15}},
    cmp:{name:'CMP 잔여 단차',metric:'topography_nm',unit:'nm',defaultStep:'B05',inputs:{before_nm:field('입력 단차','nm',0,10000,20),pressure_psi:field('헤드 압력','psi',1.5,4.5,3),rpm:field('회전 속도','rpm',40,90,60),time_s:field('연마 시간','s',40,100,60)},limits:{mae:.5,bias:.3,maxError:1.5}}
  };
  const copy=x=>JSON.parse(JSON.stringify(x)),mean=a=>a.reduce((s,v)=>s+v,0)/a.length;
  const freeze=o=>{Object.values(o).forEach(v=>{if(v&&typeof v==='object')freeze(v);});return Object.freeze(o);};
  function fail(message){throw Error(message);}
  function text(value,label,max=160){if(typeof value!=='string'||!value.trim()||value.length>max||/[\x00-\x1f]/.test(value))fail(label+' 문자열을 확인하세요.');return value.trim();}
  function finite(value,label,min=0,max=1e9){if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max)fail(label+' 숫자 범위를 확인하세요.');return value;}
  function date(value,label){
    if(typeof value!=='string')fail(label+' ISO 시각이 필요합니다.');const m=value.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,3}))?(Z|[+-]\d{2}:\d{2})$/);
    if(!m)fail(label+'에 초와 시간대(Z 또는 ±HH:MM)를 포함하세요.');const y=+m[1],month=+m[2],day=+m[3],h=+m[4],minute=+m[5],s=+m[6],check=new Date(Date.UTC(y,month-1,day));
    if(y<1970||y>2200||check.getUTCFullYear()!==y||check.getUTCMonth()!==month-1||check.getUTCDate()!==day||h>23||minute>59||s>59||m[8]!=='Z'&&(+m[8].slice(1,3)>14||+m[8].slice(4)>59||+m[8].slice(1,3)===14&&+m[8].slice(4)!==0))fail(label+'가 유효한 시각이 아닙니다.');
    return new Date(value).toISOString();
  }
  function inputs(kind,raw){const p=profiles[kind];if(!p||!raw||typeof raw!=='object'||Array.isArray(raw))fail('입력 조건 객체가 필요합니다.');if(Object.keys(raw).some(k=>!Object.hasOwn(p.inputs,k)))fail('지원하지 않는 입력 조건이 있습니다.');return Object.fromEntries(Object.entries(p.inputs).map(([k,f])=>[k,finite(raw[k],f.label,f.min,f.max)]));}
  function normalize(raw){
    if(!raw||raw.schema!==SCHEMA)fail('지원하는 근거 데이터 스키마가 아닙니다.');if(!Object.hasOwn(profiles,raw.profile))fail('HAR·CVD·CMP 응답만 검증할 수 있습니다.');
    const p=profiles[raw.profile];if(raw.modelVersion!==M.RESPONSE_VERSION)fail('응답 모델 버전이 다릅니다.');const scope={};for(const k of ['product','referenceStepId','sourceStepId','equipmentId','chamberId','recipeRevision','metrologyId','metrologyMethod'])scope[k]=text(raw.scope?.[k],k);
    if(!Object.hasOwn(M.products,scope.product)||!M.products[scope.product].route.some(s=>s.id===scope.referenceStepId&&s.tool===raw.profile))fail('제품·참조 공정과 응답 모델이 일치하지 않습니다.');
    if(!['synthetic','user-measurement'].includes(raw.origin?.kind))fail('출처 종류를 명시하세요.');const origin={kind:raw.origin.kind,source:text(raw.origin.source,'출처',500),verification:'unverified'};
    const units={...Object.fromEntries(Object.entries(p.inputs).map(([k,f])=>[k,f.unit])),measured:p.unit};if(!raw.units||JSON.stringify(Object.keys(raw.units).sort())!==JSON.stringify(Object.keys(units).sort())||Object.entries(units).some(([k,u])=>raw.units[k]!==u))fail('단위가 모델과 다릅니다. 명시된 단위로 변환한 파일을 사용하세요.');
    if(!Array.isArray(raw.observations)||!raw.observations.length||raw.observations.length>5000)fail('관측값은 1–5,000개여야 합니다.');const ids=new Set(),keys=new Set();
    const observations=raw.observations.map((row,index)=>{const n=index+1;if(!row||typeof row!=='object')fail(n+'행이 올바르지 않습니다.');const r={};for(const k of ['id','lotId','waferId','runId'])r[k]=text(row[k],n+'행 '+k,80);if(ids.has(r.id))fail(n+'행 관측 ID가 중복됩니다.');ids.add(r.id);const key=JSON.stringify([r.lotId,r.waferId,r.runId]);if(keys.has(key))fail(n+'행 LOT·웨이퍼·실행의 계측값이 중복됩니다. 위치별 값은 먼저 정의된 방식으로 집계하세요.');keys.add(key);r.processedAt=date(row.processedAt,n+'행 공정 완료');r.measuredAt=date(row.measuredAt,n+'행 계측 완료');if(r.measuredAt<r.processedAt)fail(n+'행 계측 시각이 공정 완료보다 빠릅니다.');r.inputs=inputs(raw.profile,row.inputs);r.measured=finite(row.measured,n+'행 계측값',0,1e7);return r;}).sort((a,b)=>a.processedAt.localeCompare(b.processedAt)||a.id.localeCompare(b.id));
    return freeze({schema:SCHEMA,modelVersion:M.RESPONSE_VERSION,datasetId:text(raw.datasetId,'데이터 ID'),profile:raw.profile,scope,origin,units,observations});
  }
  function configuration(raw={}){const method=raw.method??'affine',trainFraction=raw.trainFraction??.7;if(!['affine','bias'].includes(method)||![.6,.7,.8].includes(trainFraction))fail('보정 방식 또는 분할 비율을 확인하세요.');const limits={};for(const k of ['mae','bias','maxError'])limits[k]=finite(raw.limits?.[k],k+' 허용 오차',0,1e7);return{method,trainFraction,limits,minTrainLots:6,minValidationLots:3,split:'chronological-lot'};}
  function groupRows(rows){const groups=new Map();rows.forEach(r=>{if(!groups.has(r.lotId))groups.set(r.lotId,[]);groups.get(r.lotId).push(r);});return [...groups].map(([lotId,rows])=>({lotId,rows,first:rows.map(r=>r.processedAt).sort()[0],last:rows.map(r=>r.measuredAt).sort().at(-1)})).sort((a,b)=>a.first.localeCompare(b.first)||a.lotId.localeCompare(b.lotId));}
  function prepare(raw,rawConfig){
    const dataset=normalize(raw),config=configuration(rawConfig),groups=groupRows(dataset.observations),count=Math.floor(groups.length*config.trainFraction),training=groups.slice(0,count),validation=groups.slice(count);
    if(training.length<config.minTrainLots||validation.length<config.minValidationLots)fail('보정 6 LOT 이상, 검증 3 LOT 이상이 필요합니다. 현재 '+training.length+' / '+validation.length+' LOT입니다. 이는 제품의 최소 예제 규칙이며 통계적 충분성을 보장하지 않습니다.');
    const cutoff=training.map(g=>g.last).sort().at(-1),firstValidation=validation.map(g=>g.first).sort()[0];if(cutoff>=firstValidation)fail('보정 계측 완료와 검증 공정 시각이 겹칩니다. 과거에 알 수 없던 계측값의 사용을 막기 위해 기간을 분리하세요.');
    const trainRows=training.flatMap(g=>g.rows),points=training.map(g=>({x:mean(g.rows.map(r=>M.referenceResponse(dataset.profile,r.inputs))),y:mean(g.rows.map(r=>r.measured))})),mx=mean(points.map(p=>p.x)),my=mean(points.map(p=>p.y));
    let slope=1;if(config.method==='affine'){const variance=points.reduce((s,p)=>s+(p.x-mx)**2,0);if(variance<=1e-12*Math.max(1,mx*mx))fail('보정 LOT의 예측값 변화가 너무 작아 기울기를 추정할 수 없습니다. 오프셋 방식 또는 더 다양한 보정 조건이 필요합니다.');slope=points.reduce((s,p)=>s+(p.x-mx)*(p.y-my),0)/variance;}
    const intercept=my-slope*mx;if(!Number.isFinite(slope)||!Number.isFinite(intercept)||slope<=0)fail('양의 유한 응답을 갖는 보정식을 추정하지 못했습니다. 데이터와 모델 적합성을 검토하세요.');
    const domain=Object.fromEntries(Object.keys(profiles[dataset.profile].inputs).map(k=>[k,{min:Math.min(...trainRows.map(r=>r.inputs[k])),max:Math.max(...trainRows.map(r=>r.inputs[k]))}])),predictions=trainRows.map(r=>M.referenceResponse(dataset.profile,r.inputs));domain.reference={min:Math.min(...predictions),max:Math.max(...predictions)};
    return freeze({version:VERSION,dataset,config,fit:{slope,intercept,domain,cutoff,firstValidation,trainingLotIds:training.map(g=>g.lotId),validationLotIds:validation.map(g=>g.lotId),trainingRows:trainRows.length,validationRows:validation.reduce((n,g)=>n+g.rows.length,0),weighting:'one-vote-per-lot-mean'}});
  }
  function predict(plan,rawInputs){const p=inputs(plan.dataset.profile,rawInputs),reference=M.referenceResponse(plan.dataset.profile,p),value=plan.fit.slope*reference+plan.fit.intercept,outOfDomain=[];for(const[k,range]of Object.entries(plan.fit.domain)){const v=k==='reference'?reference:p[k],epsilon=1e-9*Math.max(1,Math.abs(range.min),Math.abs(range.max));if(v<range.min-epsilon||v>range.max+epsilon)outOfDomain.push(k);}return{reference,value,outOfDomain,usable:value>=0&&outOfDomain.length===0,scope:copy(plan.dataset.scope)};}
  const quantile=(values,q)=>{const a=[...values].sort((a,b)=>a-b),n=(a.length-1)*q,lo=Math.floor(n);return a[lo]+(a[Math.ceil(n)]-a[lo])*(n-lo);};
  function metrics(rows,key){if(!rows.length)return null;const errors=rows.map(r=>r[key]-r.measured),absolute=errors.map(Math.abs),lotMetrics=groupRows(rows).map(g=>mean(g.rows.map(r=>Math.abs(r[key]-r.measured))));return{n:rows.length,lots:lotMetrics.length,mae:mean(absolute),rmse:Math.sqrt(mean(errors.map(e=>e*e))),bias:mean(errors),p95:quantile(absolute,.95),maxError:Math.max(...absolute),lotMeanMae:mean(lotMetrics)};}
  function evaluate(plan,{priorEvaluations=0}={}){
    if(!Number.isInteger(priorEvaluations)||priorEvaluations<0)fail('검증 이력 수가 잘못되었습니다.');const rows=plan.dataset.observations.filter(r=>plan.fit.validationLotIds.includes(r.lotId)).map(r=>({...copy(r),...predict(plan,r.inputs)})),training=plan.dataset.observations.filter(r=>plan.fit.trainingLotIds.includes(r.lotId)).map(r=>({...copy(r),...predict(plan,r.inputs)}));
    const before=metrics(rows,'reference'),after=metrics(rows,'value'),outside=rows.filter(r=>r.outOfDomain.length),negative=rows.filter(r=>r.value<0),limits=plan.config.limits;
    const checks=[{id:'mae',label:'평균 절대 오차',actual:after.mae,limit:limits.mae,passed:after.mae<=limits.mae},{id:'bias',label:'절대 평균 편향',actual:Math.abs(after.bias),limit:limits.bias,passed:Math.abs(after.bias)<=limits.bias},{id:'maxError',label:'최대 절대 오차',actual:after.maxError,limit:limits.maxError,passed:after.maxError<=limits.maxError},{id:'domain',label:'보정 범위 밖 관측',actual:outside.length,limit:0,passed:outside.length===0},{id:'physical',label:'음수 보정 출력',actual:negative.length,limit:0,passed:negative.length===0}];
    return freeze({version:VERSION,provenance:plan.dataset.origin.kind,sourceVerified:false,manufacturingRelease:false,wholeFabValidated:false,priorEvaluations,exploratory:priorEvaluations>0,criteriaMet:checks.every(c=>c.passed),before,after,training:metrics(training,'value'),checks,rows,perLot:groupRows(rows).map(g=>({lotId:g.lotId,...metrics(g.rows,'value'),outside:g.rows.filter(r=>r.outOfDomain.length).length})),inDomain:metrics(rows.filter(r=>!r.outOfDomain.length),'value'),outOfDomainIds:outside.map(r=>r.id),limitations:['계측 불확도·양산 승인·전체 팹 검증은 포함하지 않음','축별 최소/최대 범위 검사는 다변량 적용 가능성의 충분조건이 아님','재사용 검증 데이터의 오차는 탐색 결과이며 새로운 독립 시험이 필요함']});
  }
  function demo(kind='har'){
    if(!profiles[kind])fail('지원하지 않는 예제입니다.');const p=profiles[kind],observations=[];
    const factors=[.78,1.18,.86,1.1,.94,1.04,.82,1.15,.96,1.02,.9,1.08,1,1.06,.98];
    for(let lot=0;lot<15;lot++)for(let w=0;w<2;w++){const input=Object.fromEntries(Object.entries(p.inputs).map(([k,f])=>[k,f.default]));if(kind==='har')input.power_w=1000*factors[lot];if(kind==='cvd')input.flow_sccm=100*factors[lot];if(kind==='cmp'){input.pressure_psi=2.1*factors[lot];input.time_s=50;}const reference=M.referenceResponse(kind,input),noise=(kind==='har'?6:kind==='cvd'?.6:.06)*Math.sin(lot*1.9+w*2.1),measured=reference*1.035+(kind==='har'?40:kind==='cvd'?4:.3)+noise,time=Date.UTC(2026,0,1+lot,1,w*10);observations.push({id:'DEMO-'+lot+'-'+w,lotId:'DEMO-L'+String(lot+1).padStart(2,'0'),waferId:'W'+(w+1),runId:'RUN-'+lot+'-'+w,processedAt:new Date(time).toISOString(),measuredAt:new Date(time+3600000).toISOString(),inputs:input,measured});}
    return normalize({schema:SCHEMA,modelVersion:M.RESPONSE_VERSION,datasetId:'SYNTHETIC-'+kind.toUpperCase(),profile:kind,scope:{product:'dram',referenceStepId:p.defaultStep,sourceStepId:'DEMO-'+p.defaultStep,equipmentId:'DEMO-'+kind.toUpperCase(),chamberId:'DEMO-CH01',recipeRevision:'DEMO-DOE-R1',metrologyId:'DEMO-MET01',metrologyMethod:'synthetic-generator'},origin:{kind:'synthetic',source:'앱이 만든 기능 시험 자료. 실제 공정·계측 이력 아님.'},units:{...Object.fromEntries(Object.entries(p.inputs).map(([k,f])=>[k,f.unit])),measured:p.unit},observations});
  }
  function template(kind='har'){const d=copy(demo(kind));d.datasetId='REPLACE-DATASET-ID';d.origin={kind:'user-measurement',source:'REPLACE-WITH-DATA-SOURCE'};for(const key of Object.keys(d.scope))if(!['product','referenceStepId'].includes(key))d.scope[key]='REPLACE-'+key;d.observations=[{id:'REPLACE-ID',lotId:'REPLACE-LOT',waferId:'REPLACE-WAFER',runId:'REPLACE-RUN',processedAt:'2026-01-01T00:00:00Z',measuredAt:'2026-01-01T01:00:00Z',inputs:Object.fromEntries(Object.entries(profiles[kind].inputs).map(([k])=>[k,null])),measured:null}];return d;}
  function canonical(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';}
  async function digest(value){if(!root.crypto?.subtle)fail('SHA-256에는 localhost 또는 HTTPS 환경이 필요합니다.');const bytes=new TextEncoder().encode(canonical(value)),hash=await root.crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');}
  root.EvidenceEngine=Object.freeze({VERSION,SCHEMA,profiles:freeze(profiles),normalize,configuration,prepare,predict,evaluate,demo,template,canonical,digest});
})(typeof window==='undefined'?globalThis:window);
