(function(root){
  'use strict';
  const E=root.EvidenceEngine,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(v,n=2)=>Number.isFinite(v)?Math.abs(v)>=1e6?v.toExponential(3):v.toLocaleString('en-US',{minimumFractionDigits:n,maximumFractionDigits:n}):'—';
  const copy=x=>JSON.parse(JSON.stringify(x)),LEDGER='waferflow-evidence-ledger-v1';
  let dataset=null,plan=null,result=null,datasetHash='',identityHash='',planHash='',sourceHash='',revision=0,dirty=false,busy=false,generation=0,bundlePreviouslyEvaluated=false,evaluatedAt=null,historyAvailable=true;
  const profile=()=>E.profiles[dataset?.profile||$('#profileSelect').value];
  function say(message,error=false){$('#evidenceFeedback').textContent=message;$('#evidenceFeedback').classList.toggle('error',error);}
  function setBusy(value){busy=value;$('#loadEvidence').disabled=value;$('#loadDemo').disabled=value;$('#freezePlan').disabled=value||!dataset;$('#evaluateButton').disabled=value||!plan||dirty||!!result;$('#downloadBundle').disabled=value||!plan;$('#downloadReport').disabled=value||!result;for(const id of ['profileSelect','fitMethod','trainFraction','limitMae','limitBias','limitMax'])$('#'+id).disabled=value;}
  function setConfig(config){$('#fitMethod').value=config.method;$('#trainFraction').value=String(config.trainFraction);$('#limitMae').value=String(config.limits.mae);$('#limitBias').value=String(config.limits.bias);$('#limitMax').value=String(config.limits.maxError);}
  function readConfig(){const numeric=id=>{const raw=$(id).value.trim();return raw===''?NaN:Number(raw);};return E.configuration({method:$('#fitMethod').value,trainFraction:Number($('#trainFraction').value),limits:{mae:numeric('#limitMae'),bias:numeric('#limitBias'),maxError:numeric('#limitMax')}});}
  function markDirty(){if(busy)return;if(plan){dirty=true;$('#planBadge').textContent='미적용 변경';$('#evaluationHint').textContent='초안을 바꿨습니다. 기존 결과는 고정한 계획의 결과입니다. 새 계획으로 다시 고정하세요.';}setBusy(false);}
  function renderDataset(){
    const p=profile(),lots=new Set(dataset.observations.map(r=>r.lotId)),s=dataset.scope;$('#sourceBadge').textContent=dataset.origin.kind==='synthetic'?'합성 예제':'출처 미인증';$('#sourceBadge').className='status '+(dataset.origin.kind==='synthetic'?'synthetic':'warning');
    $('#datasetInfo').innerHTML=`<strong>${esc(dataset.datasetId)}</strong><div class="data-stats"><div><b>${lots.size}</b><span>독립 LOT 식별자</span></div><div><b>${dataset.observations.length}</b><span>웨이퍼 관측</span></div></div><dl><dt>검토 응답</dt><dd>${p.name}</dd><dt>제품·공정</dt><dd>${esc(s.product+' / '+s.sourceStepId)}</dd><dt>장비·챔버</dt><dd>${esc(s.equipmentId+' / '+s.chamberId)}</dd><dt>레시피</dt><dd>${esc(s.recipeRevision)}</dd><dt>계측</dt><dd>${esc(s.metrologyId)}</dd><dt>집계 방법</dt><dd>${esc(s.metrologyMethod)}</dd><dt>출처 선언</dt><dd>${esc(dataset.origin.source)}</dd></dl><p class="fingerprint">정규화 데이터 SHA-256<br>${datasetHash}${sourceHash?'<br>입력 파일 SHA-256<br>'+sourceHash:''}</p>`;
    $('#stageData').classList.add('done');$('#stageFit').classList.remove('done');$('#stageValidation').classList.remove('done');
  }
  async function loadData(raw,{fileHash=''}={}){
    const token=++generation;setBusy(true);
    try{const bundle=raw?.schema==='waferflow-evidence-review-v1';if(bundle&&raw.version!==E.VERSION)throw Error('검토 패키지 버전이 다릅니다.');const next=E.normalize(bundle?raw.dataset:raw),config=bundle?E.configuration(raw.plan?.config):{method:'affine',trainFraction:.7,limits:E.profiles[next.profile].limits};
      const hash=await E.digest(next),identity=await E.digest({profile:next.profile,scope:next.scope,observations:next.observations});if(bundle){if(raw.hashes?.normalizedDataset!==hash)throw Error('패키지의 데이터 지문이 원본 자료와 일치하지 않습니다.');const check=E.prepare(next,config),expected=await E.digest({datasetHash:hash,config:check.config,fit:check.fit,responseVersion:next.modelVersion});if(raw.hashes?.plan!==expected)throw Error('패키지의 계획 지문이 재계산 결과와 다릅니다.');}if(token!==generation)return false;
      dataset=next;datasetHash=hash;identityHash=identity;sourceHash=fileHash;plan=null;result=null;planHash='';evaluatedAt=null;dirty=false;bundlePreviouslyEvaluated=bundle&&!!raw.result;$('#profileSelect').value=next.profile;setConfig(config);renderDataset();$('#fitSummary').innerHTML='<div class="evidence-empty"><span>02</span><h3>검토 계획을 먼저 고정하세요.</h3><p>단위·식별자·시각 검사를 통과했습니다. 보정 방식과 허용 오차는 결과를 보기 전에 정하세요.</p></div>';$('#fitVersion').textContent='고정 전';$('#planBadge').textContent='미고정';$('#resultBadge').textContent='미평가';$('#resultBadge').className='status';$('#resultsEmpty').hidden=false;$('#resultContent').hidden=true;$('#domainEmpty').hidden=false;$('#domainContent').hidden=true;$('#planError').textContent='';$('#evaluationHint').textContent='보정 데이터로 계수를 추정한 뒤, 후속 LOT을 별도로 평가합니다.';$('#evidenceState').textContent='실측 검증 미완료';say(bundle?'패키지의 원본 자료와 계획을 읽었습니다. 저장된 결과는 사용하지 않고 다시 계산합니다.':next.origin.kind==='synthetic'?'합성 예제를 불러왔습니다. 실제 공정 정확도의 근거가 될 수 없습니다.':'자료를 검사했습니다. 출처와 계측 신뢰성은 아직 인증되지 않았습니다.');return true;
    }catch(e){if(token===generation)say('자료 불러오기 실패: '+e.message,true);return false;}finally{if(token===generation)setBusy(false);}
  }
  function renderFit(){
    const f=plan.fit;$('#planBadge').textContent='계획 r'+revision+' 고정';$('#fitVersion').textContent=root.MemoryFab.RESPONSE_VERSION;$('#stageFit').classList.add('done');$('#stageValidation').classList.remove('done');
    $('#fitSummary').innerHTML=`<div class="fit-details"><div class="fit-equation">y = ${fmt(f.slope,5)} × x ${f.intercept<0?'−':'+'} ${fmt(Math.abs(f.intercept),3)}<small>x = 팹 모델의 결정론적 기준 응답 · y = 보정 참고값, nm</small></div><div class="fit-split"><div><b>보정 ${f.trainingLotIds.length} LOT / ${f.trainingRows} 관측</b>LOT 평균에 같은 가중치 적용<br><small>계측 완료 ≤ ${esc(f.cutoff)}</small></div><div><b>검증 ${f.validationLotIds.length} LOT / ${f.validationRows} 관측</b>기울기·오프셋 추정에서 제외<br><small>공정 완료 ≥ ${esc(f.firstValidation)}</small></div></div><div class="split-lots">${f.trainingLotIds.map(id=>'<span>'+esc(id)+'</span>').join('')}${f.validationLotIds.map(id=>'<span class="validation">'+esc(id)+'</span>').join('')}</div><p class="fit-footnote">청록 = 보정 / 황색 = 검증 · 고정 기준: MAE ≤ ${fmt(plan.config.limits.mae)}, |편향| ≤ ${fmt(plan.config.limits.bias)}, 최대 오차 ≤ ${fmt(plan.config.limits.maxError)} nm<br>입력 변수와 기준 응답의 보정 범위 밖 관측은 기준 충족에서 제외하지 않고 실패 항목으로 표시합니다.</p><p class="fingerprint">계획 SHA-256 ${planHash}</p></div>`;
    $('#resultsEmpty').hidden=false;$('#resultContent').hidden=true;$('#resultBadge').textContent='미평가';$('#resultBadge').className='status';$('#evaluationHint').textContent='계수와 기준을 고정했습니다. 후속 LOT의 오차를 확인하세요.';$('#domainEmpty').hidden=true;$('#domainContent').hidden=false;$('#scopeDescription').textContent=`${dataset.scope.product} / ${dataset.scope.sourceStepId} · ${dataset.scope.equipmentId} / ${dataset.scope.chamberId} · ${dataset.scope.recipeRevision}에 한정한 자료입니다.`;
    $('#domainRows').innerHTML=Object.entries(profile().inputs).map(([k,f])=>`<tr><td>${f.label}</td><td>${fmt(plan.fit.domain[k].min)}</td><td>${fmt(plan.fit.domain[k].max)}</td><td>${f.unit}</td></tr>`).join('');
    $('#predictionFields').innerHTML=Object.entries(profile().inputs).map(([k,f])=>`<label>${f.label}<small>${f.unit}</small><input data-predict="${k}" type="number" min="${f.min}" max="${f.max}" step="any" value="${(plan.fit.domain[k].min+plan.fit.domain[k].max)/2}" aria-label="${esc(f.label+' '+f.unit)}"></label>`).join('');$('#predictionResult').textContent='';
  }
  async function freezePlan(){if(!dataset||busy)return false;setBusy(true);const token=++generation;try{const config=readConfig(),next=E.prepare(dataset,config),hash=await E.digest({datasetHash,config:next.config,fit:next.fit,responseVersion:dataset.modelVersion});if(token!==generation)return false;plan=next;planHash=hash;result=null;revision++;dirty=false;evaluatedAt=null;$('#planError').textContent='';renderFit();say('보정 LOT만 사용해 계수를 고정했습니다. 이제 별도 LOT으로 검증할 수 있습니다.');return true;}catch(e){$('#planError').textContent=e.message;say('계획을 고정하지 못했습니다. '+e.message,true);return false;}finally{if(token===generation)setBusy(false);}}
  function readLedger(){try{const raw=JSON.parse(localStorage.getItem(LEDGER)||'{}');if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error();const out={};for(const[k,v]of Object.entries(raw)){if(!/^(data|lot):[a-f0-9]{64}$/.test(k)||!Number.isInteger(v?.count)||v.count<=0||v.count>=100000)throw Error();out[k]={count:v.count,at:typeof v.at==='string'?v.at:''};}historyAvailable=true;return out;}catch{historyAvailable=false;return{};}}
  async function ledgerKeys(){const grouped=new Map();dataset.observations.filter(r=>plan.fit.validationLotIds.includes(r.lotId)).forEach(r=>{if(!grouped.has(r.lotId))grouped.set(r.lotId,[]);grouped.get(r.lotId).push(r);});const lotHashes=await Promise.all([...grouped.values()].map(rows=>E.digest({profile:dataset.profile,scope:dataset.scope,observations:rows})));return ['data:'+identityHash,...lotHashes.map(hash=>'lot:'+hash)];}
  async function evaluate(){if(!plan||dirty||busy||result)return false;setBusy(true);const token=++generation;try{const keys=await ledgerKeys();if(token!==generation)return false;const ledger=readLedger(),prior=Math.max(bundlePreviouslyEvaluated?1:0,historyAvailable?0:1,...keys.map(k=>ledger[k]?.count||0));result=E.evaluate(plan,{priorEvaluations:prior});evaluatedAt=new Date().toISOString();keys.forEach(k=>ledger[k]={count:(ledger[k]?.count||0)+1,at:evaluatedAt});try{const entries=Object.entries(ledger).sort((a,b)=>a[1].at.localeCompare(b[1].at));localStorage.setItem(LEDGER,JSON.stringify(Object.fromEntries(entries.slice(-3000))));}catch{historyAvailable=false;}renderResults();say('후속 LOT의 오차를 계산했습니다. 데이터 출처와 적용 범위를 함께 확인하세요.');return true;}catch(e){say('검증 실패: '+e.message,true);return false;}finally{if(token===generation)setBusy(false);}}
  function sample(rows,max=200){return rows.length<=max?rows:Array.from({length:max},(_,i)=>rows[Math.round(i*(rows.length-1)/(max-1))]);}
  function plot(type){
    const rows=sample(result.rows),width=360,height=235,L=43,R=12,T=13,B=30,w=width-L-R,h=height-T-B;let xmin,xmax,ymin,ymax;
    if(type==='parity'){const values=rows.flatMap(r=>[r.measured,r.reference,r.value]);xmin=ymin=Math.min(...values);xmax=ymax=Math.max(...values);const pad=Math.max(1,(xmax-xmin)*.08);xmin-=pad;ymin-=pad;xmax+=pad;ymax+=pad;}else{xmin=0;xmax=Math.max(1,result.rows.length-1);const errors=rows.flatMap(r=>[r.value-r.measured,r.reference-r.measured]);const max=Math.max(1,...errors.map(Math.abs));ymin=-max*1.15;ymax=max*1.15;}
    const x=v=>L+(v-xmin)/(xmax-xmin)*w,y=v=>T+h-(v-ymin)/(ymax-ymin)*h;
    const grid=Array.from({length:5},(_,i)=>{const v=ymin+(ymax-ymin)*i/4,xx=xmin+(xmax-xmin)*i/4;return `<path d="M${L} ${y(v)}H${width-R}" stroke="#e8eff3"/><text x="${L-7}" y="${y(v)+3}" text-anchor="end" class="plot-label">${fmt(v,0)}</text><text x="${x(xx)}" y="${height-10}" text-anchor="middle" class="plot-label">${fmt(xx,0)}</text>`;}).join('');
    const guide=type==='parity'?`<path d="M${x(xmin)} ${y(xmin)}L${x(xmax)} ${y(xmax)}" stroke="#a7bbc4" stroke-dasharray="4 4"/>`:`<path d="M${L} ${y(0)}H${width-R}" stroke="#b6cbd2" stroke-dasharray="4 4"/>`;
    const dots=rows.map(r=>{const xx=type==='parity'?r.measured:result.rows.indexOf(r),yy=type==='parity'?r.value:r.value-r.measured,baseY=type==='parity'?r.reference:r.reference-r.measured;return `<circle cx="${x(xx)}" cy="${y(baseY)}" r="2.2" fill="#bbcad1"/><circle cx="${x(xx)}" cy="${y(yy)}" r="3" fill="${r.outOfDomain.length?'#c89148':'#258f8b'}" opacity=".85"><title>${esc(r.id)} · 예측 ${fmt(r.value)} / 계측 ${fmt(r.measured)} nm</title></circle>`;}).join('');
    return `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${type==='parity'?'계측값 대비 기준·보정 예측 산점도':'시간순 기준·보정 잔차'}"><title>회색: 기준 / 청록: 보정 / 황색: 범위 밖. ${rows.length}개 표시, 전체 ${result.rows.length}개.</title>${grid}${guide}${dots}</svg>`;
  }
  function renderResults(){
    $('#stageValidation').classList.add('done');$('#resultsEmpty').hidden=true;$('#resultContent').hidden=false;$('#resultBadge').textContent=result.criteriaMet?'수치 기준 충족':'검토 필요';$('#resultBadge').className='status '+(result.criteriaMet?'success':'warning');$('#evidenceState').textContent=dataset.origin.kind==='synthetic'?'합성 예제 · 실측 검증 미완료':'업로드 자료 평가 · 출처 미인증';
    const warnings=[dataset.origin.kind==='synthetic'?'합성 자료의 기능 시험 결과입니다. 실제 공정 검증의 근거로 사용할 수 없습니다.':'사용자 제공 자료의 수치 평가입니다. 원출처와 계측 정확도는 인증되지 않았습니다.',result.exploratory?'이 검증 자료가 이전 평가에 사용되었습니다. 탐색 결과로 취급하고 새 LOT으로 독립 확인하세요.':'이 브라우저 기록에서 해당 검증 LOT의 이전 평가는 발견되지 않았습니다. 독립성의 외부 증명은 아닙니다.',!historyAvailable?'검증 이력을 저장하거나 읽지 못했습니다. 반복 사용 여부를 별도로 관리하세요.':''];
    $('#resultNotice').textContent=warnings.filter(Boolean).join(' ');$('#evaluationHint').textContent='검증 완료 · 결과를 보고 계획을 바꿀 경우 검증 자료 재사용으로 기록됩니다.';
    const metrics=[['MAE','mae'],['RMSE','rmse'],['평균 편향','bias'],['최대 절대 오차','maxError']];$('#metricCards').innerHTML=metrics.map(([name,key])=>`<article><span>${name} · nm</span><b>${fmt(result.after[key])}</b><small>보정 전 ${fmt(result.before[key])}<br>${result.after.lots} LOT / ${result.after.n} 관측</small></article>`).join('');
    $('#parityPlot').innerHTML=plot('parity');$('#residualPlot').innerHTML=plot('residual');$('#criteriaChecks').innerHTML=result.checks.map(c=>`<span class="criterion ${c.passed?'':'failed'}">${c.passed?'✓':'!'} ${c.label} ${fmt(c.actual)} / ≤ ${fmt(c.limit)}</span>`).join('')+`<span class="criterion">절대 오차 P95 ${fmt(result.after.p95)} nm</span><span class="criterion">LOT 평균 MAE ${fmt(result.after.lotMeanMae)} nm</span>`;
    $('#lotResults').innerHTML=result.perLot.map(r=>`<tr><td>${esc(r.lotId)}</td><td>${r.n}</td><td>${fmt(r.mae)}</td><td>${fmt(r.bias)}</td><td>${fmt(r.maxError)}</td><td>${r.outside}</td></tr>`).join('');$('#observationRows').innerHTML=result.rows.slice(0,200).map(r=>`<tr><td>${esc(r.lotId+' / '+r.waferId)}</td><td>${esc(r.id)}</td><td>${fmt(r.measured)}</td><td>${fmt(r.reference)}</td><td>${fmt(r.value)}</td><td>${fmt(r.value-r.measured)}</td><td>${r.outOfDomain.length?'범위 밖':'범위 안'}</td></tr>`).join('');
  }
  function predict(){if(!plan)return false;try{const raw={};$$('[data-predict]').forEach(el=>raw[el.dataset.predict]=el.value.trim()===''?NaN:Number(el.value));const prediction=E.predict(plan,raw);$('#predictionResult').classList.toggle('error',!prediction.usable);$('#predictionResult').textContent=`기준 ${fmt(prediction.reference)} → 보정 ${fmt(prediction.value)} nm. `+(prediction.usable?'보정 데이터의 축별 범위 안에 있습니다. 장비·공정 범위와 별도 검증을 함께 확인하세요.':'보정 적용 범위를 벗어나거나 물리적으로 부적합한 출력입니다. 적용 근거 부족: '+prediction.outOfDomain.map(k=>profile().inputs[k]?.label||'기준 응답').join(' · '));return prediction;}catch(e){$('#predictionResult').textContent=e.message;$('#predictionResult').classList.add('error');return false;}}
  function bundle(){if(!plan)throw Error('먼저 계획을 고정하세요.');return{schema:'waferflow-evidence-review-v1',version:E.VERSION,dataset,hashes:{normalizedDataset:datasetHash,inputFile:sourceHash||null,plan:planHash},plan:{config:plan.config,fit:plan.fit,revision},result,evaluatedAt,historyAvailable,sourceVerified:false,manufacturingRelease:false};}
  function reportHTML(){if(!result)throw Error('먼저 검증을 실행하세요.');const b=bundle();return `<!doctype html><html lang="ko"><meta charset="utf-8"><title>WaferFlow 모델 근거 검토</title><style>body{font:13px/1.8 sans-serif;color:#234;max-width:1100px;margin:40px auto}h1{font-size:27px}table{border-collapse:collapse;width:100%;margin:18px 0}td,th{padding:8px;border-bottom:1px solid #ccd;text-align:left;font-size:11px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f2f6f8;padding:18px;font-size:10px}.note{padding:15px;background:#fff4df}svg{width:45%;max-height:330px}.plot-label{font:8px monospace;fill:#678}@media print{body{margin:20px}tr{break-inside:avoid}}</style><h1>공정 응답 모델 근거 검토</h1><p>${esc(profile().name)} / ${esc(dataset.datasetId)} / ${esc(evaluatedAt)}</p><p class="note">${esc($('#resultNotice').textContent)} 전체 팹·양산 투입 판정이 아닙니다.</p><h2>대상과 식별</h2><pre>${esc(JSON.stringify({scope:dataset.scope,origin:dataset.origin,hashes:b.hashes,responseVersion:dataset.modelVersion,evidenceVersion:E.VERSION},null,2))}</pre><h2>고정 계획과 데이터 분리</h2><pre>${esc(JSON.stringify(b.plan,null,2))}</pre><h2>검증 오차 · nm</h2><table><tr><th>지표</th><th>보정 전</th><th>보정 후</th></tr>${['mae','rmse','bias','p95','maxError','lotMeanMae'].map(k=>`<tr><td>${k}</td><td>${fmt(result.before[k])}</td><td>${fmt(result.after[k])}</td></tr>`).join('')}</table><p>${result.after.lots} LOT / ${result.after.n} 관측. 잔차 = 예측 − 계측. P95는 관측 절대 오차의 선형 보간 95백분위이며 신뢰구간이 아닙니다.</p>${plot('parity')}${plot('residual')}<h2>기준 확인</h2><pre>${esc(JSON.stringify(result.checks,null,2))}</pre><h2>LOT별 검증</h2><table><tr><th>LOT</th><th>관측</th><th>MAE</th><th>편향</th><th>최대 오차</th><th>범위 밖</th></tr>${result.perLot.map(r=>`<tr><td>${esc(r.lotId)}</td><td>${r.n}</td><td>${fmt(r.mae)}</td><td>${fmt(r.bias)}</td><td>${fmt(r.maxError)}</td><td>${r.outside}</td></tr>`).join('')}</table><h2>관측별 검증</h2><table><tr><th>관측 ID</th><th>LOT / wafer</th><th>계측</th><th>기준</th><th>보정</th><th>범위 밖</th></tr>${result.rows.map(r=>`<tr><td>${esc(r.id)}</td><td>${esc(r.lotId+' / '+r.waferId)}</td><td>${fmt(r.measured)}</td><td>${fmt(r.reference)}</td><td>${fmt(r.value)}</td><td>${esc(r.outOfDomain.join(', '))}</td></tr>`).join('')}</table><h2>해석 범위</h2><p>허용 오차와 최소 LOT 수는 사용자/예제 규칙입니다. 출처와 계측 불확도는 미검증입니다. 보정식은 해당 장비·챔버·레시피·공정 자료 범위에 한정합니다. 축별 범위 내라는 사실만으로 일반화 성능을 보장하지 않습니다. 같은 검증 세트의 반복 사용은 탐색 결과입니다. 로컬 해시는 내용 식별용이며 전자서명·서버 감사 기록이 아닙니다.</p><p><a href="https://www.itl.nist.gov/div898/handbook/pri/section6/pri619.htm">NIST 잔차 검토</a> · <a href="https://scikit-learn.org/stable/modules/cross_validation.html">그룹·시간순 검증 원리</a></p><p>원본 입력과 재현 계획은 함께 내려받은 JSON 검토 패키지에 포함됩니다.</p></html>`;}
  function download(name,contents,type){const url=URL.createObjectURL(new Blob([contents],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
  $('#loadDemo').addEventListener('click',()=>loadData(E.demo($('#profileSelect').value)));$('#loadEvidence').addEventListener('click',()=>$('#evidenceFile').click());$('#downloadTemplate').addEventListener('click',()=>download('waferflow-evidence-template-'+$('#profileSelect').value+'.json',JSON.stringify(E.template($('#profileSelect').value),null,2),'application/json'));
  $('#profileSelect').addEventListener('change',()=>{if(!dataset)setConfig({method:'affine',trainFraction:.7,limits:E.profiles[$('#profileSelect').value].limits});else say('양식·합성 예제용 모델을 변경했습니다. 기존 자료는 새 파일이나 예제를 불러올 때 바뀝니다.');});
  $('#evidenceFile').addEventListener('change',async()=>{const file=$('#evidenceFile').files?.[0];if(!file)return;try{if(file.size>4*1024*1024)throw Error('파일은 4 MB 이하여야 합니다.');const bytes=await file.arrayBuffer(),hash=await root.crypto.subtle.digest('SHA-256',bytes),raw=JSON.parse(new TextDecoder().decode(bytes));await loadData(raw,{fileHash:Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('')});}catch(e){say('자료 불러오기 실패: '+e.message,true);}finally{$('#evidenceFile').value='';}});
  $('#validationPlan').addEventListener('submit',e=>{e.preventDefault();freezePlan();});for(const id of ['fitMethod','trainFraction','limitMae','limitBias','limitMax'])$('#'+id).addEventListener('input',markDirty);$('#evaluateButton').addEventListener('click',evaluate);$('#predictForm').addEventListener('submit',e=>{e.preventDefault();predict();});$('#downloadBundle').addEventListener('click',()=>download('waferflow-evidence-review.json',JSON.stringify(bundle(),null,2),'application/json'));$('#downloadReport').addEventListener('click',()=>download('waferflow-evidence-review.html',reportHTML(),'text/html;charset=utf-8'));
  $('#evidenceVersion').textContent=E.VERSION+' / '+root.MemoryFab.RESPONSE_VERSION;$('#downloadBundle').title='공정 조건과 계측 원본이 포함된 로컬 JSON입니다.';
  try{const requested=new URLSearchParams(root.location?.search||'').get('profile');if(Object.hasOwn(E.profiles,requested))$('#profileSelect').value=requested;}catch{}setConfig({method:'affine',trainFraction:.7,limits:profile().limits});
  root.EvidenceApp=Object.freeze({loadData,freezePlan,evaluate,predict,bundle,reportHTML,snapshot:()=>copy({dataset,plan,result,datasetHash,planHash,revision,dirty,busy,historyAvailable})});
})(window);
