/* Original procedural equipment geometries. Functional parts are simplified for observation. */
(function(root){
  'use strict';
  const T=root.THREE,E=root.FabEngine;
  const smooth=x=>{x=Math.max(0,Math.min(1,x));return Math.max(0,Math.min(1,x*x*x*(x*(x*6-15)+10)));};
  // Shared phase curves keep loading, conditioning, processing and unloading continuous.
  function motion(phase,progress){
    const p=Math.max(0,Math.min(1,progress||0));
    const transfer=phase==='load'?p:phase==='unload'?1-Math.max(0,(p-.22)/.78):phase==='idle'?0:1;
    const travel=smooth((transfer-.18)/.64),rise=smooth(transfer/.18),lower=smooth((transfer-.82)/.18);
    const processing=phase==='process'?smooth(p/.12)*(1-smooth((p-.85)/.15)):0;
    const closed=phase==='condition'?smooth(p):phase==='process'?1:phase==='unload'?1-smooth(p/.22):0;
    const nozzle=phase==='condition'?smooth((p-.35)/.65):phase==='process'?1-smooth((p-.62)/.2):0;
    return {transfer,travel,rise,lower,processing,closed,nozzle,orientation:smooth((transfer-.45)/.4)};
  }
  function stageMotion(progress){
    const p=Math.max(0,Math.min(1,progress||0)),sites=[[-.22,-.16],[.22,-.16],[.22,.16],[-.22,.16]];
    if(p>=.9){const t=1-smooth((p-.9)/.1);return {x:sites[3][0]*t,z:sites[3][1]*t,contact:0};}
    const index=Math.min(3,Math.floor(p/.225)),local=(p-index*.225)/.225,from=index?sites[index-1]:[0,0],to=sites[index],travel=smooth(local/.32);
    return {x:from[0]+(to[0]-from[0])*travel,z:from[1]+(to[1]-from[1])*travel,contact:smooth((local-.38)/.12)*(1-smooth((local-.85)/.12))};
  }
  function mount(host,{onInspect=()=>{},onContextLoss=()=>{}}={}){
    let renderer;try{if(!T)throw Error('WebGL unavailable');renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch{host.innerHTML='<div class="webgl-fallback">3D 장비 표시에는 WebGL이 필요합니다.<br>공정 계산·단면·기록은 계속 사용할 수 있습니다.</div>';return {select(){},update(){},camera(){},cutaway(){},parts:()=>[]};}
    renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));renderer.setClearColor(0x111f29);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;host.prepend(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','공정별 3D 장비. 클릭 또는 Enter로 장비 설명, 드래그로 회전, 휠로 확대.');renderer.domElement.setAttribute('aria-haspopup','dialog');renderer.domElement.setAttribute('aria-controls','equipmentDialog');
    let disposed=false,contextLost=false;const listeners=[],recovery=document.createElement('div');recovery.className='webgl-recovery';recovery.setAttribute('role','status');recovery.textContent='3D 연결을 복구하고 있습니다. 완료 기록과 단면 계산은 유지됩니다.';
    function listen(type,handler,options){renderer.domElement.addEventListener(type,handler,options);listeners.push(()=>renderer.domElement.removeEventListener(type,handler,options));}
    listen('webglcontextlost',event=>{event.preventDefault();contextLost=true;host.append(recovery);onContextLoss();});
    listen('webglcontextrestored',()=>{contextLost=false;recovery.remove();});
    const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,100),target=new T.Vector3(0,2,0),desiredTarget=target.clone();
    scene.fog=new T.Fog(0x111f29,24,55);if(root.WaferHardware?.environment){scene.environment=root.WaferHardware.environment(T);scene.environmentIntensity=.8;}
    scene.add(new T.HemisphereLight(0xe5f3ff,0x3b4848,1.1));const key=new T.DirectionalLight(0xffeedf,2.9);key.position.set(-5,11,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-7,right:7,top:7,bottom:-7});key.shadow.normalBias=.02;scene.add(key);const fill=new T.DirectionalLight(0x9bceff,1.2);fill.position.set(6,7,-7);scene.add(fill);
    const mat={white:new T.MeshPhysicalMaterial({color:0xc9d6d9,metalness:.35,roughness:.29,clearcoat:.3}),steel:new T.MeshStandardMaterial({color:0xaebfc9,metalness:.93,roughness:.22}),dark:new T.MeshStandardMaterial({color:0x253e4d,metalness:.6,roughness:.32}),black:new T.MeshStandardMaterial({color:0x102129,roughness:.5,metalness:.3}),green:new T.MeshStandardMaterial({color:0xa9c794,roughness:.35,metalness:.35}),ceramic:new T.MeshPhysicalMaterial({color:0xe5e1d7,roughness:.24,clearcoat:.25}),glass:new T.MeshPhysicalMaterial({color:0x86b5c9,transparent:true,opacity:.15,depthWrite:false,roughness:.12,side:T.DoubleSide}),amber:new T.MeshBasicMaterial({color:0xe8a25b,transparent:true,opacity:.12,depthWrite:false}),purple:new T.MeshBasicMaterial({color:0xb88bff,transparent:true,opacity:.22,depthWrite:false,blending:T.AdditiveBlending}),cyan:new T.MeshBasicMaterial({color:0x81dae7,transparent:true,opacity:.35,depthWrite:false,blending:T.AdditiveBlending})};
    const boxGeo=root.WaferHardware?.roundedGeometry(T)||new T.BoxGeometry(1,1,1),plainBox=new T.BoxGeometry(1,1,1);
    function mesh(parent,geometry,material,x=0,y=0,z=0){const m=new T.Mesh(geometry,material);m.position.set(x,y,z);m.castShadow=!material.transparent;m.receiveShadow=true;parent.add(m);return m;}
    function box(g,x,y,z,w,h,d,m=mat.white){const s=mesh(g,Math.min(w,h,d)>.13?boxGeo:plainBox,m,x,y,z);s.scale.set(w,h,d);return s;}
    function cyl(g,x,y,z,r,h,m=mat.steel){return mesh(g,new T.CylinderGeometry(r,r,h,48),m,x,y,z);}
    function ring(g,x,y,z,r,t=.025,m=mat.steel){const o=mesh(g,new T.TorusGeometry(r,t,8,64),m,x,y,z);o.rotation.x=Math.PI/2;return o;}
    function pipe(g,points,r=.035,m=mat.steel){const curve=new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p)));return mesh(g,new T.TubeGeometry(curve,40,r,8,false),m);}
    function bolts(g,r,y,count=12){for(let i=0;i<count;i++){const a=i/count*Math.PI*2;const b=cyl(g,Math.cos(a)*r,y,Math.sin(a)*r,.035,.035);}}
    function decal(g,title,subtitle,x,y,z,w=1.8){const c=document.createElement('canvas');c.width=512;c.height=144;const ctx=c.getContext('2d');ctx.fillStyle='#17313e';ctx.fillRect(0,0,512,144);ctx.fillStyle='#a8d8bc';ctx.fillRect(20,23,5,95);ctx.fillStyle='#dbe8ec';ctx.font='bold 31px sans-serif';ctx.fillText(title,42,62);ctx.font='17px monospace';ctx.fillStyle='#96b6c3';ctx.fillText(subtitle,43,101);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const o=mesh(g,new T.PlaneGeometry(w,w*144/512),new T.MeshBasicMaterial({map:tex}),x,y,z);o.castShadow=false;return o;}
    const floor=box(scene,0,-.18,0,24,.2,20,new T.MeshStandardMaterial({color:0x243d49,metalness:.22,roughness:.64}));
    const grid=new T.GridHelper(24,48,0x426574,0x2c4654);grid.position.y=-.072;grid.material.transparent=true;grid.material.opacity=.3;scene.add(grid);
    let equipment=new T.Group();scene.add(equipment);let shell=[],effects=[],parts=[],animated={},currentStep=null,frameState=null,cut=true,activePoint=new T.Vector3(0,1.74,0),waferOrientation=new T.Euler(),clock=0;
    function cabinet(g,w=3.6,h=1.4,d=2.6){box(g,0,h/2,0,w,h,d);box(g,0,h+.04,0,w+.08,.1,d+.08,mat.steel);for(const x of [-w*.25,w*.25]){box(g,x,h*.49,d/2+.013,w*.44,h*.83,.025,mat.white);box(g,x+.1,h*.57,d/2+.038,.036,.29,.028,mat.dark);for(let i=0;i<5;i++)box(g,x,h*.2+i*.06,d/2+.04,w*.3,.023,.014,mat.dark);}for(const x of [-w*.4,w*.4])for(const z of [-d*.38,d*.38])cyl(g,x,.02,z,.12,.1,mat.black);}
    function cover(g,x,y,z,w,h,d){const m=mat.white.clone();m.transparent=true;m.opacity=cut?.07:1;m.depthWrite=!cut;const o=box(g,x,y,z,w,h,d,m);o.castShadow=!cut;shell.push(o);return o;}
    function effect(g,shape,m,x,y,z){const o=mesh(g,shape,m.clone(),x,y,z);o.castShadow=false;effects.push(o);return o;}
    function foup(g,x=-3.2,z=.7){const f=new T.Group();f.position.set(x,0,z);g.add(f);cabinet(f,1.65,1.1,1.75);box(f,0,1.14,0,1.5,.1,1.6,mat.steel);for(const side of [-1,1])box(f,side*.7,1.91,0,.035,1.43,1.48,mat.glass);box(f,0,2.64,0,1.42,.06,1.48,mat.glass);for(let i=0;i<9;i++)cyl(f,0,1.35+i*.12,0,.55,.015,mat.dark);decal(f,'LOAD PORT','FOUP / TRANSFER',0,.8,.89,1.35);}
    function chamber(g,mode){cabinet(g);cyl(g,0,1.53,0,1.14,.15,mat.dark);cyl(g,0,1.7,0,.85,.14,mat.steel);ring(g,0,1.6,0,1.17,.045);bolts(g,1.08,1.65,16);cyl(g,0,2.98,0,1.12,.18);ring(g,0,2.86,0,1.08,.045);bolts(g,1.02,3.09,16);const wall=mesh(g,new T.CylinderGeometry(1.08,1.08,1.14,64,1,true),mat.glass,0,2.25,0);shell.push(wall);cyl(g,0,2.77,0,.89,.08,mode==='pvd'?mat.ceramic:mat.dark);for(let i=0;i<6;i++)ring(g,0,2.718,0,.14+i*.13,.006,mat.steel);pipe(g,[[0,3.15,0],[0,3.36,-.6],[1.35,3.36,-.83],[1.35,1.5,-.83]],.05);pipe(g,[[.94,1.85,0],[1.5,1.85,0],[1.65,1.45,-.7]],.11);box(g,1.65,1.6,-.73,.4,.44,.48,mat.dark);const glow=effect(g,new T.SphereGeometry(.85,32,16),mode==='pvd'?mat.cyan:mat.purple,0,2.27,0);glow.scale.y=.44;animated.plasma=glow;const dots=new T.Group();g.add(dots);for(let i=0;i<45;i++){const a=i*2.399,r=Math.sqrt((i+.5)/45)*.77;const dot=mesh(dots,new T.SphereGeometry(.012,5,4),mode==='pvd'?mat.green:mat.cyan,Math.cos(a)*r,2.4,Math.sin(a)*r);dot.userData.phase=i/45;dot.castShadow=false;}animated.particles=dots;activePoint.set(0,1.8,0);parts=[['상부 전극 / 타깃',[0,2.86,0]],['정전 척',[0,1.66,0]],['진공 배기 라인',[1.45,1.8,-.3]]];}
    function build(step){
      if(currentStep?.tool===step.tool){currentStep=step;paintKey='';return;}
      const geometries=new Set(),ownedMats=new Set();equipment.traverse(o=>{if(o.geometry&&o.geometry!==boxGeo&&o.geometry!==plainBox)geometries.add(o.geometry);if(o.material&&!Object.values(mat).includes(o.material))ownedMats.add(o.material);});scene.remove(equipment);geometries.forEach(g=>g.dispose());ownedMats.forEach(m=>{m.map?.dispose();m.dispose();});equipment=new T.Group();scene.add(equipment);shell=[];effects=[];parts=[];animated={};waferOrientation.set(0,0,0);activePoint.set(0,1.8,0);const g=equipment,family=E.tools[step.tool].family;
      if(family==='furnace'){
        cabinet(g,3.2,1.1,2.6);cover(g,-1.4,3.1,0,.2,3.9,2.6);cover(g,1.4,3.1,0,.2,3.9,2.6);box(g,0,5.1,0,3.1,.22,2.6);cyl(g,0,3.1,0,1.12,3.72,mat.glass);for(let i=0;i<22;i++)ring(g,0,1.4+i*.158,0,1.15,.026,i%5===0?mat.green:mat.steel);cyl(g,0,1.2,0,1.19,.16);cyl(g,0,5,0,1.2,.17);const boat=new T.Group();g.add(boat);for(const x of [-.78,.78])box(boat,x,2.7,0,.055,2.5,.06,mat.ceramic);for(let i=0;i<12;i++)cyl(boat,0,1.63+i*.17,0,.69,.02,mat.dark);animated.boat=boat;activePoint.set(0,3.65,0);const glow=effect(g,new T.CylinderGeometry(1.06,1.06,3.5,48,1,true),mat.amber,0,3.15,0);animated.heat=glow;pipe(g,[[-1.12,4.88,-.4],[-1.6,4.85,-.7],[-1.65,1.2,-.8]],.05);parts=[['석영 반응관',[0,4.2,0]],['웨이퍼 보트',[0,2.7,0]],['다중 가열 존',[1.1,3.2,0]]];
      }else if(family==='spin'){
        cabinet(g,3.5,1.45,2.8);cyl(g,0,1.6,0,1.12,.2,mat.dark);mesh(g,new T.CylinderGeometry(1.17,.83,.37,64,1,true),mat.ceramic,0,1.76,0);for(const r of [1.04,1.13,1.22])ring(g,0,1.94,0,r,.028);cyl(g,0,1.78,0,.47,.13,mat.dark);const nozzle=new T.Group();nozzle.position.set(.98,0,-.64);g.add(nozzle);pipe(nozzle,[[0,1.5,0],[0,2.7,0],[-.98,2.7,.64]],.05);cyl(nozzle,-.98,2.58,.64,.06,.2,mat.ceramic);animated.nozzle=nozzle;animated.stream=effect(g,new T.CylinderGeometry(.018,.018,.58,10),step.tool==='coat'?new T.MeshBasicMaterial({color:0xdb91b4,transparent:true,opacity:.8}):mat.cyan,0,2.17,0);for(const x of [-1.62,1.62])box(g,x,2.28,-1.28,.06,1.65,.06,mat.steel);cover(g,0,3.1,0,3.45,.08,2.7);box(g,0,2.3,-1.33,3.4,1.6,.06,mat.dark);pipe(g,[[1,1.6,.6],[1.42,1.4,.9],[1.42,.7,1]],.065,mat.dark);activePoint.set(0,1.88,0);parts=[['처리액 디스펜스 노즐',[0,2.5,0]],['진공 스핀 척',[0,1.78,0]],['스플래시 컵 / 배액',[1,1.8,.7]]];
      }else if(family==='scanner'){
        cabinet(g,4.4,1.45,3.3);for(const x of [-1.65,1.65])box(g,x,2.6,-.65,.3,2.25,.35);box(g,0,3.73,-.5,3.65,.3,.85);cyl(g,0,3.37,0,.56,.8,mat.white);for(let i=0;i<6;i++)ring(g,0,3.03+i*.12,0,.58,.035);cyl(g,0,2.83,0,.35,.2,mat.dark);box(g,0,4.4,0,1.65,.05,1.65,mat.glass);for(const x of [-.9,.9])box(g,x,4.4,0,.12,.13,1.9,mat.steel);for(const z of [-.9,.9])box(g,0,4.4,z,1.75,.13,.12,mat.steel);for(let i=0;i<8;i++)box(g,-.7+i*.2,4.436,0,.07,.006,1.4,mat.dark);const stage=new T.Group();g.add(stage);box(stage,0,1.65,0,2.2,.15,1.9,mat.dark);cyl(stage,0,1.78,0,.84,.12);animated.stage=stage;for(const z of [-1,1])box(g,0,1.57,z,3.1,.1,.12,mat.steel);animated.beam=effect(g,new T.CylinderGeometry(.34,.83,.9,48,1,true),mat.purple,0,2.27,0);activePoint.set(0,1.87,0);parts=[['투영 광학계',[0,3.25,0]],['레티클 / 포토마스크',[.5,4.4,.4]],['정렬 웨이퍼 스테이지',[0,1.7,.8]]];
      }else if(['etch','pvd','cluster'].includes(family)){
        chamber(g,family==='pvd'?'pvd':'etch');if(step.tool==='ald'){animated.plasma.material.color.set(0x88c5bc);animated.plasma.material.opacity=.045;}if(family==='cluster'){for(const x of [-2.05,2.05]){const aux=new T.Group();aux.position.set(x,0,-.8);g.add(aux);cyl(aux,0,.8,0,.77,1.5,mat.dark);cyl(aux,0,1.75,0,.76,.36);ring(aux,0,1.95,0,.73,.045);pipe(g,[[x*.62,1.75,-.35],[x,1.75,-.8]],.22,mat.steel);}parts[0]=['가스 분배판 / 반응 구역',[0,2.75,0]];}
      }else if(family==='implant'){
        cabinet(g,5.6,1.35,2.55);box(g,-2.05,2.4,0,.9,1.45,1.1,mat.dark);cyl(g,-2.05,3.2,0,.2,.3,mat.ceramic);pipe(g,[[-1.6,2.35,0],[-.8,2.35,0],[0,2.35,-.65],[.8,2.35,-.65],[1.5,2.35,0]],.22);for(const x of [-1.35,-.85]){const ringObj=ring(g,x,2.35,0,.3,.045);ringObj.rotation.z=Math.PI/2;}box(g,.05,2.35,-.65,.9,.9,.9,mat.green);const chamberMesh=cyl(g,1.62,2.35,0,.97,.65,mat.glass);chamberMesh.rotation.z=Math.PI/2;const back=cyl(g,2.02,2.35,0,.97,.13);back.rotation.z=Math.PI/2;const front=ring(g,1.25,2.35,0,1,.055);front.rotation.z=Math.PI/2;animated.beam=effect(g,new T.TubeGeometry(new T.CatmullRomCurve3([[-1.65,2.35,0],[-.8,2.35,0],[0,2.35,-.65],[.8,2.35,-.65],[1.5,2.35,0]].map(p=>new T.Vector3(...p))),48,.055,8,false),mat.cyan,0,0,0);activePoint.set(1.6,2.35,0);waferOrientation.z=-Math.PI/2;parts=[['이온 소스',[-2,2.65,0]],['질량 분석 자석',[0,2.4,-.65]],['틸트 / 스캔 엔드스테이션',[1.6,2.35,0]]];
      }else if(family==='cmp'){
        cabinet(g,4.5,1.2,3.3);const platen=new T.Group();g.add(platen);animated.platen=platen;cyl(platen,0,1.32,0,1.48,.15,mat.dark);cyl(platen,0,1.414,0,1.42,.028,mat.ceramic);for(let r=.15;r<1.4;r+=.12)ring(platen,0,1.435,0,r,.004,mat.dark);for(let i=0;i<12;i++){const a=i*Math.PI/6,line=box(platen,Math.cos(a)*.77,1.435,Math.sin(a)*.77,1.22,.003,.008,mat.dark);line.rotation.y=-a;}box(g,1.56,2.13,-.72,.23,1.7,.25);box(g,.75,2.91,-.5,1.9,.18,.22,mat.steel);const head=cyl(g,.35,1.95,.1,.82,.83,mat.glass);shell.push(head);animated.head=head;cyl(g,.35,2.59,.1,.13,.5,mat.steel);ring(g,.35,1.53,.1,.83,.05,mat.steel);pipe(g,[[-1.65,1.26,-.4],[-1.65,2.25,-.4],[-.55,2.25,-.15]],.04);animated.stream=effect(g,new T.CylinderGeometry(.017,.017,.75,10),mat.cyan,-.55,1.85,-.15);activePoint.set(.35,1.465,.1);waferOrientation.x=Math.PI;parts=[['회전 플래튼 / 연마 패드',[0,1.4,.9]],['캐리어 헤드',[.35,2,.1]],['슬러리 노즐',[-.55,2.25,-.15]]];
      }else if(family==='hotplate'||family==='rtp'){
        cabinet(g,3.35,1.45,2.6);cyl(g,0,1.61,0,1,.18,mat.dark);cyl(g,0,1.77,0,.88,.12,mat.ceramic);const lid=new T.Group();lid.position.y=2.75;g.add(lid);cyl(lid,0,0,0,1.04,.15);cyl(lid,0,.17,0,.16,.25,mat.dark);pipe(g,[[0,1.5,-1.08],[0,3.3,-1.08],[0,3.3,0]],.055);animated.lid=lid;if(family==='rtp'){for(let i=-3;i<=3;i++){const lamp=effect(g,new T.CylinderGeometry(.04,.04,1.65,12),mat.amber,i*.23,2.44,0);lamp.rotation.x=Math.PI/2;}parts=[['램프 가열 배열',[0,2.45,0]],['석영 윈도',[0,2.15,0]],['온도 계측 위치',[.92,1.8,.1]]];}else parts=[['히팅 플레이트',[0,1.78,0]],['이송 / 리프트 커버',[0,2.75,0]],['온도 제어부',[.85,1.7,.4]]];activePoint.set(0,1.86,0);
      }else if(family==='wet'){
        cabinet(g,4.1,1.3,2.8);for(const x of [-.93,.93]){box(g,x,1.4,0,1.65,.14,2.1,mat.ceramic);for(const sx of [-1,1])box(g,x+sx*.78,2.12,0,.06,1.4,2.05,mat.glass);for(const z of [-1,1])box(g,x,2.12,z,1.57,1.4,.055,mat.glass);box(g,x,1.98,0,1.49,1.15,1.94,new T.MeshPhysicalMaterial({color:0x66b7c3,transparent:true,opacity:.16,depthWrite:false,roughness:.15}));}box(g,0,3.3,-1.12,3.85,.12,.13,mat.steel);for(const x of [-1.8,1.8])box(g,x,2.4,-1.12,.12,1.95,.13);pipe(g,[[-.93,3.26,-1.1],[-.93,3.26,0],[-.93,2.75,0]],.045);animated.stream=effect(g,new T.CylinderGeometry(.03,.03,.6,12),mat.cyan,-.93,2.5,0);activePoint.set(-.93,2.1,0);waferOrientation.x=Math.PI/2;parts=[['처리조 / 석영 배스',[-.93,2.15,.7]],['DI 린스 / 건조',[.93,2.15,.7]],['로봇 리프트',[-.93,3.3,0]]];
      }else{
        cabinet(g,3.55,1.45,2.75);const inspectStage=new T.Group();g.add(inspectStage);animated.stage=inspectStage;box(inspectStage,0,1.59,0,2.5,.15,2.15,mat.dark);cyl(inspectStage,0,1.78,0,.86,.16,mat.steel);box(g,0,2.9,-.93,.28,2.8,.3,mat.white);box(g,0,4.22,-.4,2.3,.24,1.05);const optic=cyl(g,0,3.62,0,.4,.85,mat.dark);cyl(g,0,3.12,0,.24,.16,mat.ceramic);animated.beam=effect(g,new T.CylinderGeometry(.017,.035,1.21,16),mat.cyan,0,2.5,0);if(family==='probe'){const probeAssembly=new T.Group();g.add(probeAssembly);animated.probes=probeAssembly;for(const x of [-.45,.45])for(const z of [-.3,.3])pipe(probeAssembly,[[x*2,2.8,z*2],[x,2.15,z],[x*.7,1.87,z*.7]],.018,mat.steel);ring(probeAssembly,0,2.8,0,.95,.05,mat.steel);}activePoint.set(0,1.89,0);parts=[[family==='probe'?'프로브 카드':'광학 계측 헤드',[0,3.2,0]],['웨이퍼 스테이지',[0,1.8,0]],['XY 정렬 레일',[.9,1.55,.6]]];
      }
      foup(g,family==='implant'?-4.15:-3.1,1.1);decal(g,step.tool.toUpperCase(),E.tools[step.tool].english.slice(0,30),0,.84,(family==='scanner'?1.67:family==='cmp'?1.68:1.43),2.3);cyl(g,1.45,3.5,-.97,.055,.22,mat.dark);cyl(g,1.45,3.66,-.97,.06,.12,new T.MeshStandardMaterial({color:0xaacd89,emissive:0x75a65c,emissiveIntensity:.65}));
      currentStep=step;setCamera('equipment');paintKey='';host.classList.remove('equipment-ready');requestAnimationFrame(()=>host.classList.add('equipment-ready'));
    }
    const transfer=new T.Group();scene.add(transfer);transfer.visible=false;const transferBase=cyl(transfer,-2.1,.6,1.5,.24,1.2,mat.dark),linkA=box(transfer,0,0,0,2.3,.09,.14,mat.steel),linkB=box(transfer,0,0,0,2.3,.075,.12,mat.ceramic),jointA=cyl(transfer,0,0,0,.13,.1,mat.steel),jointB=cyl(transfer,0,0,0,.11,.1,mat.steel),blade=box(transfer,0,0,0,.64,.04,.3,mat.ceramic);
    function poseTransfer(point,visible){transfer.visible=visible;if(!visible)return;const bx=-2.1,bz=1.5,dx=point.x-bx,dz=point.z-bz,len=2.3,d=Math.min(4.599,Math.hypot(dx,dz)),angle=Math.atan2(dz,dx)-Math.acos(d/(2*len)),ex=bx+len*Math.cos(angle),ez=bz+len*Math.sin(angle),a2=Math.atan2(point.z-ez,point.x-ex),h=point.y-.12;transferBase.scale.y=Math.max(.2,h/1.2);transferBase.position.y=h/2;linkA.position.set((bx+ex)/2,h,(bz+ez)/2);linkA.rotation.y=-angle;linkB.position.set((ex+point.x)/2,h+.04,(ez+point.z)/2);linkB.rotation.y=-a2;jointA.position.set(bx,h,bz);jointB.position.set(ex,h+.04,ez);blade.position.set(point.x,point.y-.05,point.z);}
    const wafer=new T.Group();scene.add(wafer);const silicon=new T.MeshPhysicalMaterial({color:0x5c7591,metalness:.9,roughness:.2,iridescence:.85,clearcoat:1});cyl(wafer,0,0,0,.75,.03,silicon);const waferCanvas=document.createElement('canvas');waferCanvas.width=768;waferCanvas.height=768;const waferTexture=new T.CanvasTexture(waferCanvas);waferTexture.colorSpace=T.SRGBColorSpace;const surface=mesh(wafer,new T.CircleGeometry(.749,96),new T.MeshStandardMaterial({map:waferTexture,metalness:.7,roughness:.28,side:T.DoubleSide}),0,.016,0);surface.rotation.x=-Math.PI/2;let paintKey='';
    function paint(w){const samples=Array.from({length:16},(_,i)=>{const column=Math.floor(i/16*E.NX);return topColor(w.columns[column],w.latent?.[column]||0);});const signature=w.cursor+'-'+w.mask+'-'+samples.join('');if(signature===paintKey)return;paintKey=signature;const ctx=waferCanvas.getContext('2d');const grad=ctx.createLinearGradient(0,0,768,768);grad.addColorStop(0,'#405872');grad.addColorStop(.45,'#a4b7c5');grad.addColorStop(1,'#384f78');ctx.fillStyle=grad;ctx.fillRect(0,0,768,768);for(let y=0;y<768;y+=96)for(let x=0;x<768;x+=96){for(let i=0;i<16;i++){ctx.fillStyle=samples[i];ctx.fillRect(x+4+i*5.5,y+5,5.5,86);}ctx.strokeStyle='#cfe5e344';ctx.lineWidth=.7;ctx.strokeRect(x+3,y+4,89,88);}ctx.strokeStyle='#d5e4e7';ctx.lineWidth=2;ctx.beginPath();ctx.arc(384,384,376,0,Math.PI*2);ctx.stroke();waferTexture.needsUpdate=true;}
    function topColor(column,latent=0){const layer=column.at(-1),under=column.at(-2),mix=(a,b,t)=>{const x=parseInt(a.slice(1),16),y=parseInt(b.slice(1),16);return '#'+[16,8,0].map(shift=>Math.round(((x>>shift)&255)*(1-t)+((y>>shift)&255)*t).toString(16).padStart(2,'0')).join('');};let color=E.materials[layer?.material]?.color||'#708798';if(under)color=mix(E.materials[under.material].color,color,Math.min(1,layer.nm/80));if(layer?.material==='PR'&&latent>0)color=mix(color,'#d9ef9f',Math.min(.55,latent/180));return color;}
    let desiredDistance=11,distance=11,azimuth=.4,desiredAzimuth=.4,elevation=.5,desiredElevation=.5,cameraMode='equipment',drag=null,last=performance.now(),raf;
    function setCamera(mode){cameraMode=mode;const family=currentStep?E.tools[currentStep.tool].family:'';desiredTarget.set(0,family==='furnace'?2.55:2,0);desiredDistance=Math.max(family==='implant'?13:family==='furnace'?12:10.7,8/Math.max(.6,camera.aspect));desiredAzimuth=.4;desiredElevation=.5;if(mode==='top'){desiredElevation=1.48;desiredAzimuth=0;}if(mode==='wafer'){desiredTarget.copy(wafer.position);desiredDistance=4.5;desiredAzimuth=.24;desiredElevation=.83;}if(typeof mode==='number'&&parts[mode]){desiredTarget.set(...parts[mode][1]);desiredDistance=5;desiredElevation=.4;}}
    let lastWidth=0,lastHeight=0;
    const resize=()=>{if(disposed)return;const w=host.clientWidth,h=host.clientHeight;if(!w||!h||w===lastWidth&&h===lastHeight)return;lastWidth=w;lastHeight=h;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();};const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(host);
    const raycaster=new T.Raycaster(),pointer=new T.Vector2();
    function inspectAt(e){const rect=renderer.domElement.getBoundingClientRect();if(!rect.width||!rect.height||e.clientX<rect.left||e.clientX>rect.left+rect.width||e.clientY<rect.top||e.clientY>rect.top+rect.height)return;pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects([equipment,wafer],true).some(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent;}return h.object.material?.opacity!==0;});if(hit&&currentStep)onInspect(currentStep);}
    listen('pointerdown',e=>{if(e.button!==0||e.isPrimary===false)return;drag={x:e.clientX,y:e.clientY,a:desiredAzimuth,e:desiredElevation,id:e.pointerId,moved:false};renderer.domElement.setPointerCapture(e.pointerId);});
    listen('pointermove',e=>{if(drag&&e.pointerId===drag.id){drag.moved||=Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>6;if(drag.moved){desiredAzimuth=drag.a-(e.clientX-drag.x)*.007;desiredElevation=T.MathUtils.clamp(drag.e+(e.clientY-drag.y)*.006,.12,1.5);}}});
    listen('pointerup',e=>{if(!drag||e.pointerId!==drag.id)return;const click=!drag.moved&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<=6;drag=null;if(renderer.domElement.hasPointerCapture?.(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);if(click)inspectAt(e);});listen('pointercancel',()=>drag=null);listen('lostpointercapture',()=>drag=null);
    listen('wheel',e=>{e.preventDefault();desiredDistance=T.MathUtils.clamp(desiredDistance*Math.exp(e.deltaY*.001),2.8,25);},{passive:false});listen('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();if(!e.repeat&&currentStep)onInspect(currentStep);return;}if(e.key==='ArrowLeft')desiredAzimuth-=.12;else if(e.key==='ArrowRight')desiredAzimuth+=.12;else if(e.key==='ArrowUp')desiredElevation=Math.min(1.5,desiredElevation+.1);else if(e.key==='ArrowDown')desiredElevation=Math.max(.12,desiredElevation-.1);else return;e.preventDefault();});
    let spin=0,headSpin=0;
    function handlingPosition(m){const startX=E.tools[currentStep.tool].family==='implant'?-4.15:-3.1,high=Math.max(1.93,activePoint.y)+.5;return new T.Vector3(T.MathUtils.lerp(startX,activePoint.x,m.travel),T.MathUtils.lerp(1.93,high,m.rise)+(activePoint.y-high)*m.lower,T.MathUtils.lerp(1.1,activePoint.z,m.travel));}
    function tick(now){
      if(disposed)return;raf=requestAnimationFrame(tick);const dt=Math.max(0,Math.min(.1,(now-last)/1000));last=now;if(document.hidden||contextLost)return;
      if(frameState&&currentStep){
        const state=frameState,m=motion(state.phase,state.progress),rate=state.running?dt*(state.speed||1):0,recipe=state.recipe||currentStep.recipe,scan=stageMotion(state.phase==='process'?state.progress:0);clock+=rate;spin+=rate*6*Math.min(1.7,Math.max(.4,(recipe.rpm||3000)/3000))*m.processing;headSpin+=rate*2*Math.min(2,Math.max(.5,(recipe.rpm||60)/60))*m.processing;
        effects.forEach(e=>{e.userData.baseOpacity??=e.material.opacity;let envelope=e===animated.stream&&currentStep.tool==='coat'?m.processing*(1-smooth(((state.progress||0)-.45)/.12)):m.processing;if(e===animated.beam&&animated.stage)envelope*=scan.contact;e.visible=envelope>.001;e.material.opacity=e.userData.baseOpacity*envelope;});
        if(animated.particles){animated.particles.visible=m.processing>.01;animated.particles.children.forEach(p=>{const travel=(clock*.5+p.userData.phase)%1;p.position.y=2.7-travel*.83;p.scale.setScalar(Math.sqrt(Math.max(0,Math.sin(Math.PI*travel))));});}
        if(animated.nozzle)animated.nozzle.rotation.y=-.9*(1-m.nozzle);
        if(animated.lid)animated.lid.position.y=2.75-.66*m.closed;
        if(animated.stage){animated.stage.position.x=scan.x;animated.stage.position.z=scan.z;}
        if(animated.probes)animated.probes.position.y=.22*(1-scan.contact);
        if(animated.platen)animated.platen.rotation.y=-headSpin*.7;
        if(animated.head)animated.head.rotation.y=headSpin;
        wafer.position.copy(handlingPosition(m));wafer.rotation.set(waferOrientation.x*m.orientation,waferOrientation.y*m.orientation,waferOrientation.z*m.orientation);
        if(E.tools[currentStep.tool].family==='spin')wafer.rotation.y=spin;
        if(E.tools[currentStep.tool].family==='cmp')wafer.rotation.y=headSpin;
        if(animated.stage){wafer.position.x+=animated.stage.position.x;wafer.position.z+=animated.stage.position.z;}
        const home=handlingPosition(motion('idle',0)),parked=home.clone();parked.y-=.16;
        let armPoint=parked;
        if(state.phase==='load'){armPoint=wafer.position.clone();armPoint.y-=.16*(1-smooth((state.progress||0)/.08));}
        if(state.phase==='condition'&&state.progress<.5){armPoint=activePoint.clone().lerp(home,smooth((state.progress-.1)/.4));armPoint.y-=.16*smooth(state.progress/.1);}
        if(state.phase==='unload'){if(state.progress<.22){armPoint=parked.clone().lerp(activePoint,smooth(state.progress/.22));}else{armPoint=wafer.position.clone();armPoint.y-=.16*smooth((state.progress-.94)/.06);}}
        poseTransfer(armPoint,true);paint(state.wafer);
      }
      if(cameraMode==='wafer')desiredTarget.copy(wafer.position);
      const alpha=1-Math.exp(-dt*8);target.lerp(desiredTarget,alpha);distance=T.MathUtils.lerp(distance,desiredDistance,alpha);azimuth=T.MathUtils.lerp(azimuth,desiredAzimuth,alpha);elevation=T.MathUtils.lerp(elevation,desiredElevation,alpha);camera.position.set(target.x+distance*Math.cos(elevation)*Math.sin(azimuth),target.y+distance*Math.sin(elevation),target.z+distance*Math.cos(elevation)*Math.cos(azimuth));camera.lookAt(target);renderer.render(scene,camera);
    }
    resize();raf=requestAnimationFrame(tick);
    return {select:build,update:s=>frameState=s,camera:setCamera,parts:()=>parts.map(([name,position])=>({name,position})),cutaway(value){cut=value;shell.forEach(o=>{if(o.material===mat.glass)return;o.material.opacity=cut?.07:1;o.material.depthWrite=!cut;o.castShadow=!cut;});},scene,wafer,renderer,viewCamera:camera,dispose(){
      if(disposed)return;disposed=true;cancelAnimationFrame(raf);resizeObserver.disconnect();listeners.forEach(remove=>remove());recovery.remove();
      const geometries=new Set(),materials=new Set(),textures=new Set();
      scene.traverse(object=>{if(object.geometry)geometries.add(object.geometry);for(const material of Array.isArray(object.material)?object.material:[object.material])if(material)materials.add(material);object.shadow?.dispose?.();});
      for(const material of materials)for(const value of Object.values(material))if(value?.isTexture)textures.add(value);
      if(scene.environment?.isTexture)textures.add(scene.environment);geometries.forEach(item=>item.dispose());materials.forEach(item=>item.dispose());textures.forEach(item=>item.dispose());scene.clear();renderer.dispose();renderer.domElement.remove();
    }};
  }
  root.FabViewport={mount,motion,stageMotion};
})(window);
