(function(root){
  'use strict';
  const E=root.FabEngine,$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
  const KEY='waferflow-fab-v05',SCHEMA='waferflow-fab-history-v1',faults=['none','dose','uniformity','vacuum'];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(n,d=1)=>n==null?'—':Number(n).toLocaleString('en-US',{maximumFractionDigits:d});
  const amount=(n,d=2)=>Math.abs(n)>=1e6||(Math.abs(n)>0&&Math.abs(n)<.001)?Number(n).toExponential(d):fmt(n,d);
  const time=s=>s<60?fmt(s)+' s':s<3600?fmt(s/60)+' min':fmt(s/3600,2)+' h';
  const state={wafers:[],active:'W01',selected:0,expanded:new Set(['well']),running:null,busy:false,stopAdvance:false,before:false,probe:40,tab:'metrics',compare:'',compareCount:null,preview:null,sweep:null,feedback:'',error:false,lastFrame:0,lastDraw:0};
  let shown=null,before=null,view=null,renderedTool=null,toastTimer=null,replayCache=new Map();
  function entry(){return state.wafers.find(w=>w.id===state.active);}
  function current(){return entry().wafer;}
  function makeEntry(id,records=[],overrides={},conditions={},parent=null){return {id,title:'',note:'',wafer:E.replay(id,records),overrides,conditions,parent,events:[]};}
  function pack(){return {schema:SCHEMA,modelVersion:E.VERSION,lotId:'CMOS-001',exportedAt:new Date().toISOString(),active:state.active,selected:state.selected,wafers:state.wafers.map(w=>({id:w.id,title:w.title,note:w.note,parent:w.parent,records:w.wafer.records,overrides:w.overrides,conditions:w.conditions,events:w.events})),notice:'Independent geometric model; coefficients are not calibrated. Local editable experiment records, not production approval evidence.'};}
  function decode(data){
    if(data?.schema!==SCHEMA||data.modelVersion!==E.VERSION||!Array.isArray(data.wafers)||data.wafers.length<1||data.wafers.length>25)throw Error('지원하지 않는 기록 형식·모델 버전 또는 웨이퍼 수입니다.');
    const ids=new Set();return data.wafers.map(item=>{if(typeof item.id!=='string'||!/^[A-Za-z0-9_-]{1,32}$/.test(item.id)||ids.has(item.id))throw Error('웨이퍼 ID가 잘못되었거나 중복됩니다.');ids.add(item.id);if(!Array.isArray(item.records)||item.records.length>E.route.length)throw Error('공정 기록 수가 잘못되었습니다.');
      const overrides={},conditions={};for(const [id,p] of Object.entries(item.overrides||{})){const step=E.route.find(s=>s.id===id);if(!step||!p||typeof p!=='object')throw Error('레시피 공정 ID가 올바르지 않습니다.');overrides[id]=E.recipeFor(step,p);}
      for(const [id,f] of Object.entries(item.conditions||{})){if(!E.route.some(s=>s.id===id)||!faults.includes(f))throw Error('알 수 없는 이상 조건입니다.');conditions[id]=f;}
      const records=item.records.map((r,i)=>{const step=E.route[i];if(r.stepId!==step.id||r.modelVersion!==E.VERSION||!faults.includes(r.fault||'none')||!r.recipe||Object.keys(E.tools[step.tool].fields).some(k=>!Object.hasOwn(r.recipe,k))||!Number.isFinite(Date.parse(r.time)))throw Error('공정 순서·시간·레시피·이상 조건을 검증하지 못했습니다.');return {...r,recipe:E.recipeFor(step,r.recipe)};});
      const parent=item.parent&&typeof item.parent.id==='string'&&Number.isInteger(item.parent.from)&&item.parent.from>=0&&item.parent.from<E.route.length?{id:item.parent.id.slice(0,32),from:item.parent.from}:null;
      if((item.title!=null&&typeof item.title!=='string')||(item.note!=null&&typeof item.note!=='string'))throw Error('실험 이름과 메모는 문자열이어야 합니다.');
      const w=makeEntry(item.id,records,overrides,conditions,parent);w.title=(item.title||'').slice(0,60);w.note=(item.note||'').slice(0,2000);w.events=Array.isArray(item.events)?item.events.slice(-200).map(e=>({stepId:String(e.stepId||'').slice(0,12),message:String(e.message||'').slice(0,500),time:String(e.time||'').slice(0,40)})):[];return w;
    });
  }
  function persist(){try{localStorage.setItem(KEY,JSON.stringify(pack()));$('#saveStatus').textContent='✓ 이 브라우저에 저장됨';$('#saveStatus').classList.remove('error');}catch{$('#saveStatus').textContent='저장 실패 · JSON으로 보관하세요';$('#saveStatus').classList.add('error');}}
  function notify(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,5000);}
  function explainEquipment(){
    if(state.busy)return;
    const step=E.route[state.selected],tool=E.tools[step.tool],guide=root.FabGuide.tools[step.tool],dialog=$('#equipmentDialog');
    const wasRunning=!!state.running&&!state.running.paused;
    if(wasRunning){state.running.paused=true;syncControls();draw();}
    $('#equipmentDialogTitle').textContent=tool.name;$('#equipmentDialogEnglish').textContent=tool.english;
    const sceneParts=view.parts(),parts=root.FabGuide.parts[tool.family];
    $('#equipmentDialogBody').innerHTML=`<p class="equipment-role">${esc(guide.role)}</p><div class="guide-flow">${guide.flow.map((label,i)=>`<div><span>${['들어오는 상태','장비의 작용','처리 후'][i]}</span><strong>${esc(label)}</strong></div>`).join('')}</div><section class="guide-current"><span class="eyebrow">CURRENT OPERATION · ${step.id}</span><h3>${esc(step.name)}</h3><p>${esc(guide.observe)}</p>${step.mask?`<span class="guide-chip">마스크 · ${esc(step.mask.toUpperCase())}</span>`:''}${step.material?`<span class="guide-chip">증착 재료 · ${esc(step.material)}</span>`:''}${step.targets?`<span class="guide-chip">제거 대상 · ${esc(step.targets.join(' / '))}</span>`:''}${step.species?`<span class="guide-chip">주입 원소 · ${esc(step.species)}</span>`:''}</section><h3>어떤 순서로 작동하나요?</h3><ol class="guide-steps">${guide.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><h3>주요 부품과 역할</h3><div class="guide-parts">${parts.map(([name,description],i)=>`<article><span class="guide-part-number">0${i+1}</span><h4>${esc(sceneParts[i]?.name||name)}</h4><p>${esc(description)}</p>${sceneParts[i]?`<button type="button" data-guide-part="${i}">3D에서 이 부품 보기 ↗</button>`:''}</article>`).join('')}</div><h3>현재 조건을 바꾸면?</h3><p class="guide-params-note">아래 설명은 이 시뮬레이터의 계산 경향입니다. 값은 현재 입력 중인 레시피입니다.</p><div class="guide-parameters">${Object.entries(tool.fields).map(([k,f])=>`<div><span><b>${esc(f.label)}</b><em>${esc($('#recipe-'+k)?.value??'—')} ${esc(f.unit)}</em></span><p>${esc(guide.knobs[k])}</p></div>`).join('')}</div><div class="guide-references"><span>공정 원리 참고</span>${guide.sources.map(key=>`<a href="${esc(root.FabGuide.sources[key].url)}" target="_blank" rel="noreferrer">${esc(root.FabGuide.sources[key].name)} ↗</a>`).join('')}</div>`;
    $('#equipmentDialogStatus').textContent=wasRunning?'공정을 일시 정지했습니다. 닫은 뒤 ‘계속 실행’으로 이어갈 수 있습니다.':'원리 학습용 설명입니다. 현재 웨이퍼와 입력 조건은 유지됩니다.';
    if(!dialog.open)dialog.showModal();$('#equipmentDialogBody').scrollTop=0;
  }
  try{const saved=localStorage.getItem(KEY);if(saved){const data=JSON.parse(saved);state.wafers=decode(data);state.active=state.wafers.some(w=>w.id===data.active)?data.active:state.wafers[0].id;state.selected=Number.isInteger(data.selected)?Math.max(0,Math.min(E.route.length-1,data.selected)):Math.min(current().cursor,E.route.length-1);}}catch(e){state.feedback='저장 기록을 복원하지 못했습니다. '+e.message;}
  if(!state.wafers.length)state.wafers=[makeEntry('W01')];
  state.expanded.add(E.route[state.selected].module);
  function at(w,count){if(count===w.wafer.cursor)return w.wafer;const key=w.id+':'+w.wafer.cursor+':'+count;if(!replayCache.has(key)){if(replayCache.size>30)replayCache.clear();replayCache.set(key,E.replay(w.id,w.wafer.records,count));}return replayCache.get(key);}
  function select(index){if(state.running||state.busy){notify(state.running?'현재 공정을 완료하거나 실행을 취소한 뒤 다른 공정을 선택하세요.':'앞 공정 계산을 완료한 뒤 선택할 수 있습니다.');return;}state.selected=Math.max(0,Math.min(E.route.length-1,index));state.expanded.add(E.route[state.selected].module);state.before=false;state.feedback='';state.error=false;render();persist();}
  function renderRoute(){$('#experimentTitle').textContent=entry().title||'실험 이름 · 메모';$('#experimentNote').textContent=entry().note;$('#experimentNote').hidden=!entry().note;const w=current(),q=$('#routeSearch').value.trim().toLowerCase();$('#routeCount').textContent=E.route.length+' OPS';$('#waferSelect').innerHTML=state.wafers.map(e=>`<option value="${esc(e.id)}" ${e.id===state.active?'selected':''}>${esc(e.id)}${e.title?' · '+esc(e.title):''}${e.parent?' · 분기':''} · ${e.wafer.cursor}/${E.route.length}</option>`).join('');$('#waferSelect').value=state.active;$('#waferProgress').textContent=w.cursor+' / '+E.route.length+' 완료';$('#progressPercent').textContent=Math.round(w.cursor/E.route.length*100)+'%';$('#routeProgressBar').style.width=(w.cursor/E.route.length*100)+'%';
    $('#routeList').innerHTML=E.modules.map((m,mi)=>{const list=E.route.filter(s=>s.module===m.id),filtered=q?list.filter(s=>(s.id+' '+s.name+' '+E.tools[s.tool].name+' '+E.tools[s.tool].english).toLowerCase().includes(q)):list;const open=state.expanded.has(m.id)||!!q;if(!filtered.length)return '';return `<div class="route-module"><button class="module-toggle" data-module="${m.id}" aria-expanded="${open}"><span class="module-number">${String(mi+1).padStart(2,'0')}</span>${m.name}<span class="module-count">${list.filter(s=>s.index<w.cursor).length}/${list.length}</span><span class="chevron">${open?'−':'+'}</span></button><div ${open?'':'hidden'}>${filtered.map(s=>`<button class="route-step ${s.index<w.cursor?'done':''} ${s.index===w.cursor?'current':''} ${s.index===state.selected?'selected':''} ${w.records[s.index]?.warnings.length?'warning':''}" data-step="${s.index}" ${s.index===state.selected?'aria-current="step"':''}><span class="step-marker">${s.index<w.cursor?'✓':''}</span><span>${s.name}<small>${s.id} · ${s.tool.toUpperCase()}</small></span></button>`).join('')}</div></div>`;}).join('');if(!$('#routeList').children.length)$('#routeList').innerHTML='<div class="route-no-results">검색된 공정이 없습니다.<br>공정 이름 또는 장비명으로 검색하세요.</div>';
  }
  function renderRecipe(){const step=E.route[state.selected],tool=E.tools[step.tool],done=state.selected<current().cursor,p=E.recipeFor(step,entry().overrides[step.id]??(done?current().records[state.selected].recipe:undefined));$('#moduleTag').textContent=E.modules.find(m=>m.id===step.module).tag;$('#operationId').textContent=step.id+' / '+String(E.route.length);$('#operationName').textContent=step.name;$('#operationDescription').textContent=tool.principle;$('#toolTitle').textContent=tool.english;$('#toolId').textContent=tool.family.toUpperCase()+'-01';$('#recipeTitle').textContent=tool.name;$('#materialContext').textContent=step.mask?'MASK · '+step.mask.toUpperCase():step.material?'FILM · '+step.material:step.species?'IMPLANT · '+step.species:step.targets?'TARGET · '+step.targets.join(' / '):'OPERATION · '+step.op.toUpperCase();$('#recipeState').textContent=done?'RECORDED':entry().overrides[step.id]?'MODIFIED':'REFERENCE';
    $('#recipeFields').innerHTML=Object.entries(tool.fields).map(([k,f])=>`<div class="recipe-field"><label for="recipe-${k}">${f.label}<span>${amount(f.min)}–${amount(f.max)}</span></label><div class="recipe-input"><input id="recipe-${k}" data-field="${k}" type="number" min="${f.min}" max="${f.max}" step="${f.step}" value="${p[k]}" aria-describedby="recipeEditHint recipe-error-${k}"><span>${f.unit}</span></div><span id="recipe-error-${k}" class="recipe-field-error" hidden></span></div>`).join('');$('#recipeDuration').textContent=time(E.duration(step,p));$('#faultSelect').value=entry().conditions[step.id]??(done?current().records[state.selected].fault:'none');$('#faultNote').textContent='기록되는 이상 조건 · '+({dose:'노광 단계에만 적용됩니다.',vacuum:'진공 장비에서 공정을 시작하지 못하도록 보류합니다.',uniformity:'증착·코팅·산화·식각의 위치별 편차를 늘립니다.',none:'정상 조건으로 계산합니다.'}[$('#faultSelect').value]);
    $('#equipmentCaption').textContent='원리 관찰용 장비 모형';view.select(step);view.cutaway($('#cutaway').checked);if(renderedTool!==step.tool)$$('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera==='equipment'));renderedTool=step.tool;$('#partButtons').innerHTML=view.parts().map((p,i)=>`<button data-part="${i}" title="${esc(p.name)}">${i+1} · ${esc(p.name.split(' / ')[0])}</button>`).join('');syncControls();
  }
  function recipeChanged(recipe,fault){try{const p=readRecipe();return Object.keys(p).some(k=>p[k]!==recipe[k])||$('#faultSelect').value!==fault;}catch{return true;}}
  function syncControls(){
    const w=current(),done=state.selected<w.cursor,future=state.selected>w.cursor,busy=!!state.running||state.busy,locked=state.busy||!!(state.running&&!state.running.paused),full=state.wafers.length>=25;
    const changed=state.running?.paused&&recipeChanged(state.running.recipe,state.running.fault),record=done?w.records[state.selected]:null,draft=!!record&&recipeChanged(record.recipe,record.fault);
    $('#cancelRunButton').hidden=!busy;$('#cancelRunButton').disabled=state.stopAdvance;$('#cancelRunButton').textContent=state.busy?'앞 공정 계산 중단 · 완료 기록 유지':'현재 실행 취소 · 완료 기록 유지';$('#equipmentHelpButton').disabled=state.busy;$('#runButton').disabled=state.busy||(!state.running&&(future||(done&&full)));
    $('#runButton').textContent=state.running?(state.running.paused?(changed?'↻ 변경 조건으로 다시 시작':'▶ 계속 실행'):'Ⅱ 일시 정지'):done?'▶ 이 조건으로 새 실험':future?'앞 공정 완료 후 실행':'▶ 선택 공정 실행';
    $('#nextButton').hidden=!done||w.cursor>=E.route.length;$('#nextButton').disabled=busy;$('#advanceButton').hidden=!future;$('#advanceButton').disabled=busy;$('#advanceButton').textContent=`앞선 ${Math.max(0,state.selected-w.cursor)}개 공정 계산`;$('#forkButton').hidden=!done;$('#forkButton').disabled=busy||full;
    $('#previewButton').disabled=busy||future;const sweepRun=$('#sweepRun');if(sweepRun)sweepRun.disabled=busy||future;$$('[data-sweep-row]').forEach(b=>b.disabled=busy);$('#defaultsButton').disabled=locked;$$('[data-field]').forEach(e=>{e.disabled=locked;const baseline=record?.recipe[e.dataset.field]??E.route[state.selected].recipe[e.dataset.field];e.classList.toggle('is-edited',e.value.trim()!==''&&Number(e.value)!==baseline);e.title=(record?'원본 실행값: ':'기준값: ')+baseline;});$('#faultSelect').disabled=locked;$('#restoreRecordButton').hidden=!done;$('#restoreRecordButton').disabled=locked||!draft;
    $('#recipeState').textContent=locked?'RUNNING':draft||changed?'MODIFIED':done?'EDITABLE':entry().overrides[E.route[state.selected].id]?'MODIFIED':'REFERENCE';
    $('#recipeEditHint').textContent=state.busy?'앞 공정 계산이 끝나면 수치를 수정할 수 있습니다.':state.running?(state.running.paused?(changed?'변경 조건으로 공정 처음부터 다시 계산합니다. 완료된 이전 공정은 유지됩니다.':'일시정지 중입니다. 수치를 수정하거나 그대로 계속 실행할 수 있습니다.'):'일시 정지를 누르면 수치를 수정할 수 있습니다.'):done?(full?'수정은 가능하지만 새 실험은 웨이퍼 25개 한도에 도달했습니다.':'수치를 바로 수정하세요. 실행하면 원본 기록을 보존한 새 실험이 만들어집니다.'):future?'이 공정의 조건을 미리 수정할 수 있습니다. 실행 전 앞 공정을 계산하세요.':'수치를 입력한 뒤 실행하세요. 아래 단면·계측값은 실행 후 갱신됩니다.';
    for(const id of ['waferSelect','newWafer','importButton','editExperiment','jumpCurrent'])$('#'+id).disabled=busy;$('#newWafer').disabled=busy||full;$('#beforeButton').disabled=state.selected>w.cursor||(!done&&!state.running&&!state.preview);$('#runFeedback').textContent=state.feedback;$('#faultNote').textContent={none:'정상 조건으로 계산합니다.',dose:'노광 단계에만 적용되는 출력 저하입니다.',uniformity:'막·식각의 위치별 편차를 늘립니다.',vacuum:'진공 장비에서 공정을 보류하는 인터록입니다.'}[$('#faultSelect').value];
    const badge=$('#runState');badge.className='state-badge'+(state.error?' hold':state.running?' running':'');badge.textContent=state.busy?'CALCULATING':state.running?(state.running.paused?'PAUSED':'PROCESSING'):state.error?'CHECK':state.preview?'PREVIEW':draft?'DRAFT':done?'RECORDED':future?'PREVIEW':w.cursor===E.route.length?'COMPLETE':'READY';$('#viewContext').textContent=state.running?'현재 공정 실행 중':state.preview?'미리 계산 결과 · 실행 기록 유지':done?(draft?'변경 조건 초안 · 단면은 원본 결과':'원본 결과 보기 · 조건 수정 가능'):future?'장비 미리 보기 · 단면은 현재 상태':'다음 실행 공정';
  }
  function chooseDisplay(){const w=current();shown=state.selected<w.cursor?at(entry(),state.selected+1):w;before=state.selected<w.cursor?at(entry(),state.selected):w;}
  function render(){state.preview=null;state.sweep=null;renderRoute();renderRecipe();chooseDisplay();draw();renderHistory();renderCompare();renderSweep();setPhase('idle',0,0);$('#historyCount').textContent=current().records.length;$('#waferStatus').textContent=state.active+' · '+(entry().parent?'BRANCH FROM '+entry().parent.id:'PLANAR CMOS');$('#virtualTime').textContent='누적 처리 시간 '+time(current().virtualSeconds);}
  function updateViewport(){view.update({wafer:shown,running:!!state.running&&!state.running.paused,phase:state.running?.phase||'idle',progress:state.running?.phaseProgress||0,speed:Number($('#speedSelect').value||1),recipe:state.running?.recipe||E.recipeFor(E.route[state.selected],entry().overrides[E.route[state.selected].id])});}
  function draw(){const w=state.before?before:shown;if(!w)return;drawSection(w);drawMetrics(w);updateViewport();setPhase(state.running?.phase||'idle',state.running?.phaseProgress||0,state.running?Math.min(1,state.running.elapsed/6):0);$('#beforeButton').setAttribute('aria-pressed',String(state.before));$('#sectionStatus').textContent=state.before?'선택 공정 전':state.preview?'미리 계산 · 실행 기록 아님':state.running?'실시간 계산':state.selected<current().cursor?'선택 공정 완료 후':'현재 웨이퍼 상태';}
  function drawSection(w){const max=Math.max(120,E.summarize(shown).surfaceMax,E.summarize(before).surfaceMax)+70,min=-E.BASE,W=820,H=245,L=46,R=12,T=27,B=27,plotW=W-L-R,plotH=H-T-B,cell=plotW/E.NX,y=z=>T+(max-z)/(max-min)*plotH;let svg=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="${esc(E.route[state.selected].name)} 재료 단면"><rect width="${W}" height="${H}" fill="#fbfcfd"/>`;const text=(x,yy,s,anchor='start')=>`<text x="${x}" y="${yy}" fill="#8a9da6" font-family="Consolas,monospace" font-size="9" text-anchor="${anchor}">${s}</text>`;
    for(let k=0;k<=4;k++){const z=min+(max-min)*k/4;svg+=`<path d="M${L},${y(z)}H${W-R}" stroke="#e7edef" stroke-width=".7"/>`+text(L-7,y(z)+3,fmt(z,0),'end');}svg+=text(8,13,'nm');
    const present=new Set();for(let i=0;i<E.NX;i++){let base=-E.BASE;for(const l of w.columns[i]){present.add(l.material);const top=base+l.nm;svg+=`<rect x="${L+i*cell}" y="${y(top)}" width="${cell+.05}" height="${Math.max(.12,y(base)-y(top))}" fill="${E.materials[l.material].color}"/>`;base=top;}}
    if(w.latent){for(let i=0;i<E.NX;i++){const pr=w.columns[i].at(-1);if(pr?.material==='PR'){const top=E.height(w.columns[i]),opacity=Math.min(.55,w.latent[i]/180);svg+=`<rect x="${L+i*cell}" y="${y(top)}" width="${cell+.05}" height="${Math.max(.12,pr.nm/(max-min)*plotH)}" fill="#d9ef9f" opacity="${opacity}"/>`;}}}
    if($('#dopingToggle').checked&&w.dopants.length){for(let i=0;i<E.NX;i+=4){const si=w.columns[i].find(l=>l.material==='Si');if(!si)continue;for(let depth=15;depth<Math.min(si.nm,600);depth+=30){const n=E.dopingAt(w,i,depth),a=Math.min(.7,Math.max(0,(Math.log10(Math.abs(n))-15)/5));if(a>.02)svg+=`<rect x="${L+i*cell}" y="${y(si.nm-E.BASE-depth+15)}" width="${cell*4+.1}" height="${30/(max-min)*plotH+.1}" fill="${n>0?'#70d1ee':'#f5a9a2'}" opacity="${a}"/>`;}}svg+=text(W-R,13,'N: cyan / P: rose','end');}
    const mask=E.route[state.selected].mask;if($('#maskToggle').checked&&mask){svg+=text(L,13,'MASK '+esc(mask.toUpperCase()));for(let i=0;i<E.NX;i++){if(!E.maskOpen(mask,(i+.5)/E.NX))svg+=`<rect x="${L+i*cell}" y="18" width="${cell+.03}" height="4" fill="#354e5f"/>`;}}
    const px=L+(state.probe+.5)*cell;svg+=`<path d="M${px},${T}V${H-B}" stroke="#173e4e" stroke-width="1" stroke-dasharray="3 3" opacity=".6"/><path d="M${px-3},${T-5}h6l-3,4z" fill="#173e4e"/>`;
    for(let k=0;k<=4;k++)svg+=text(L+plotW*k/4,H-9,fmt(E.WIDTH/1000*k/4,2)+(k===4?' µm':''),'middle');svg+='</svg>';$('#crossSection').innerHTML=svg;$('#materialLegend').innerHTML=Array.from(present).map(m=>`<span><i style="background:${E.materials[m].color}"></i>${m}</span>`).join('')+(w.latent&&present.has('PR')?'<span><i style="background:#d9ef9f"></i>노광 잠상 · 제거 전 PR</span>':'');$('#probePosition').textContent='X = '+fmt((state.probe+.5)*E.WIDTH/E.NX/1000,3)+' µm';$('#layerStack').innerHTML=w.columns[state.probe].slice().reverse().map(l=>`<div class="layer-row"><i style="background:${E.materials[l.material].color}"></i><span>${l.material}</span><strong>${fmt(l.nm)} nm</strong></div>`).join('');const dop=E.dopingAt(w,state.probe,50);$('#dopantValue').innerHTML=`깊이 50 nm · 활성 순농도<br>${dop>0?'N':'P'} ${Math.abs(dop).toExponential(2)} cm⁻³<br><span>기판 표시 범위: 600 nm</span>`;
  }
  function drawMetrics(w){const m=E.summarize(w),record=state.selected<current().cursor?current().records[state.selected]:null;const warnings=state.before?[]:state.preview?.warnings||record?.warnings||state.running?.warnings||[];const topFilm=w.columns[state.probe].at(-1);const gateIndex=E.route.find(s=>s.name==='폴리 게이트 패턴 식각').index,gatePatterned=w.cursor>gateIndex||(!state.before&&!!state.preview&&state.selected>=gateIndex);$('#metricsPanel').innerHTML=`${state.preview?'<p class="preview-result-note">미리 계산한 결과입니다. 웨이퍼 진행 상태와 실행 기록에는 반영되지 않았습니다.</p>':''}<div class="metrics-grid"><div class="metric"><span>선택 위치 최상층 · ${esc(topFilm?.material||'—')}</span><strong>${fmt(topFilm?.nm)}<small>nm</small></strong><p>대표 단면의 해당 위치</p></div><div class="metric"><span>표면 최대–최소 단차</span><strong>${fmt(m.topography)}<small>nm</small></strong><p>전체 160개 위치의 높이 차이</p></div><div class="metric"><span>폴리 게이트 평균 폭</span><strong>${gatePatterned?fmt(m.gateCD):'—'}<small>nm</small></strong><p>30 nm 격자 기반 구조 값</p></div><div class="metric"><span>주입 분포 평균 활성 비율</span><strong>${fmt(m.activation)}<small>%</small></strong><p>${m.implants}개 주입 이력 · 축약 열처리 모델</p></div></div>${warnings.length?'<div class="warning-list">'+warnings.map(a=>`<p><b>${esc(a.code)}</b> · ${esc(a.message)}</p>`).join('')+'</div>':''}<p class="measurement-note">${w.lastMeasurement?.stepId===E.route[state.selected].id?'현재 공정의 '+w.lastMeasurement.samples+'개 위치를 샘플링했습니다. ':''}구조 계산 결과입니다. 실제 공정 데이터·전기 수율로 해석하지 않습니다.</p>`;if(w.lastMeasurement?.stepId===E.route[state.selected].id){const sites=w.lastMeasurement.sites,mean=sites.reduce((a,b)=>a+b.surface_nm,0)/sites.length,sd=Math.sqrt(sites.reduce((a,b)=>a+(b.surface_nm-mean)**2,0)/(sites.length-1));$('#metricsPanel').innerHTML+=`<details class="measurement-details"><summary>${sites.length}개 계측 지점 보기 · 표면 높이 평균 ${fmt(mean)} nm / 표본 표준편차 ${fmt(sd)} nm</summary><div class="table-wrap"><table><thead><tr><th>지점</th><th>X (µm)</th><th>표면 높이 (nm)</th><th>최상층</th><th>두께 (nm)</th></tr></thead><tbody>${sites.map((site,i)=>`<tr><td>S${String(i+1).padStart(2,'0')}</td><td>${fmt(site.x_nm/1000,3)}</td><td>${fmt(site.surface_nm)}</td><td>${site.top_material}</td><td>${fmt(site.top_thickness_nm)}</td></tr>`).join('')}</tbody></table></div></details>`;}}
  function renderHistory(){const records=current().records;$('#historyPanel').innerHTML=records.length?`<div class="table-wrap"><table><thead><tr><th>공정</th><th>레시피 조건</th><th>시간</th><th>단차</th><th>판정 / 기록</th></tr></thead><tbody>${records.slice().reverse().map(r=>`<tr><td><button class="history-link" data-history="${r.index}">${r.stepId} · ${esc(r.name)}</button></td><td class="mono">${Object.entries(r.recipe).map(([k,v])=>esc(k)+' '+amount(v)).join(' / ')}</td><td class="mono">${time(r.seconds)}</td><td class="mono">${fmt(r.metrics.topography)} nm</td><td>${r.warnings.length?esc(r.warnings.map(w=>w.code).join(', ')):'완료'}${r.fault!=='none'?' · '+esc(r.fault):''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">첫 공정을 실행하면 조건과 결과가 여기에 기록됩니다.</div>';if(entry().events.length)$('#historyPanel').innerHTML+='<div class="warning-list">'+entry().events.slice(-5).reverse().map(e=>`<p>${esc(e.stepId)} · ${esc(e.message)}</p>`).join('')+'</div>';}
  function comparison(){
    const ref=state.wafers.find(e=>e.id===state.compare&&e.id!==state.active);if(!ref)return null;
    const common=Math.min(ref.wafer.cursor,current().cursor),count=state.compareCount==null?common:Math.max(0,Math.min(common,state.compareCount));
    const a=at(ref,count),b=at(entry(),count),differences=[];
    for(let i=0;i<count;i++){
      const left=a.records[i],right=b.records[i],step=E.route[i];
      for(const [key,field] of Object.entries(E.tools[step.tool].fields))if(left.recipe[key]!==right.recipe[key])differences.push({stepId:step.id,name:step.name,field:key,label:field.label,unit:field.unit,reference:left.recipe[key],current:right.recipe[key]});
      if(left.fault!==right.fault)differences.push({stepId:step.id,name:step.name,field:'fault',label:'이상 조건',unit:'',reference:left.fault,current:right.fault});
    }
    return {schema:'waferflow-fab-comparison-v1',modelVersion:E.VERSION,generatedAt:new Date().toISOString(),completedOperations:count,stepId:count?E.route[count-1].id:null,
      reference:{waferId:ref.id,title:ref.title,note:ref.note,records:E.copy(a.records),metrics:E.summarize(a)},current:{waferId:state.active,title:entry().title,note:entry().note,records:E.copy(b.records),metrics:E.summarize(b)},
      profile:a.columns.map((column,i)=>({x_nm:(i+.5)*E.WIDTH/E.NX,reference_nm:E.height(column),current_nm:E.height(b.columns[i])})),differences,
      notice:'Same completed operation, same uncalibrated geometric model. Draft recipes are excluded. Not measurement data or statistical inference.'};
  }
  function compareChart(data){
    const points=data.profile,low=Math.min(...points.flatMap(p=>[p.reference_nm,p.current_nm])),high=Math.max(...points.flatMap(p=>[p.reference_nm,p.current_nm])),pad=Math.max(10,(high-low)*.12),min=low-pad,max=high+pad;
    const x=v=>54+v/E.WIDTH*680,y=v=>22+(max-v)/(max-min)*126,path=key=>points.map((p,i)=>`${i?'L':'M'}${x(p.x_nm).toFixed(2)},${y(p[key]).toFixed(2)}`).join(' ');
    return `<svg class="compare-chart" viewBox="0 0 760 180" role="img" aria-label="같은 공정 완료 시점에서 두 웨이퍼의 표면 높이 비교"><title>기준 ${esc(data.reference.waferId)}와 현재 ${esc(data.current.waferId)}의 4.8 µm 대표 단면 표면 높이</title>${[0,.5,1].map(t=>{const v=min+(max-min)*t;return `<path d="M54 ${y(v)}H734" stroke="#dfe8e4"/><text x="47" y="${y(v)+3}" text-anchor="end">${fmt(v,0)}</text>`;}).join('')}<text x="14" y="14">nm</text><path d="${path('reference_nm')}" fill="none" stroke="#9c8cc3" stroke-width="2" stroke-dasharray="5 3"/><path d="${path('current_nm')}" fill="none" stroke="#197766" stroke-width="2"/>${[0,1.2,2.4,3.6,4.8].map(v=>`<text x="${x(v*1000)}" y="169" text-anchor="middle">${v}</text>`).join('')}<text x="748" y="169">µm</text></svg>`;
  }
  function renderCompare(){
    const options=state.wafers.filter(e=>e.id!==state.active);
    if(!options.length){$('#comparePanel').innerHTML='<div class="empty-state">완료된 공정의 조건을 수정하고 ‘이 조건으로 새 실험’을 실행하세요.<br>원본 이력을 보존한 채 조건과 구조를 비교할 수 있습니다.</div>';return;}
    const ref=options.find(e=>e.id===state.compare)||options.find(e=>e.id===entry().parent?.id)||options[0];state.compare=ref.id;
    const common=Math.min(ref.wafer.cursor,current().cursor);if(state.compareCount>common)state.compareCount=null;
    const data=comparison(),count=data.completedOperations,a=data.reference.metrics,b=data.current.metrics,gateReady=count>E.route.find(s=>s.name==='폴리 게이트 패턴 식각').index;
    const metrics=[['표면 단차',a.topography,b.topography,'nm'],['폴리 평균 폭',gateReady?a.gateCD:null,gateReady?b.gateCD:null,'nm'],['활성 비율',a.activation,b.activation,'%'],...Object.keys(E.materials).filter(k=>k!=='Si'&&(a.films[k].mean>0||b.films[k].mean>0)).map(k=>[k+' 평균 두께',a.films[k].mean,b.films[k].mean,'nm'])];
    const value=v=>typeof v==='number'?(Math.abs(v)>=1e6?v.toExponential(3):fmt(v,3)):esc(v);
    $('#comparePanel').innerHTML=`<div class="comparison-toolbar"><label>기준 웨이퍼<select id="compareSelect">${options.map(e=>`<option value="${esc(e.id)}" ${e.id===ref.id?'selected':''}>${esc(e.id)}${e.title?' · '+esc(e.title):''} · ${e.wafer.cursor}개 완료</option>`).join('')}</select></label><label>비교 공정<select id="compareOperation"><option value="auto" ${state.compareCount==null?'selected':''}>최신 공통 완료 · ${common}개</option><option value="0" ${state.compareCount===0?'selected':''}>입고 상태</option>${E.route.slice(0,common).map(s=>`<option value="${s.index+1}" ${state.compareCount===s.index+1?'selected':''}>${s.id} · ${esc(s.name)}</option>`).join('')}</select></label><button id="exportComparison">비교 JSON ↓</button></div><p class="compare-note">동일 공정 시점에서 비교: ${count?E.route[count-1].id+' · '+E.route[count-1].name:'입고 상태'} (${count}개 완료)</p><div class="comparison-legend"><span class="reference">기준 ${esc(ref.id)}</span><span class="current">현재 ${esc(state.active)}</span><small>표면 높이 · 단면 160개 위치</small></div>${compareChart(data)}<div class="table-wrap"><table><thead><tr><th>구조 지표</th><th>${esc(ref.id)}</th><th>${esc(state.active)}</th><th>현재 − 기준</th></tr></thead><tbody>${metrics.map(([label,left,right,unit])=>`<tr><td>${label}</td><td>${fmt(left)} ${unit}</td><td>${fmt(right)} ${unit}</td><td>${left!=null&&right!=null?fmt(right-left):'—'} ${unit}</td></tr>`).join('')}</tbody></table></div><div class="comparison-differences"><h4>실행 조건 차이 <span>${data.differences.length}개 항목</span></h4>${data.differences.length?`<div class="table-wrap"><table><thead><tr><th>공정</th><th>변수</th><th>${esc(ref.id)}</th><th>${esc(state.active)}</th></tr></thead><tbody>${data.differences.map(d=>`<tr><td>${d.stepId} · ${esc(d.name)}</td><td>${esc(d.label)}</td><td>${value(d.reference)} ${esc(d.unit)}</td><td>${value(d.current)} ${esc(d.unit)}</td></tr>`).join('')}</tbody></table></div>`:'<p>이 시점까지 실행한 조건이 동일합니다.</p>'}</div><p class="compare-note">선택 시점까지 완료된 레시피만 비교합니다. 미실행 초안은 제외됩니다. 같은 모델의 계산 차이이며 실측 통계나 신뢰구간이 아닙니다.</p>`;
  }
  function readRecipe(){
    const p={},errors=[],step=E.route[state.selected];
    for(const input of $$('[data-field]')){
      const key=input.dataset.field,field=E.tools[step.tool].fields[key],value=Number(input.value);let message='';
      if(input.value.trim()==='')message=field.label+' 값을 입력하세요.';
      else try{E.recipeFor(step,{[key]:value});}catch(e){message=e.message;}
      input.setAttribute('aria-invalid',String(!!message));const hint=$('#recipe-error-'+key);if(hint){hint.textContent=message;hint.hidden=!message;}
      if(message)errors.push(message);p[key]=value;
    }
    if(errors.length)throw Error(errors[0]);return E.recipeFor(step,p);
  }
  function sweepMeasure(step,result){
    const w=result.wafer,m=result.metrics,average=a=>a.reduce((s,v)=>s+v,0)/a.length;
    if(step.op==='expose')return {label:'평균 유효 노광량',unit:'mJ/cm²',value:average(w.latent)};
    if(step.op==='implant'){const d=w.dopants.at(-1);return {label:'평균 투과 주입량',unit:'cm⁻²',value:d.dose*average(d.transmission)};}
    if(step.op==='anneal')return {label:'주입 이력 평균 활성 비율',unit:'%',value:m.activation};
    if(step.op==='bake')return {label:'모델 노광 응답 계수',unit:'%',value:w.bakeFactor*100};
    if(step.op==='clean')return {label:'잔여 오염 지표',unit:'모델 단위',value:m.particles};
    if(['cmp','measure','probe'].includes(step.op))return {label:'표면 최대–최소 단차',unit:'nm',value:m.topography};
    const material=step.material||step.targets?.[0]||(step.op==='oxidize'?'SiO2':step.op==='silicide'?'NiSi':'PR');
    return {label:material+' 평균 두께',unit:'nm',value:m.films[material].mean};
  }
  function renderSweep(){
    const step=E.route[state.selected],tool=E.tools[step.tool],previous=$('#sweepField')?.dataset.operation===step.id?$('#sweepField').value:undefined,field=Object.hasOwn(tool.fields,previous)?previous:Object.keys(tool.fields)[0],blocked=!!state.running||state.busy||state.selected>current().cursor;
    $('#sweepPanel').innerHTML=`<div class="sweep-heading"><div><strong>한 변수씩 바꾸어 비교</strong><p>같은 입력 웨이퍼에 5개 조건을 적용합니다. 계산만 수행하며 실행 기록을 추가하지 않습니다.</p></div><span class="tag">${step.id} · MODEL EXPERIMENT</span></div><div class="sweep-controls"><label>변수<select id="sweepField" data-operation="${step.id}">${Object.entries(tool.fields).map(([k,f])=>`<option value="${k}" ${k===field?'selected':''}>${f.label} (${f.unit})</option>`).join('')}</select></label><label>시작값<input id="sweepLow" type="number"></label><label>끝값<input id="sweepHigh" type="number"></label><button id="sweepRun" class="primary-button" ${blocked?'disabled':''}>5조건 계산</button></div><p id="sweepHint" class="compare-note">${state.selected>current().cursor?'선택 공정 직전까지 진행한 뒤 사용할 수 있습니다.':'다른 변수는 현재 입력값으로 고정합니다. 장비 입력 간격에 맞춰 중복 조건은 합칩니다.'}</p><div id="sweepResults"></div>`;
    setSweepBounds();if(state.sweep)drawSweep();
  }
  function setSweepBounds(){
    const step=E.route[state.selected],key=$('#sweepField').value,f=E.tools[step.tool].fields[key],raw=Number($('#recipe-'+key)?.value),center=Number.isFinite(raw)&&raw>=f.min&&raw<=f.max?raw:step.recipe[key],span=Math.max(Math.abs(center)*.2,f.step*2);
    for(const id of ['sweepLow','sweepHigh']){const el=$('#'+id);el.min=f.min;el.max=f.max;el.step=f.step;}
    $('#sweepLow').value=Number(Math.max(f.min,center-span).toPrecision(12));$('#sweepHigh').value=Number(Math.min(f.max,center+span).toPrecision(12));
  }
  function runSweep(){
    if(state.running||state.busy||state.selected>current().cursor)return;
    state.sweep=null;$('#sweepResults').innerHTML='';
    try{const step=E.route[state.selected],key=$('#sweepField').value,f=E.tools[step.tool].fields[key],low=Number($('#sweepLow').value),high=Number($('#sweepHigh').value);
      if(!$('#sweepLow').value.trim()||!$('#sweepHigh').value.trim()||!Number.isFinite(low)||!Number.isFinite(high)||low>=high||low<f.min||high>f.max)throw Error(`시작값 < 끝값이며 ${f.min}–${f.max} ${f.unit} 범위여야 합니다.`);
      const first=Math.ceil((low-f.min)/f.step-1e-10),last=Math.floor((high-f.min)/f.step+1e-10);if(last<=first)throw Error('입력 간격에 맞는 조건이 2개 이상 포함되도록 범위를 넓혀 주세요.');const values=[...new Set(Array.from({length:5},(_,i)=>Number((f.min+Math.round(first+(last-first)*i/4)*f.step).toPrecision(12))))];if(values.length<2)throw Error('서로 다른 조건이 2개 이상 나오도록 범위를 넓혀 주세요.');
      const recipe=readRecipe(),fault=$('#faultSelect').value,input=state.selected<current().cursor?at(entry(),state.selected):current();
      const rows=values.map(value=>{const p=E.recipeFor(step,{...recipe,[key]:value}),r=E.process(input,step,p,1,fault);return {value,recipe:p,measure:sweepMeasure(step,r),metrics:r.metrics,warnings:r.warnings,seconds:r.seconds};});
      state.sweep={schema:'waferflow-fab-sweep-v1',modelVersion:E.VERSION,generatedAt:new Date().toISOString(),waferId:state.active,stepId:step.id,field:key,fieldLabel:f.label,unit:f.unit,baseRecipe:recipe,fault,inputHistory:E.copy(input.records),rows,notice:'동일 입력에서 재계산한 미보정 모델 비교입니다. 실측 통계나 실행 기록이 아닙니다.'};drawSweep();$('#sweepHint').textContent=rows.length+'개 조건을 동일한 입력 웨이퍼로 계산했습니다.';
    }catch(e){$('#sweepHint').textContent=e.message;}
  }
  function drawSweep(){const s=state.sweep;if(!s)return;const rows=s.rows,values=rows.map(r=>r.measure.value),lo=Math.min(...values),hi=Math.max(...values),span=hi-lo||Math.max(Math.abs(hi)*.1,1),y=v=>108-(v-lo)/span*76,x=i=>52+i/(rows.length-1)*566;const label=rows[0].measure,chartNumber=v=>Math.abs(v)>=1e6||(Math.abs(v)>0&&Math.abs(v)<.001)?v.toExponential(2):fmt(v,3);
    $('#sweepResults').innerHTML=`<div class="sweep-result-title"><strong>${esc(label.label)} <small>${esc(label.unit)}</small></strong><button id="exportSweep" class="text-button">실험 조건·결과 JSON ↓</button></div><svg class="sweep-chart" viewBox="0 0 680 145" role="img" aria-label="${esc(s.fieldLabel)}에 따른 ${esc(label.label)} 비교"><path d="M52,25V110H630" fill="none" stroke="#cad8d3"/><text x="44" y="33" text-anchor="end" font-size="9" fill="#839990">${esc(chartNumber(hi))}</text><text x="44" y="112" text-anchor="end" font-size="9" fill="#839990">${esc(chartNumber(lo))}</text><polyline points="${rows.map((r,i)=>x(i)+','+y(r.measure.value)).join(' ')}" fill="none" stroke="#357d62" stroke-width="2"/>${rows.map((r,i)=>`<circle cx="${x(i)}" cy="${y(r.measure.value)}" r="4" fill="${r.warnings.length?'#b97e42':'#357d62'}"/><text x="${x(i)}" y="134" text-anchor="middle" font-size="9" fill="#82948d">${esc(chartNumber(r.value))}</text>`).join('')}</svg><p class="compare-note">${esc(s.waferId)} · ${s.stepId} 직전 상태 기준 / ${esc(s.fieldLabel)} (${esc(s.unit)}). 경고가 있는 조건은 주황색입니다.</p><div class="table-wrap"><table><thead><tr><th>${esc(s.fieldLabel)}</th><th>${esc(label.label)}</th><th>표면 단차</th><th>모델 경고</th><th>조건 적용</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td class="mono">${fmt(r.value,3)} ${esc(s.unit)}</td><td class="mono">${fmt(r.measure.value,4)} ${esc(label.unit)}</td><td class="mono">${fmt(r.metrics.topography)} nm</td><td>${r.warnings.map(w=>esc(w.code)).join(', ')||'없음'}</td><td><button class="history-link" data-sweep-row="${i}">이 조건 불러오기 →</button></td></tr>`).join('')}</tbody></table></div><p class="compare-note">실행 결과를 남기려면 조건을 불러온 뒤 공정을 실행하세요. 스윕 결과는 임시 표시되며 JSON으로 별도 보관할 수 있습니다.</p>`;
  }
  function clearPreview(){if(!state.preview)return;state.preview=null;state.before=false;chooseDisplay();draw();}
  function previewRecipe(){if(state.busy||state.running||state.selected>current().cursor)return;try{const step=E.route[state.selected],p=readRecipe(),input=state.selected<current().cursor?at(entry(),state.selected):current();const result=E.process(input,step,p,1,$('#faultSelect').value);state.preview=result;before=input;shown=result.wafer;state.before=false;state.feedback=result.warnings.map(w=>w.message).join(' ');state.error=!!result.warnings.length;syncControls();draw();notify('조건을 미리 계산했습니다. 실행 기록은 그대로 유지됩니다.');}catch(e){clearPreview();state.feedback=e.message;state.error=true;syncControls();}}
  function rememberRecipe(){clearPreview();try{const p=readRecipe();entry().overrides[E.route[state.selected].id]=p;$('#recipeDuration').textContent=time(E.duration(E.route[state.selected],p));$('#recipeState').textContent='MODIFIED';state.feedback='';state.error=false;persist();}catch(e){state.feedback=e.message;state.error=true;}syncControls();}
  function hold(error){state.feedback=error.message;state.error=true;const id=E.route[current().cursor]?.id||'END';entry().events.push({stepId:id,message:error.message,time:new Date().toISOString()});entry().events=entry().events.slice(-200);state.running=null;state.busy=false;$('#autoRun').checked=false;persist();syncControls();renderHistory();notify(error.message);}
  function start(){
    if(state.busy)return;
    if(state.running&&!state.running.paused){state.running.paused=true;syncControls();draw();return;}
    if(state.selected>current().cursor)return;
    try{
      const step=E.route[state.selected],p=readRecipe(),fault=$('#faultSelect').value;
      if(state.running&&!recipeChanged(state.running.recipe,state.running.fault)){state.running.paused=false;syncControls();draw();return;}
      // Validate against the actual pre-process wafer before creating a branch or restarting.
      const source=state.selected<current().cursor?at(entry(),state.selected):current();E.interlocks(source,step,p,fault);
      if(state.selected<current().cursor){if(state.wafers.length>=25)throw Error('웨이퍼 25개 한도에 도달하여 새 실험을 만들 수 없습니다.');entry().overrides[step.id]=p;entry().conditions[step.id]=fault;addWafer(true);}
      const restarting=!!state.running;state.preview=null;entry().overrides[step.id]=p;entry().conditions[step.id]=fault;before=current();shown=current();state.before=false;state.feedback='';state.error=false;
      state.running={step,recipe:p,fault,before:current(),elapsed:0,paused:false,phase:'load',phaseProgress:0,warnings:[]};state.lastDraw=0;setPhase('load',0,0);persist();syncControls();draw();
      if(restarting)notify('변경한 조건으로 현재 공정을 처음부터 다시 시작합니다.');
    }catch(e){if(state.running?.paused){state.feedback=e.message;state.error=true;syncControls();}else hold(e);$('#recipeFields [aria-invalid="true"]')?.focus();}
  }
  function cancelRun(){if(state.busy){state.stopAdvance=true;$('#cancelRunButton').disabled=true;$('#runFeedback').textContent='현재까지 완료한 공정을 보존하고 계산을 중단합니다.';return;}if(!state.running)return;state.running=null;state.preview=null;state.before=false;state.feedback='';state.error=false;$('#autoRun').checked=false;persist();render();notify('현재 실행을 취소했습니다. 완료된 공정 기록과 수정한 조건은 유지됩니다.');}
  function setPhase(phase,fraction,total){
    $$('[data-phase]').forEach(el=>el.classList.toggle('active',el.dataset.phase===phase));$('#phaseProgress').style.width=(total*100)+'%';
    const tool=E.route[state.selected].tool,scan=root.FabViewport.stageMotion?.(fraction),actions={clean:'처리액 세정',oxidation:'산화막 성장',lpcvd:'저압 반응 · 박막 증착',pecvd:'플라즈마 보조 증착',coat:'PR 공급 · 스핀 코팅',bake:'핫플레이트 가열',scanner:scan?.contact>.01?'스테이지 정지 · 노광':'다음 노광 위치로 이동',developer:'현상액 처리 · PR 개구',etch:'플라즈마 식각',strip:'산소 플라즈마 · PR 제거',wetetch:'표적 막 선택 제거',implant:'이온 빔 주입',rtp:'가열 · 열처리 유지',cmp:'패드 회전 · 표면 연마',pvd:'타깃 스퍼터링 · 금속 증착',ald:'전구체 공급 · 퍼지 반복',metrology:scan?.contact>.01?'스테이지 정지 · 계측':'다음 계측 위치로 이동',probe:scan?.contact>.01?'프로브 접촉 · 구조 확인':'프로브 상승 · 다음 위치 이동'};
    const text=phase==='load'?(fraction<.18?'웨이퍼 들어올림':fraction<.82?'처리 위치로 이동':'웨이퍼 안착'):phase==='condition'?(fraction<.5?'이송 로봇 복귀':'장비 조건 형성'):phase==='process'?actions[tool]:phase==='unload'?(fraction<.22?'반출 준비 · 로봇 접근':'웨이퍼 회수 · 로드 포트 이동'):state.preview?'조건 미리 계산 · 실행 전':state.selected<current().cursor?'공정 완료 · 원본 결과 보기':'웨이퍼 반입 대기';
    $('#motionAction').textContent=(state.running?.paused?'일시정지 · ':'')+text;$('#motionPercent').textContent=state.running?Math.round(total*100)+'%':state.preview?'PREVIEW':state.selected<current().cursor?'COMPLETE':'READY';
    const processFraction=phase==='process'?fraction:phase==='unload'?1:0,seconds=current().virtualSeconds+(state.running?E.duration(state.running.step,state.running.recipe)*processFraction:0);$('#virtualTime').textContent='누적 처리 시간 '+time(seconds);
  }
  function frame(now){requestAnimationFrame(frame);const dt=Math.min(.1,Math.max(0,(now-state.lastFrame)/1000));state.lastFrame=now;const run=state.running;if(!run||run.paused||document.hidden)return;run.elapsed+=dt*Number($('#speedSelect').value||1);const total=Math.min(1,run.elapsed/6),p=total<.15?['load',total/.15]:total<.28?['condition',(total-.15)/.13]:total<.88?['process',(total-.28)/.6]:['unload',(total-.88)/.12];run.phase=p[0];run.phaseProgress=p[1];setPhase(p[0],p[1],total);updateViewport();
    if(now-state.lastDraw>100||total===1){const fraction=total<.28?0:Math.min(1,(total-.28)/.6);try{const result=fraction===0?null:E.process(run.before,run.step,run.recipe,fraction,run.fault);shown=result?.wafer||run.before;run.warnings=result?.warnings||[];draw();state.lastDraw=now;}catch(e){hold(e);return;}}
    if(total===1){try{const result=E.execute(run.before,run.recipe,run.fault);entry().wafer=result.wafer;state.running=null;replayCache.clear();const auto=$('#autoRun').checked&&!result.warnings.length&&current().cursor<E.route.length;if(result.warnings.length){state.feedback=result.warnings.map(w=>w.message).join(' ');state.error=true;$('#autoRun').checked=false;}if(auto)state.selected=current().cursor;state.expanded.add(E.route[state.selected].module);persist();render();if(auto)start();else notify(result.warnings.length?'공정 완료 · 경고를 확인하세요.':current().cursor===E.route.length?'117개 CMOS 기준 공정을 완료했습니다.':'공정 완료 · 조건과 구조가 기록되었습니다.');}catch(e){hold(e);}}
  }
  async function advance(){
    if(state.running||state.busy||state.selected<=current().cursor)return;
    const target=state.selected;state.busy=true;state.stopAdvance=false;state.error=false;state.feedback='저장된 초안 또는 기준 조건으로 앞 공정을 계산합니다.';syncControls();
    try{
      while(current().cursor<target&&!state.stopAdvance){
        const step=E.route[current().cursor],result=E.execute(current(),entry().overrides[step.id],entry().conditions[step.id]||'none');entry().wafer=result.wafer;
        if(result.warnings.length){state.selected=step.index;state.feedback=result.warnings.map(w=>w.message).join(' ');state.error=true;break;}
        if(current().cursor%5===0){
          persist();$('#runFeedback').textContent=current().cursor+' / '+target+' 공정 계산 중';$('#waferProgress').textContent=current().cursor+' / '+E.route.length+' 완료';$('#progressPercent').textContent=Math.round(current().cursor/E.route.length*100)+'%';$('#routeProgressBar').style.width=current().cursor/E.route.length*100+'%';
          await new Promise(resolve=>setTimeout(resolve,0));
        }
      }
      if(state.stopAdvance){state.selected=Math.min(current().cursor,E.route.length-1);state.feedback='계산을 중단했습니다. '+current().cursor+'개 완료 기록은 유지됩니다.';$('#autoRun').checked=false;}
      else if(current().cursor===target){state.feedback='앞 공정 계산 완료. 현재 조건으로 선택 공정을 실행하세요.';state.error=false;}
      state.busy=false;state.stopAdvance=false;replayCache.clear();state.expanded.add(E.route[state.selected].module);persist();render();
    }catch(e){state.stopAdvance=false;state.selected=Math.min(current().cursor,E.route.length-1);hold(e);render();}
  }
  function nextId(){let n=1;while(state.wafers.some(w=>w.id==='W'+String(n).padStart(2,'0')))n++;return 'W'+String(n).padStart(2,'0');}
  function addWafer(fork=false){if(state.running||state.busy||state.wafers.length>=25)return;const old=entry(),id=nextId(),point=state.selected,records=fork?old.wafer.records.slice(0,point):[];const e=makeEntry(id,records,fork?E.copy(old.overrides):{},fork?E.copy(old.conditions):{},fork?{id:old.id,from:point}:null);if(fork){e.title=old.title?(old.title+' · 분기').slice(0,60):'';e.note=old.note;for(const r of old.wafer.records.slice(point)){e.overrides[r.stepId]??=E.copy(r.recipe);e.conditions[r.stepId]??=r.fault;}}state.wafers.push(e);state.active=id;if(fork)state.compare=old.id;state.compareCount=null;state.selected=fork?point:0;state.feedback='';state.error=false;state.before=false;state.expanded.add(E.route[state.selected].module);persist();render();notify(fork?`${old.id}의 원본 기록을 보존하고 ${id}에서 분기했습니다.`:`새 웨이퍼 ${id}를 생성했습니다.`);}
  function download(name,type,content){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function exportCSV(){const cell=v=>'"'+String(v??'').replace(/^(?=[\t\r\n]|[^\S\r\n]*[=+@-])/,"'").replace(/"/g,'""')+'"';const rows=[['wafer','operation','name','recipe_json','fault','duration_s','topography_nm','poly_width_nm','activation_pct','warning_codes','model_version','executed_at','experiment_title','experiment_note']];for(const w of state.wafers)for(const r of w.wafer.records)rows.push([w.id,r.stepId,r.name,JSON.stringify(r.recipe),r.fault,r.seconds,r.metrics.topography,r.metrics.gateCD,r.metrics.activation,r.warnings.map(a=>a.code).join('|'),r.modelVersion,r.time,w.title,w.note]);download('waferflow-fab-history.csv','text/csv;charset=utf-8','\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n'));}
  function exportReport(){
    const experiment=entry(),w=current(),m=E.summarize(w),created=new Date().toISOString(),warnings=w.records.flatMap(r=>r.warnings.map(a=>({step:r.stepId,...a}))),gateReady=w.cursor>E.route.find(s=>s.name==='폴리 게이트 패턴 식각').index;
    const number=n=>Math.abs(n)>=1e6?Number(n).toExponential(3):fmt(n,3),title=experiment.title||'CMOS 공정 실험 '+experiment.id;
    const rows=w.records.map(r=>{const fields=E.tools[E.route[r.index].tool].fields;return `<tr><td><b>${r.stepId}</b><br>${esc(r.name)}</td><td>${Object.entries(r.recipe).map(([k,v])=>`${esc(fields[k].label)}: ${number(v)} ${esc(fields[k].unit)}`).join('<br>')}</td><td>${time(r.seconds)}</td><td>${fmt(r.metrics.topography)} nm</td><td>${r.warnings.length?r.warnings.map(a=>esc(a.code)).join('<br>'):'완료'}${r.fault!=='none'?'<br>이상 조건: '+esc(r.fault):''}</td><td>${esc(r.time)}</td></tr>`;}).join('');
    const profile=w.columns.map((c,i)=>({x_nm:(i+.5)*E.WIDTH/E.NX,reference_nm:0,current_nm:E.height(c)})),chart=compareChart({profile,reference:{waferId:'입고 표면'},current:{waferId:w.id}});
    const report=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · WaferFlow</title><style>
      *{box-sizing:border-box}body{margin:0;background:#edf2ef;color:#263f35;font:14px/1.75 system-ui,sans-serif}main{max-width:1080px;margin:35px auto;background:white;padding:45px 50px;border:1px solid #dbe6de}h1{font-size:30px;line-height:1.4;margin:8px 0 12px;overflow-wrap:anywhere}h2{font-size:17px;margin:30px 0 12px;border-bottom:1px solid #dbe5de;padding-bottom:8px}.brand{color:#628a73;letter-spacing:2px;font-size:12px}.meta,.note{font-size:12px;color:#708278}.scope{padding:14px 18px;background:#f0f5f0;border-left:3px solid #749e7b}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.cards article{border:1px solid #dbe6df;border-radius:6px;padding:14px}.cards small{display:block;color:#819289;font-size:11px}.cards strong{font-size:23px;font-weight:600}.memo{white-space:pre-wrap;overflow-wrap:anywhere;background:#f7f9f7;padding:17px;border-radius:5px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{text-align:left;padding:10px 9px;border-bottom:1px solid #e4ebe6;vertical-align:top}th{background:#edf4ef;font-weight:600}td:last-child{overflow-wrap:anywhere}.table-wrap{overflow-x:auto}.compare-chart{width:100%;height:220px;background:#f8fbf9;margin-top:12px}.compare-chart text{font:9px monospace;fill:#799084}.legend{display:flex;gap:20px;color:#769084;font-size:11px}.legend span:first-child{color:#9c8cc3}.legend span:last-child{color:#197766}footer{margin-top:30px;padding-top:15px;border-top:1px solid #dbe5de;font-size:11px;color:#87988d}.warning{color:#9c6548}.history td:first-child{min-width:130px}.history td:nth-child(2){min-width:155px}.history td:last-child{font-size:9px;color:#8a9a91;max-width:135px}@media(max-width:680px){main{margin:0;padding:22px 18px;border:0}.cards{grid-template-columns:repeat(2,1fr)}h1{font-size:24px}}@media print{body{background:white}main{margin:0;max-width:none;padding:0;border:0}.table-wrap{overflow:visible}tr,.cards article,.scope{break-inside:avoid}thead{display:table-header-group}h2{break-after:avoid}a{color:inherit}.compare-chart{height:180px}@page{size:A4;margin:16mm}}
      </style></head><body><main><div class="brand">WAFERFLOW / EXPERIMENT REPORT</div><h1>${esc(title)}</h1><p class="meta">웨이퍼 ${esc(w.id)} · 모델 ${E.VERSION} · 내보낸 시각 ${created}</p><p class="scope">공개 원리를 축약한 미보정 기하 모델의 실험 기록입니다. 실측 데이터, 양산 레시피 검증, 전기 수율 또는 승인 증빙이 아닙니다. 완료된 공정만 포함하며 미실행 초안과 진행 중 계산은 제외합니다.</p><div class="cards"><article><small>완료한 공정</small><strong>${w.cursor} / ${E.route.length}</strong></article><article><small>모델 누적 처리 시간</small><strong>${time(w.virtualSeconds)}</strong></article><article><small>표면 최대–최소 단차</small><strong>${fmt(m.topography)} nm</strong></article><article><small>폴리 게이트 평균 폭</small><strong>${gateReady?fmt(m.gateCD):'—'} nm</strong></article></div>
      <h2>실험 맥락</h2><p>${experiment.parent?`${esc(experiment.parent.id)}의 ${E.route[experiment.parent.from].id} 직전 상태에서 분기한 실험입니다.`:'입고 Si 웨이퍼에서 시작한 독립 실험입니다.'}</p><div class="memo">${esc(experiment.note||'작성된 실험 메모가 없습니다.')}</div>
      <h2>최종 완료 상태의 구조</h2><p class="note">${w.cursor?E.route[w.cursor-1].id+' · '+esc(E.route[w.cursor-1].name)+' 완료 후':'입고 상태'} · 4.8 µm 대표 단면 / 가로 30 nm 격자. 세로축은 별도 배율입니다.</p><div class="legend"><span>점선 · 입고 Si 표면</span><span>실선 · 현재 표면</span></div>${chart}<div class="table-wrap"><table><thead><tr><th>재료</th><th>160개 위치 평균 두께</th><th>최대 두께</th></tr></thead><tbody>${Object.entries(m.films).filter(([,v])=>v.max>0).map(([material,v])=>`<tr><td>${material}</td><td>${fmt(v.mean)} nm</td><td>${fmt(v.max)} nm</td></tr>`).join('')}</tbody></table></div><p class="note">활성 비율 ${fmt(m.activation)}%는 ${m.implants}개 주입 이력의 모델 활성화 계수 평균입니다. 계측 정확도나 전기 성능을 의미하지 않습니다.</p>
      <h2>완료 공정의 경고 · ${warnings.length}건</h2>${warnings.length?'<ul class="warning">'+warnings.map(a=>`<li>${a.step} · ${esc(a.code)} — ${esc(a.message)}</li>`).join('')+'</ul>':'<p class="note">완료한 공정에서 모델 경고가 발생하지 않았습니다. 제조 적합 판정을 뜻하지 않습니다.</p>'}
      <h2>실행 조건과 결과 · ${w.cursor}개 공정</h2>${w.records.length?`<div class="table-wrap"><table class="history"><thead><tr><th>공정</th><th>실행 레시피</th><th>처리 시간</th><th>단차</th><th>기록 상태</th><th>실행 시각 (UTC)</th></tr></thead><tbody>${rows}</tbody></table></div>`:'<p class="note">완료된 공정이 없습니다.</p>'}
      <footer>독립 HTML 리포트 · 인터넷 연결 없이 열람하고 브라우저 인쇄로 PDF를 만들 수 있습니다. 복원 가능한 원본은 시뮬레이터의 ‘JSON 내보내기’로 함께 보관하세요. 이 문서는 로컬 실험 기록이며 편집할 수 있습니다.</footer></main></body></html>`;
    download('waferflow-report-'+w.id+'.html','text/html;charset=utf-8',report);notify('완료 기록을 기준으로 독립 실험 리포트를 내보냈습니다.');
  }
  function importData(data){if(state.running||state.busy)throw Error('공정 실행을 완료한 뒤 기록을 불러오세요.');const incoming=decode(data);if(incoming.length+state.wafers.length>25)throw Error('현재 기록과 합쳐 최대 25개 웨이퍼까지 지원합니다.');const taken=new Set(state.wafers.map(w=>w.id)),map=new Map();for(const w of incoming){let id=w.id,n=1;while(taken.has(id)){id='IMPORT'+String(n++).padStart(2,'0');}taken.add(id);map.set(w.id,id);}for(const w of incoming){const old=w.id;w.id=map.get(old);w.wafer.id=w.id;if(w.parent&&map.has(w.parent.id))w.parent.id=map.get(w.parent.id);}state.wafers.push(...incoming);state.active=incoming[0].id;state.selected=Math.min(current().cursor,E.route.length-1);state.expanded.add(E.route[state.selected].module);state.feedback='';state.error=false;state.before=false;persist();render();notify('기록을 재계산해 복원했습니다. 기존 웨이퍼는 보존했습니다.');}
  $('#routeList').addEventListener('click',e=>{const module=e.target.closest('[data-module]'),step=e.target.closest('[data-step]');if(module){const id=module.dataset.module;state.expanded.has(id)?state.expanded.delete(id):state.expanded.add(id);renderRoute();}if(step)select(Number(step.dataset.step));});$('#routeSearch').addEventListener('input',renderRoute);$('#waferSelect').addEventListener('change',e=>{if(state.running||state.busy)return;state.active=e.target.value;state.selected=Math.min(current().cursor,E.route.length-1);state.expanded.add(E.route[state.selected].module);state.before=false;state.feedback='';state.error=false;persist();render();});
  $('#recipeForm').addEventListener('submit',e=>e.preventDefault());$('#recipeFields').addEventListener('input',rememberRecipe);$('#defaultsButton').addEventListener('click',()=>{clearPreview();const step=E.route[state.selected];entry().overrides[step.id]=E.recipeFor(step);state.feedback='';state.error=false;persist();renderRecipe();});$('#restoreRecordButton').addEventListener('click',()=>{clearPreview();const r=current().records[state.selected];if(!r)return;entry().overrides[r.stepId]=E.copy(r.recipe);entry().conditions[r.stepId]=r.fault;state.feedback='';state.error=false;persist();renderRecipe();});$('#faultSelect').addEventListener('change',()=>{clearPreview();entry().conditions[E.route[state.selected].id]=$('#faultSelect').value;state.feedback='';state.error=false;persist();syncControls();});$('#cancelRunButton').addEventListener('click',cancelRun);$('#previewButton').addEventListener('click',previewRecipe);$('#runButton').addEventListener('click',start);$('#nextButton').addEventListener('click',()=>select(current().cursor));$('#advanceButton').addEventListener('click',advance);$('#forkButton').addEventListener('click',()=>addWafer(true));$('#newWafer').addEventListener('click',()=>addWafer());
  $$('[data-camera]').forEach(b=>b.addEventListener('click',()=>{view.camera(b.dataset.camera);$$('[data-camera]').forEach(x=>x.classList.toggle('active',x===b));}));$('#partButtons').addEventListener('click',e=>{const b=e.target.closest('[data-part]');if(b){view.camera(Number(b.dataset.part));$('#equipmentCaption').textContent=view.parts()[Number(b.dataset.part)].name;$$('[data-camera]').forEach(x=>x.classList.remove('active'));}});$('#cutaway').addEventListener('change',()=>view.cutaway($('#cutaway').checked));$('#beforeButton').addEventListener('click',()=>{state.before=!state.before;draw();});for(const id of ['dopingToggle','maskToggle'])$('#'+id).addEventListener('change',draw);
  $('#crossSection').addEventListener('click',e=>{const bounds=$('#crossSection').getBoundingClientRect();const x=(e.clientX-bounds.left)/bounds.width*820;state.probe=Math.max(0,Math.min(E.NX-1,Math.floor((x-46)/(820-46-12)*E.NX)));draw();});$('#crossSection').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();state.probe=Math.max(0,Math.min(E.NX-1,state.probe+(e.key==='ArrowLeft'?-1:1)));draw();});
  function activateTab(name,focus=false){
    state.tab=name;$$('[data-tab]').forEach(b=>{const active=b.dataset.tab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active&&focus)b.focus();});
    for(const tab of ['metrics','history','sweep','compare'])$('#'+tab+'Panel').hidden=tab!==name;
    if(name==='compare')renderCompare();if(name==='sweep')renderSweep();
  }
  $$('[data-tab]').forEach(b=>{b.addEventListener('click',()=>activateTab(b.dataset.tab));b.addEventListener('keydown',e=>{const names=['metrics','history','sweep','compare'],index=names.indexOf(b.dataset.tab);let next;if(e.key==='ArrowRight')next=(index+1)%names.length;else if(e.key==='ArrowLeft')next=(index+names.length-1)%names.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=names.length-1;else return;e.preventDefault();activateTab(names[next],true);});});
  $('#jumpCurrent').addEventListener('click',()=>{$('#routeSearch').value='';select(Math.min(current().cursor,E.route.length-1));$('#routeList .selected')?.scrollIntoView?.({block:'nearest'});});
  $('#historyPanel').addEventListener('click',e=>{const b=e.target.closest('[data-history]');if(b)select(Number(b.dataset.history));});$('#comparePanel').addEventListener('change',e=>{if(e.target.id==='compareSelect'){state.compare=e.target.value;state.compareCount=null;renderCompare();}else if(e.target.id==='compareOperation'){state.compareCount=e.target.value==='auto'?null:Number(e.target.value);renderCompare();}});$('#comparePanel').addEventListener('click',e=>{if(e.target.closest('#exportComparison')){const data=comparison();if(data)download('waferflow-comparison-'+(data.stepId||'incoming')+'.json','application/json',JSON.stringify(data,null,2));}});
  $('#sweepPanel').addEventListener('change',e=>{if(e.target.id==='sweepField')setSweepBounds();});$('#sweepPanel').addEventListener('click',e=>{if(e.target.closest('#sweepRun'))runSweep();if(e.target.closest('#exportSweep')&&state.sweep)download('waferflow-sweep-'+state.sweep.stepId+'.json','application/json',JSON.stringify(state.sweep,null,2));const b=e.target.closest('[data-sweep-row]');if(b&&state.sweep&&!state.running&&!state.busy){const r=state.sweep.rows[Number(b.dataset.sweepRow)];if(!r)return;clearPreview();entry().overrides[state.sweep.stepId]=E.copy(r.recipe);entry().conditions[state.sweep.stepId]=state.sweep.fault;state.feedback='';state.error=false;persist();renderRecipe();notify('비교한 조건을 레시피에 불러왔습니다. 실행하면 기록에 반영됩니다.');}});
  $('#exportButton').addEventListener('click',()=>download('waferflow-fab-'+new Date().toISOString().slice(0,10)+'.json','application/json',JSON.stringify(pack(),null,2)));$('#csvButton').addEventListener('click',exportCSV);$('#reportButton').addEventListener('click',exportReport);$('#importButton').addEventListener('click',()=>$('#importFile').click());$('#importFile').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>12*1024*1024)throw Error('12 MB 이하의 JSON 파일을 선택하세요.');importData(JSON.parse(await file.text()));}catch(err){notify('불러오기 실패: '+err.message);}finally{e.target.value='';}});
  $('#editExperiment').addEventListener('click',()=>{if(state.busy||state.running)return;$('#experimentContext').textContent=entry().id+(entry().parent?' · '+entry().parent.id+' / '+E.route[entry().parent.from].id+'에서 분기':' · 독립 웨이퍼');$('#experimentNameInput').value=entry().title;$('#experimentNoteInput').value=entry().note;$('#experimentDialog').showModal();$('#experimentNameInput').focus();});
  $('#experimentForm').addEventListener('submit',e=>{e.preventDefault();entry().title=$('#experimentNameInput').value.trim().slice(0,60);entry().note=$('#experimentNoteInput').value.trim().slice(0,2000);persist();renderRoute();renderCompare();$('#experimentDialog').close();notify('실험 이름과 메모를 저장했습니다.');});for(const id of ['closeExperiment','cancelExperiment'])$('#'+id).addEventListener('click',()=>$('#experimentDialog').close());
  $('#aboutButton').addEventListener('click',()=>$('#infoDialog').showModal());$('#closeInfo').addEventListener('click',()=>$('#infoDialog').close());$('#infoDialog').addEventListener('click',e=>{if(e.target===$('#infoDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
  $('#equipmentHelpButton').addEventListener('click',explainEquipment);$('#closeEquipmentDialog').addEventListener('click',()=>$('#equipmentDialog').close());$('#equipmentDialogDone').addEventListener('click',()=>$('#equipmentDialog').close());$('#equipmentDialog').addEventListener('click',e=>{const b=e.target.closest('[data-guide-part]');if(b){const i=Number(b.dataset.guidePart);$('#equipmentDialog').close();view.camera(i);$('#equipmentCaption').textContent=view.parts()[i].name;$$('[data-camera]').forEach(x=>x.classList.remove('active'));view.renderer?.domElement.focus();}else if(e.target===$('#equipmentDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running&&!state.running.paused){state.running.paused=true;syncControls();draw();notify('화면을 벗어나 공정을 일시정지했습니다. 계속 실행으로 재개하세요.');}});
  root.addEventListener('beforeunload',e=>{if(state.running||state.busy){e.preventDefault();e.returnValue='';}});view=root.FabViewport.mount($('#fabViewport'),{onInspect:explainEquipment,onContextLoss(){if(state.running){state.running.paused=true;syncControls();draw();}notify('3D 연결이 끊겨 일시정지했습니다. 복구 후 계속 실행할 수 있습니다.');}});render();requestAnimationFrame(frame);
  root.FabApp={snapshot:()=>E.copy(pack()),importData,select,advance,viewport:view};
})(window);
