(function(root){
  'use strict';
  const E=root.MemoryFab,V=root.MemoryFabView,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=x=>JSON.parse(JSON.stringify(x));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=(v,d=1)=>Number.isFinite(v)?v.toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
  const statuses={planned:'투입 전',processing:'가공 중',waiting:'대기·이송',completed:'완료',held:'후속 보류',blocked:'장비 미배정',running:'가공 중',idle:'대기 가능',excluded:'계획 제외'};
  const STORAGE='waferflow-memory-fab-v1';let result,baseline=null,comparisonReason='',selectedChamber='HAR-01',selectedLot='H-201',product='all',time=0,playing=false,speed=6,frame=0,lastClock=null,lastPaint=0,disposed=false,selectedRecord=null,drafts={},viewport=null,motion=false,motionTime=0,topCamera=false;
  const metrics={cd_nm:['CD','nm'],etch_depth_nm:['식각 깊이','nm'],etch_error_pct:['깊이 목표 편차','%'],film_nm:['마지막 형성막','nm'],film_error_pct:['막 목표 편차','%'],topography_nm:['단차','nm'],overlay_nm:['정렬 지표','nm'],warp_um:['휨 지표','µm'],alignment_um:['적층 정렬','µm'],fill_pct:['충진 지표','%'],particles:['파티클 지표','상대값'],thermal_index:['열 이력 지표','상대값'],implant_dose_cm2:['주입 도즈','cm⁻²'],implant_range_nm:['주입 깊이 지표','nm'],pr_nm:['PR 두께','nm'],measurement_sites:['표본 계획','sites']};
  const evidenceKeys={clean:['particles'],furnace:['thermal_index','warp_um'],implant:['implant_dose_cm2','implant_range_nm'],coat:['pr_nm'],scanner:['cd_nm','overlay_nm'],develop:['cd_nm'],etch:['etch_depth_nm','etch_error_pct','cd_nm'],har:['etch_depth_nm','etch_error_pct','cd_nm'],cvd:['film_nm','film_error_pct','warp_um'],ald:['film_nm','film_error_pct'],pvd:['film_nm','film_error_pct'],plate:['fill_pct'],cmp:['topography_nm'],metro:['etch_error_pct','topography_nm','measurement_sites'],inspect:['film_error_pct','topography_nm','measurement_sites'],probe:['cd_nm','measurement_sites'],grind:['warp_um'],dice:['particles'],bond:['alignment_um','warp_um'],mold:['warp_um'],final:['alignment_um','measurement_sites']};
  let startupNote='';try{const saved=localStorage.getItem(STORAGE);result=saved?E.importPlan(JSON.parse(saved)):E.run();if(saved)startupNote='이 브라우저에 저장한 팹 계획을 다시 계산했습니다.';}catch{result=E.run();startupNote='저장 계획을 읽지 못해 기준 예제를 열었습니다. 기존 저장값은 덮어쓰지 않았습니다.';}
  time=(result.events.find(e=>e.kind==='hold')?.t??Math.min(50,result.duration));selectedLot=result.events.find(e=>e.kind==='hold')?.lotId||result.lots[0].id;
  const badge=(status)=>`<span class="status ${esc(status)}">${esc(statuses[status]||status)}</span>`;
  function say(message,error=false){$('#feedback').textContent=message;$('#feedback').classList.toggle('error',error);}
  function save(){try{localStorage.setItem(STORAGE,JSON.stringify(E.exportPlan(result)));}catch{say('계산은 완료했습니다. 브라우저 저장 공간을 사용할 수 없어 계획을 저장하지 못했습니다. JSON으로 내보내세요.',true);}}
  function chamber(){return E.chambers.find(c=>c.id===selectedChamber);}
  function initMap(){
    $('#fabMap').innerHTML=E.bays.map((bay,i)=>`<article class="bay"><div class="bay-head"><b>${String(i+1).padStart(2,'0')}</b><div><strong>${bay.name}</strong><small>${bay.sub}</small></div></div><div class="bay-tools">${Object.entries(E.tools).filter(([,t])=>t.bay===bay.id).map(([type,t])=>`<div class="tool-group"><div class="tool-label">${t.name}<span aria-hidden="true">${['har','etch','ald','cvd','pvd'].includes(type)?'◉':['coat','cmp','grind'].includes(type)?'◎':'▱'}</span></div><div class="chamber-pair">${E.chambers.filter(c=>c.type===type).map(c=>`<button class="chamber" data-chamber="${c.id}" data-state="idle" aria-pressed="false" aria-label="${c.id} ${t.name}"><b>${c.id}</b><small>대기 가능</small><i class="fill"></i></button>`).join('')}</div></div>`).join('')}</div></article>`).join('');
    $('#fleetCount').textContent=`${Object.keys(E.tools).length} 장비군 · ${E.chambers.length} 가상 챔버`;
    $('#scenarioSelect').innerHTML=Object.entries(E.scenarios).map(([id,s])=>`<option value="${id}">${s.name}</option>`).join('');
    $('#modelVersion').textContent=E.VERSION+' / LOCAL SIMULATION';
  }
  function syncPlanControls(){$('#scenarioSelect').value=result.options.scenario;$('#scenarioDescription').textContent=E.scenarios[result.options.scenario].description;$('#holdGate').checked=result.options.holdAtGate;$('#timeSlider').max=String(result.duration);}
  function renderMap(snap){for(const c of snap.fleet){const el=$(`[data-chamber="${c.id}"]`),issue=snap.events.some(e=>e.chamber===c.id&&e.kind==='anomaly');el.dataset.state=c.status;el.dataset.issue=String(issue);el.setAttribute('aria-pressed',String(c.id===selectedChamber));el.querySelector('small').textContent=c.active?c.active.lotId:c.queue.length?`대기 ${c.queue.length} LOT`:statuses[c.status];el.querySelector('.fill').style.width=c.active?Math.max(0,Math.min(100,(time-c.active.start)/c.active.duration*100))+'%':'0%';el.title=`${c.id} · ${E.tools[c.type].name} · ${statuses[c.status]} · ${c.qualification}${c.queue.length?' · 대기 '+c.queue.join(', '):''}${issue?' · 관찰된 편차 있음':''}`;}}
  function renderLots(snap){
    const lots=snap.lots.filter(l=>product==='all'||l.product===product);$('#lotCount').textContent=lots.length+' LOT / 전체 '+snap.lots.length;
    $('#lotRows').innerHTML=lots.map(l=>{const total=E.products[l.product].route.length,r=l.current;return `<tr class="${l.id===selectedLot?'selected':''}"><td><button data-lot="${l.id}" aria-pressed="${l.id===selectedLot}">${l.id}</button><small>${E.products[l.product].name} · 투입 ${l.wafers} wafers</small></td><td>${l.status==='planned'?'투입 예정':r?esc(r.name):'사용 가능한 장비 없음'}<small>${r?esc(r.chamber):'—'}${l.status==='waiting'&&r?' · 다음 예약 '+num(r.start,1)+' 모형 분':''}</small></td><td><div class="lot-progress"><span class="progress-track"><i style="width:${l.completedOps/total*100}%"></i></span><span>${l.completedOps}/${total}</span></div></td><td>${badge(l.status)}</td></tr>`;}).join('');
  }
  function renderRoute(snap){
    const lot=snap.lots.find(l=>l.id===selectedLot)||snap.lots[0],route=E.products[lot.product].route,rows=result.records.filter(r=>r.lotId===lot.id),activeOp=lot.active?rows.find(r=>r.id===lot.active)?.operation:lot.completedOps,modules=[...new Set(route.map(r=>r.module))];
    $('#routeTitle').textContent=lot.id+' · '+E.products[lot.product].name;$('#routeState').className='status '+lot.status;$('#routeState').textContent=statuses[lot.status];$('#routeDescription').textContent=E.products[lot.product].description+' · '+route.length+'개 축약 모듈 공정';
    $('#routeModules').innerHTML=modules.map(id=>{const steps=route.map((op,i)=>({...op,i})).filter(op=>op.module===id),done=steps.filter(op=>op.i<lot.completedOps).length,here=steps.some(op=>op.i===activeOp)||lot.status==='held'&&steps.some(op=>op.i===lot.completedOps-1);return `<div class="module ${done===steps.length?'done':''} ${here?'current':''} ${here&&lot.status==='held'?'held':''}"><b>${E.modules[id]}</b><small>${done} / ${steps.length} 완료</small></div>`;}).join('');
    let start=$('#showAllOps').checked?0:Math.max(0,Math.min(route.length-6,activeOp-2)),end=$('#showAllOps').checked?route.length:Math.min(route.length,start+6);
    $('#routeHint').textContent=`${start+1}–${end} / ${route.length} 공정 · 항목을 누르면 완료 시점 확인`;
    $('#operationList').innerHTML=route.slice(start,end).map((op,offset)=>{const i=start+offset,r=rows.find(row=>row.operation===i),done=r&&r.end<=time,phase=done?(r.gateFailed&&result.options.holdAtGate?'held':'done'):r&&r.start<=time?'active':'future',label=phase==='done'?'완료':phase==='held'?'보류':phase==='active'?'가공 중':r?'예정':'미실행';return `<button class="operation ${selectedRecord===r?.id?'selected':''}" data-operation="${i}" data-phase="${phase}" ${!r?'disabled':''}><span>${String(i+1).padStart(2,'0')}</span><span><b>${esc(op.name)}${op.gate?' · GATE':''}</b><small>${E.tools[op.tool].name}${r?' / '+num(r.start)+'–'+num(r.end)+' 모형 분':''}</small></span><span class="operation-chamber">${r?r.chamber:'미배정'}</span><span>${label}</span></button>`;}).join('');
    const values=[['현재 CD',lot.state.cd_nm,'nm'],['마지막 식각 깊이',lot.state.etch_depth_nm,'nm'],['현재 단차',lot.state.topography_nm,'nm'],['현재 휨',lot.state.warp_um,'µm']];
    $('#stateMetrics').innerHTML=values.map(([label,value,unit])=>`<div><span>${label}</span><b>${num(value)} <small>${unit}</small></b></div>`).join('');
    const evidence=rows.filter(r=>r.end<=time).at(-1);$('#operationEvidence').innerHTML=evidence?`<div class="evidence-title"><b>최근 완료 공정의 수치 근거</b><span>${esc(evidence.name)} · ${evidence.chamber}</span></div><table><thead><tr><th>구조 지표</th><th>공정 전</th><th>공정 후</th><th>단위</th></tr></thead><tbody>${evidenceKeys[evidence.tool].map(key=>`<tr><td>${metrics[key][0]}</td><td>${num(evidence.before[key])}</td><td>${num(evidence.after[key])}</td><td>${metrics[key][1]}</td></tr>`).join('')}</tbody></table><p>합성 구조 상태 · 실제 센서값 아님${evidence.recipe.sites?' · 표본 수는 계획 정보':''}</p>`:'<p class="empty">첫 공정이 완료되면 장비별 입력·출력 지표를 표시합니다.</p>';
    $('#lotIssues').innerHTML=lot.state.issues.length?`<b>${lot.state.issues.length}개 합성 규칙 편차 · ${lot.status==='held'?'후속 단계 미실행':'이력에 유지'}</b><br>${lot.state.issues.slice(-3).map(i=>`${esc(i.chamber)} → ${esc(i.originName)}: ${esc(i.reason)}`).join('<br>')}`:'';
  }
  function renderInspector(snap,fields=false){
    const c=snap.fleet.find(c=>c.id===selectedChamber),t=E.tools[c.type];if($('#evidenceLink'))$('#evidenceLink').href='evidence.html'+(['har','cvd','cmp'].includes(c.type)?'?profile='+c.type:'');$('#chamberTitle').textContent=c.id;$('#chamberStatus').textContent=statuses[c.status];$('#chamberStatus').className='status '+c.status;$('#toolName').textContent=t.name+' / '+t.en;$('#toolRole').textContent=t.role;$('#toolWatch').textContent=t.watch;
    const completed=result.records.filter(r=>r.chamber===c.id&&r.end<=time),last=completed.at(-1);
    $('#chamberNow').innerHTML=c.active?`<strong>${c.active.lotId}</strong> · ${esc(c.active.name)}<br>대기 ${c.queue.length} LOT · 현재까지 가동 ${num(c.utilization*100,0)}%`:c.excluded?'현재 계획에서 제외된 챔버입니다.':`현재 가공 없음 · 경유 ${new Set(completed.map(r=>r.lotId)).size} LOT${last?'<br>최근 완료: '+esc(last.lotId)+' / '+esc(last.name):'<br>아직 완료된 공정이 없습니다.'}`;
    $('#chamberNow').innerHTML+=`<br><span class="qualification">장비 적합성: ${esc(c.qualification)}</span>`;$('#isolateButton').textContent=c.excluded?'이 챔버 복귀 후 전체 비교 ↗':'이 챔버 제외 후 전체 비교 ↗';$('#isolateButton').disabled=result.options.scenario==='down'&&c.id==='LIT-01';
    if(fields){$('#equipmentPreview').innerHTML=V.svg(c.type);const p=drafts[c.type]||E.recipe(c.type,result.options.overrides);$('#recipeFields').innerHTML=Object.entries(t.fields).map(([key,f])=>`<label class="recipe-field"><span>${f.label}<small>${f.unit}</small></span><input id="field-${key}" data-field="${key}" type="number" step="${['sites','cycles'].includes(key)?'1':'any'}" min="${f.min}" max="${f.max}" value="${esc(p[key])}" aria-label="${esc(f.label+' '+f.unit)}"><small class="range">예제 입력 범위 ${f.min.toLocaleString('en-US')}–${f.max.toLocaleString('en-US')} ${f.unit}${key==='sites'?' · 표본 계획만 기록':''}</small></label>`).join('');$('#recipeError').textContent='';$('#recipeBadge').textContent=drafts[c.type]?'미적용 초안':result.options.overrides[c.type]?'조건 변경됨':'기준값';}
  }
  function renderImpact(){const list=E.impact(result,selectedChamber,time);$('#impactCount').textContent=String(list.length);$('#impactList').innerHTML=list.length?list.map(l=>`<button class="impact-list-item ${l.causes.length?'has-cause':''}" data-impact-lot="${l.lotId}"><strong>${l.lotId}</strong><span>${E.products[l.product].name} · ${l.records.length}회 경유</span><small>${l.causes.length?l.causes.length+'개 편차 기원 · '+(l.held?'후속 보류':'하류 진행 이력 확인'):'이 챔버에 기원을 둔 규칙 편차 없음'}<br>이후 완료 ${l.downstream.length}개 · 잔여 ${l.plannedRemaining}개 공정</small></button>`).join(''):'<p class="empty">현재 시점까지 이 챔버에서 완료한 LOT이 없습니다. 시간을 이동하거나 다른 챔버를 선택하세요.</p>';}
  function renderEvents(snap){$('#eventList').innerHTML=snap.events.length?snap.events.slice().reverse().map(e=>`<button class="event" data-event-time="${e.t}" data-event-lot="${e.lotId}" data-event-chamber="${e.chamber||''}"><span>${num(e.t)}′</span><div><b>${e.lotId} · ${e.kind==='hold'?'후속 공정 보류':e.kind==='blocked'?'장비 미배정':e.chamber+' 편차'}</b><small>${esc(e.message)}</small></div></button>`).join(''):'<p class="empty">현재 시점까지 관찰된 이상·보류 이벤트가 없습니다.</p>';}
  function renderComparison(){
    $('#restoreBaseline').hidden=!baseline;if(!baseline){$('#comparison').innerHTML='<p class="empty">장비군 조건을 바꾸거나 챔버를 제외하면, 같은 투입 LOT의 전체 결과를 비교합니다.</p>';return;}
    const a=baseline.summary,b=result.summary,rows=[['완료 LOT',a.completed,b.completed],['보류 LOT',a.held,b.held],['장비 미배정 LOT',a.blocked,b.blocked],['LOT당 누적 대기',num(a.meanWait)+'′',num(b.meanWait)+'′'],['전체 계획 종료',num(a.duration)+'′',num(b.duration)+'′']];
    const sameInput=JSON.stringify(baseline.options.lots)===JSON.stringify(result.options.lots);$('#comparison').innerHTML=`<p class="comparison-caption">${esc(comparisonReason)}<br>${sameInput?'동일 '+a.lots+' LOT · 같은 투입 시각':a.lots+' → '+b.lots+' LOT · 투입 구성/시각 변경'} · 전체 종료 결과</p><table class="compare-table"><thead><tr><th>비교 지표</th><th>변경 전</th><th>변경 후</th></tr></thead><tbody>${rows.map(([label,a,b])=>`<tr><td>${label}</td><td>${a}</td><td>${b}</td></tr>`).join('')}</tbody></table><p class="compare-caveat">′ = 모형 분. 보류로 일찍 끝난 계획과 전체 경로를 완료한 계획의 종료시간은 작업량이 다릅니다. 실제 생산성·수율 개선 수치가 아닙니다.</p>`;
  }
  function render(fields=false){
    const snap=E.snapshot(result,time),s=snap.summary;$('#kpiLots').textContent=`${snap.lots.filter(l=>l.release<=time).length} / ${snap.lots.length}`;$('#kpiWafers').textContent=`투입 전 계획 ${result.summary.wafers} wafers · LOT 계보 유지`;$('#kpiWip').textContent=`${s.processing} / ${s.waiting}`;$('#kpiHeld').textContent=`${s.held} / ${s.blocked}`;$('#kpiDone').textContent=String(s.completed);
    const queues=result.fleet.map(c=>({id:c.id,wait:result.records.filter(r=>r.chamber===c.id&&r.ready<time).reduce((sum,r)=>sum+Math.max(0,Math.min(time,r.start)-r.ready),0)})).sort((a,b)=>b.wait-a.wait);$('#kpiBottleneck').textContent=queues[0]?.wait?queues[0].id:'—';$('#kpiQueue').textContent=queues[0]?.wait?num(queues[0].wait)+' 모형 분 · 누적 LOT 대기':'현재 시점까지 누적 대기 없음';
    $('#timeLabel').textContent=num(time);$('#timeSlider').value=String(time);$('#timeSlider').setAttribute('aria-valuetext',num(time)+' / '+num(result.duration)+' 모형 분');$('#playButton').textContent=playing?'Ⅱ':'▶';$('#playButton').setAttribute('aria-label',playing?'팹 흐름 일시정지':'팹 흐름 재생');
    renderMap(snap);renderLots(snap);renderRoute(snap);renderInspector(snap,fields);renderImpact();renderEvents(snap);
  }
  function pause(){playing=false;render();}
  function seek(value){time=Math.max(0,Math.min(result.duration,Number(value)||0));playing=false;render();}
  function selectChamber(id){if(!E.chambers.some(c=>c.id===id))return;selectedChamber=id;render(true);}
  function selectLot(id){const lot=result.lots.find(l=>l.id===id);if(!lot)return;selectedLot=id;selectedRecord=null;if(product!=='all'&&lot.product!==product)setProduct('all');render();}
  function setProduct(id){if(id!=='all'&&!E.products[id])return;product=id;$$('[data-product]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.product===id)));if(id!=='all'&&!result.lots.some(l=>l.id===selectedLot&&l.product===id))selectedLot=result.lots.find(l=>l.product===id)?.id||result.lots[0].id;render();}
  function applyPlan(options,reason,compare=true){
    try{const next=E.run(options);if(compare){baseline=result;comparisonReason=reason;}else{baseline=null;comparisonReason='';}result=next;drafts={};playing=false;selectedRecord=null;if(!result.lots.some(l=>l.id===selectedLot))selectedLot=result.lots[0].id;time=result.duration;syncPlanControls();render(true);renderComparison();say(reason+' · 팹 전체 경로를 다시 계산했습니다.');save();return true;}catch(e){say(e.message,true);return false;}
  }
  function applyRecipe(){
    const c=chamber(),p={},fields=E.tools[c.type].fields;let error='';for(const[key,f]of Object.entries(fields)){const el=$('#field-'+key),raw=el.value.trim(),value=Number(raw),valid=raw!==''&&Number.isFinite(value)&&value>=f.min&&value<=f.max&&(!['sites','cycles'].includes(key)||Number.isInteger(value));el.setAttribute('aria-invalid',String(!valid));if(!valid&&!error)error=f.label+' 입력 범위와 숫자를 확인하세요.';p[key]=value;}
    if(error){$('#recipeError').textContent=error;return false;}return applyPlan({...result.options,overrides:{...result.options.overrides,[c.type]:p}},E.tools[c.type].name+' 장비군 조건 변경');
  }
  function isolate(){const c=chamber();if(result.options.scenario==='down'&&c.id==='LIT-01')return false;const excluded=result.options.excluded.includes(c.id)?result.options.excluded.filter(id=>id!==c.id):[...result.options.excluded,c.id];return applyPlan({...result.options,excluded},c.id+(excluded.includes(c.id)?' 제외 / 대체 챔버 사용':' 복귀'));}
  function restore(){if(!baseline)return;const previous=baseline;result=previous;baseline=null;drafts={};playing=false;selectedLot=result.lots.some(l=>l.id===selectedLot)?selectedLot:result.lots[0].id;time=result.duration;syncPlanControls();render(true);renderComparison();say('변경 전 계획을 복원했습니다.');save();}
  function lotFormRow(l){return `<tr><td><input data-lot-field="id" value="${esc(l.id)}" aria-label="LOT ID" maxlength="40"></td><td><select data-lot-field="product" aria-label="LOT 제품">${Object.entries(E.products).map(([id,p])=>`<option value="${id}" ${id===l.product?'selected':''}>${p.name}</option>`).join('')}</select></td><td><input data-lot-field="wafers" type="number" value="${l.wafers}" min="1" max="25" step="1" aria-label="투입 웨이퍼 수"></td><td><input data-lot-field="release" type="number" value="${l.release}" min="0" max="200" step="any" aria-label="투입 시각 모형 분"></td><td><button type="button" data-remove-lot aria-label="이 LOT 삭제">✕</button></td></tr>`;}
  function openLots(){pause();$('#lotsEditor').innerHTML=result.options.lots.map(lotFormRow).join('');$('#lotsError').textContent='';$('#lotsDialog').showModal();}
  function applyLots(){try{const lots=$$('#lotsEditor tr').map(row=>{const get=key=>row.querySelector(`[data-lot-field="${key}"]`).value.trim(),release=get('release'),wafers=get('wafers');return{id:get('id'),product:get('product'),wafers:wafers===''?NaN:Number(wafers),release:release===''?NaN:Number(release)};});E.validate({...result.options,lots});if(applyPlan({...result.options,lots},'투입 LOT 계획 변경')){$('#lotsDialog').close();return true;}return false;}catch(e){$('#lotsError').textContent=e.message+' ID는 영문·숫자·밑줄·하이픈을 사용하며 중복될 수 없습니다.';return false;}}
  function jumpIncident(){const e=result.events.find(e=>e.kind==='hold')||result.events[0];if(!e){seek(result.duration);say('이 계획에는 보류·이상 이벤트가 없습니다. 전체 완료 결과를 표시합니다.');return;}selectedLot=e.lotId;const cause=result.lots.find(l=>l.id===e.lotId)?.state.issues[0];selectedChamber=cause?.chamber||e.chamber||selectedChamber;product='all';$$('[data-product]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.product==='all')));seek(e.t);render(true);say('첫 보류 시점입니다. 원인 챔버의 경유 LOT과 다음 계측 지점을 확인하세요.');}
  function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
  function reportHTML(){
    const r=result;return `<!doctype html><html lang="ko"><meta charset="utf-8"><title>WaferFlow 메모리 팹 검토</title><style>body{font:14px/1.8 sans-serif;max-width:1050px;margin:50px auto;color:#234}h1{font-size:27px}table{width:100%;border-collapse:collapse;margin:20px 0}td,th{border-bottom:1px solid #ccd;padding:10px;text-align:left;font-size:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f3f6f8;padding:20px;font-size:11px}.note{background:#edf6f5;padding:15px}small{color:#789}@media print{body{margin:20px}tr{break-inside:avoid}}</style><h1>메모리 팹 공정 통합 검토</h1><p>${esc(E.scenarios[r.options.scenario].name)} · ${esc(E.VERSION)}</p><p class="note">자체 생성 LOT·장비·레시피·규칙. SK하이닉스의 실측 데이터·내부 공정·장비 목록이 아닙니다. 미보정 LOT 단위 참조 모형이며 양산 판정·실장비 제어용이 아닙니다.</p><p>생성 시각 ${esc(new Date().toISOString())} / 보고 범위: 전체 계획 종료 결과 / 재생 화면 ${num(time)} 모형 분</p><h2>계획 결과</h2><p>${r.summary.lots} LOT · 완료 ${r.summary.completed} · 보류 ${r.summary.held} · 장비 미배정 ${r.summary.blocked} · 종료 ${num(r.duration)} 모형 분</p>${baseline?'<h2>변경 전후 비교</h2>'+$('#comparison').innerHTML:''}<h2>LOT 이력 요약</h2><table><thead><tr><th>LOT</th><th>제품</th><th>진행</th><th>상태</th><th>편차 기원</th></tr></thead><tbody>${r.lots.map(l=>`<tr><td>${esc(l.id)}</td><td>${E.products[l.product].name}</td><td>${l.records.length}/${E.products[l.product].route.length}</td><td>${statuses[l.status]}</td><td>${l.state.issues.map(i=>esc(i.chamber+' / '+i.originName)).join('<br>')||'없음'}</td></tr>`).join('')}</tbody></table><h2>모델 해석</h2><p>모형 시간은 실제 공정 시간·생산 능력이 아닙니다. 계측 표본 수는 계획 정보로만 기록하며 검출 확률을 계산하지 않습니다. HBM 후공정에서도 부모 LOT을 유지하고 개별 다이·스택 수량 전환은 생략합니다. 챔버 제외 비교는 같은 입력을 처음부터 다시 계산한 대안 계획입니다.</p><h2>재현 가능한 계획</h2><pre>${esc(JSON.stringify(E.exportPlan(r),null,2))}</pre>${baseline?'<h2>변경 전 계획</h2><pre>'+esc(JSON.stringify(E.exportPlan(baseline),null,2))+'</pre>':''}<h2>공정 이벤트</h2><table><thead><tr><th>모형 분</th><th>LOT / 챔버</th><th>관찰</th></tr></thead><tbody>${r.events.map(e=>`<tr><td>${num(e.t)}</td><td>${esc(e.lotId+' / '+(e.chamber||'미배정'))}</td><td>${esc(e.message)}</td></tr>`).join('')}</tbody></table><h2>공개 기술 근거</h2><p>SK하이닉스 공개 식각·패키징 자료와 Lam Research HBM 설명을 공정 역할에만 참고했습니다. 수치 계수와 장비 ID는 자체 생성입니다.</p>${$('#sourcesDialog .sources').outerHTML}<small>로컬 검토 리포트 · 서버 승인 기록이나 장비 투입 허가가 아닙니다.</small></html>`;
  }
  function importPlan(data){const next=E.importPlan(data);baseline=null;result=next;drafts={};playing=false;selectedLot=next.lots[0].id;product='all';selectedChamber=E.scenarios[next.options.scenario].tool||'CLN-01';time=next.duration;syncPlanControls();$$('[data-product]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.product==='all')));render(true);renderComparison();say('계획의 입력을 검증한 뒤 현재 모델로 재계산했습니다.');save();return true;}
  function closeEquipment(){motion=false;viewport?.dispose();viewport=null;$('#equipmentDialog').close();}
  function openEquipment(){
    pause();viewport?.dispose();const c=chamber(),t=E.tools[c.type];$('#equipmentDialogTitle').textContent=c.id+' · '+t.name;$('#equipmentExplanation').textContent=t.role+' 관찰 항목: '+t.watch;const rows=result.records.filter(r=>r.chamber===c.id&&r.end<=time),types=[...new Set(rows.map(r=>r.product))];$('#equipmentContext').innerHTML=`<div class="context-box"><b>팹 전체에서 이 장비의 역할</b><p>현재 시점까지 ${new Set(rows.map(r=>r.lotId)).size} LOT · ${rows.length}개 공정을 처리했습니다. ${types.map(id=>E.products[id].name).join(' · ')||'아직 완료 이력 없음'}</p><div class="mini-flow">${[...new Set(rows.map(r=>r.name))].slice(0,6).map(name=>'<span>'+esc(name)+'</span>').join('')}</div></div>`;$('#equipmentDialog').showModal();viewport=V.mount($('#equipmentViewport'),c.type);motion=false;motionTime=0;topCamera=false;viewport.update(0,false);$('#cameraButton').hidden=!viewport.is3D;$('#motionButton').textContent='▶ 원리 동작 재생';$('#equipmentPhase').textContent=viewport.is3D?'3D 기능 모형 · 반입 대기':'2D 기능 모형 · 반입 대기';
  }
  function tick(now){
    if(disposed)return;const dt=lastClock===null?0:Math.min(.1,Math.max(0,(now-lastClock)/1000));lastClock=now;
    if(playing){time=Math.min(result.duration,time+dt*speed);if(time>=result.duration)playing=false;if(now-lastPaint>180||!playing){render();lastPaint=now;}}
    if(motion&&viewport){motionTime=Math.min(1,motionTime+dt/12);viewport.update(motionTime,true);const phase=motionTime<.22?'웨이퍼 반입':motionTime<.34?'조건 형성':motionTime<.82?'대표 공정 작용':'웨이퍼 반출';$('#equipmentPhase').textContent=(viewport.is3D?'3D':'2D')+' 기능 모형 · '+phase+' '+num(motionTime*100,0)+'%';if(motionTime>=1){motion=false;viewport.update(1,false);$('#motionButton').textContent='↻ 다시 재생';}}
    frame=requestAnimationFrame(tick);
  }
  $('#fabMap').addEventListener('click',e=>{const b=e.target.closest('[data-chamber]');if(b)selectChamber(b.dataset.chamber);});
  $('#lotRows').addEventListener('click',e=>{const b=e.target.closest('[data-lot]');if(b)selectLot(b.dataset.lot);});
  $('#impactList').addEventListener('click',e=>{const b=e.target.closest('[data-impact-lot]');if(b)selectLot(b.dataset.impactLot);});
  $('#operationList').addEventListener('click',e=>{const b=e.target.closest('[data-operation]');if(!b)return;const row=result.records.find(r=>r.lotId===selectedLot&&r.operation===Number(b.dataset.operation));if(row){selectedRecord=row.id;selectedChamber=row.chamber;seek(row.end);render(true);}});
  $('#eventList').addEventListener('click',e=>{const b=e.target.closest('[data-event-time]');if(!b)return;selectedLot=b.dataset.eventLot;if(b.dataset.eventChamber)selectedChamber=b.dataset.eventChamber;seek(Number(b.dataset.eventTime));render(true);});
  $$('[data-product]').forEach(b=>b.addEventListener('click',()=>setProduct(b.dataset.product)));$('#showAllOps').addEventListener('change',()=>render());
  $('#runPlan').addEventListener('click',()=>applyPlan({...result.options,scenario:$('#scenarioSelect').value,holdAtGate:$('#holdGate').checked},E.scenarios[$('#scenarioSelect').value].name));
  $('#scenarioSelect').addEventListener('change',()=>{$('#scenarioDescription').textContent=E.scenarios[$('#scenarioSelect').value].description;say('시나리오 초안을 변경했습니다. ‘팹 전체 계산’을 누르면 적용됩니다.');});
  $('#holdGate').addEventListener('change',()=>say('보류 규칙 초안을 변경했습니다. ‘팹 전체 계산’을 누르면 적용됩니다.'));
  $('#resetPlan').addEventListener('click',()=>applyPlan({scenario:$('#scenarioSelect').value,lots:result.options.lots,holdAtGate:true},'장비 제외·조건을 초기화'));
  $('#playButton').addEventListener('click',()=>{if(time>=result.duration)time=0;playing=!playing;render();});$('#timeSlider').addEventListener('input',()=>seek(Number($('#timeSlider').value)));$('#speedSelect').addEventListener('change',()=>{speed=Number($('#speedSelect').value)||6;});$('#jumpIncident').addEventListener('click',jumpIncident);$('#jumpEnd').addEventListener('click',()=>seek(result.duration));
  $('#recipeFields').addEventListener('input',e=>{const key=e.target.dataset.field;if(!key)return;const type=chamber().type;drafts[type]||=E.recipe(type,result.options.overrides);drafts[type][key]=e.target.value;$('#recipeBadge').textContent='미적용 초안';$('#recipeError').textContent='';});
  $('#recipeForm').addEventListener('submit',e=>{e.preventDefault();applyRecipe();});$('#resetRecipe').addEventListener('click',()=>{const type=chamber().type,overrides=clone(result.options.overrides);delete overrides[type];applyPlan({...result.options,overrides},E.tools[type].name+' 기준 조건 복원');});$('#isolateButton').addEventListener('click',isolate);$('#restoreBaseline').addEventListener('click',restore);
  $('#exportButton').addEventListener('click',()=>{download('waferflow-memory-fab-plan.json',JSON.stringify(E.exportPlan(result),null,2),'application/json');say('현재 적용된 팹 계획을 저장했습니다. 미적용 초안은 포함하지 않습니다.');});$('#reportButton').addEventListener('click',()=>download('waferflow-memory-fab-review.html',reportHTML(),'text/html;charset=utf-8'));
  $('#editLots').addEventListener('click',openLots);$('#lotsForm').addEventListener('submit',e=>{e.preventDefault();applyLots();});$('#addLot').addEventListener('click',()=>{if($$('#lotsEditor tr').length>=40){$('#lotsError').textContent='최대 40 LOT까지 설정할 수 있습니다.';return;}const ids=$$('[data-lot-field="id"]').map(el=>el.value);let n=1;while(ids.includes('LOT-'+String(n).padStart(3,'0')))n++;$('#lotsEditor').insertAdjacentHTML('beforeend',lotFormRow({id:'LOT-'+String(n).padStart(3,'0'),product:'hbm',wafers:25,release:0}));});$('#lotsEditor').addEventListener('click',e=>{const b=e.target.closest('[data-remove-lot]');if(b)b.closest('tr').remove();});
  $('#importButton').addEventListener('click',()=>$('#importFile').click());$('#importFile').addEventListener('change',async()=>{const file=$('#importFile').files?.[0];if(!file)return;try{if(file.size>500000)throw Error('계획 파일은 500 KB 이하여야 합니다.');importPlan(JSON.parse(await file.text()));}catch(e){say('계획 불러오기 실패: '+e.message,true);}finally{$('#importFile').value='';}});
  for(const id of ['sourcesButton','scopeFooter'])$('#'+id).addEventListener('click',()=>{pause();$('#sourcesDialog').showModal();});
  $$('[data-close]').forEach(b=>b.addEventListener('click',()=>b.dataset.close==='equipmentDialog'?closeEquipment():$('#'+b.dataset.close).close()));$('#equipmentDialog').addEventListener('cancel',e=>{e.preventDefault();closeEquipment();});$('#openEquipment').addEventListener('click',openEquipment);
  $('#motionButton').addEventListener('click',()=>{if(!viewport)return;if(motionTime>=1)motionTime=0;motion=!motion;viewport.update(motionTime,motion);$('#motionButton').textContent=motion?'Ⅱ 동작 일시정지':'▶ 원리 동작 재생';});$('#cameraButton').addEventListener('click',()=>{topCamera=!topCamera;viewport?.camera(topCamera?'top':'equipment');});
  document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;motion=false;viewport?.update(motionTime,false);$('#motionButton').textContent='▶ 원리 동작 재생';render();}});
  function dispose(){disposed=true;playing=false;motion=false;cancelAnimationFrame(frame);viewport?.dispose();viewport=null;}
  root.addEventListener('pagehide',dispose);initMap();syncPlanControls();render(true);renderComparison();say(startupNote||'HAR 챔버 편차 예제를 첫 계측 보류 시점에서 열었습니다. ‘이 챔버 제외 후 전체 비교’로 대안을 확인하세요.');frame=requestAnimationFrame(tick);
  root.MemoryFabApp=Object.freeze({seek,selectChamber,selectLot,setProduct,applyPlan,applyRecipe,isolate,restore,jumpIncident,importPlan,reportHTML,openEquipment,closeEquipment,openLots,applyLots,dispose,snapshot:()=>clone({result,baseline,time,playing,selectedChamber,selectedLot,product,motion,motionTime,drafts})});
})(window);
