(function () {
  'use strict';
  const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const roles={admin:'관리자',engineer:'공정 엔지니어',reviewer:'검토자'};
  const statuses={draft:'초안',submitted:'검토 요청',approved:'승인',rejected:'반려'};
  const kinds={simulation:'합성 모델',measurement:'사용자 제공 계측',demo:'합성 CSV 예시'};
  const titles={revisions:['레시피 · 버전 관리','변경의 이유와 실험 근거를 하나의 검토 흐름으로 연결하세요.'],experiments:['실험 · 계측 데이터','어떤 버전에서 얻은 결과인지, 데이터의 출처부터 확인하세요.'],reviews:['검토 대기함','변경 조건과 근거를 확인하고 검토 의견을 남기세요.'],audit:['변경 이력','작성 · 실험 · 검토의 순서를 서버 기록으로 확인하세요.'],team:['구성원 관리','작성과 검토 역할을 분리해 워크스페이스를 운영하세요.']};
  const S={user:null,csrf:'',catalog:null,projects:[],projectId:'',data:null,revisionId:'',tab:'revisions',initialized:false,loading:0};
  let toastTimer;const detailRecords=new Map();
  const authoring=()=>S.user&&['admin','engineer'].includes(S.user.role);
  const current=()=>S.data?.revisions.find(r=>r.id===S.revisionId);
  const time=value=>new Date(value).toLocaleString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
  const statusPill=r=>`<span class="pill ${r.status}">${statuses[r.status]}</span>`;
  const sourcePill=kind=>`<span class="pill ${kind}">${kinds[kind]}</span>`;
  const fmt=(n,d=2)=>n===null||n===undefined?'—':Number(n).toLocaleString('ko-KR',{maximumFractionDigits:d});

  async function api(path, method='GET', data){
    const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);
    let response;
    try{response=await fetch('/api'+path,{method,credentials:'same-origin',signal:controller.signal,headers:{'Content-Type':'application/json','X-WaferFlow':'review',...(S.csrf?{'X-CSRF-Token':S.csrf}:{})},...(data?{body:JSON.stringify(data)}:{})});}finally{clearTimeout(timeout);}
    let result;try{result=await response.json();}catch{throw new Error('워크스페이스 서버가 응답하지 않습니다. start-review.ps1로 실행하세요.');}
    if(!response.ok){if(response.status===401&&path!=='/login'){showAuth(true);S.user=null;S.csrf='';S.data=null;$('#reviewContent').innerHTML='';}throw new Error(result.error||'요청에 실패했습니다.');}
    return result;
  }
  function toast(message,error=false){$('#reviewToast').textContent=message;$('#reviewToast').hidden=false;$('#reviewToast').classList.toggle('error',error);clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#reviewToast').hidden=true,5000);}
  async function task(button,fn){if(button)button.disabled=true;try{await fn();}catch(error){const msg=error.name==='AbortError'?'요청 시간이 초과되었습니다. 새로고침해 저장 여부를 확인하세요.':error.message;const output=$('#dialogError');if(output)output.textContent=msg;else toast(msg,true);}finally{if(button)button.disabled=false;}}
  function showAuth(initialized){S.initialized=initialized;$('#authScreen').hidden=false;$('#reviewShell').hidden=true;$('#reviewDialog').close();$('#authForm').hidden=false;$('#serverHelp').hidden=true;$('#authTitle').textContent=initialized?'워크스페이스에 로그인':'첫 관리자 설정';$('#authDescription').textContent=initialized?'팀 계정으로 레시피와 검토 기록을 확인하세요.':'서버에 저장할 관리자 계정을 직접 설정하세요. 기본 계정이나 공용 비밀번호는 없습니다.';$('#displayNameLabel').hidden=initialized;$('#authForm [name="display_name"]').required=!initialized;$('#authPassword').minLength=initialized?1:12;$('#authPassword').autocomplete=initialized?'current-password':'new-password';$('#authSubmit').textContent=initialized?'로그인':'관리자 계정 만들기';$('#authError').textContent='';}
  async function start(){try{const status=await api('/status');showAuth(status.initialized);if(status.initialized){try{const me=await api('/me');await enter(me);}catch{showAuth(true);}}}catch(error){$('#authTitle').textContent='검토 서버에 연결하세요';$('#authDescription').textContent='레시피와 검토 기록은 서버 워크스페이스에서 관리합니다.';$('#authForm').hidden=true;$('#serverHelp').hidden=false;}}
  async function enter(me){S.user=me.user;S.csrf=me.csrf;if(!me.catalog)me=await api('/me');S.catalog=me.catalog;$('#authForm').reset();$('#authScreen').hidden=true;$('#reviewShell').hidden=false;$('#userName').textContent=S.user.display_name;$('#userRole').textContent=roles[S.user.role];$('#userAvatar').textContent=S.user.display_name.slice(0,2).toUpperCase();$('#teamNav').hidden=S.user.role!=='admin';$('#newProject').hidden=!authoring();S.tab='revisions';await refresh();
    let transfer;try{transfer=JSON.parse(sessionStorage.getItem('wf-review-draft')||'null');}catch{}if(transfer){sessionStorage.removeItem('wf-review-draft');const project=S.projects.find(p=>p.id===transfer.projectId);if(project&&authoring()){S.projectId=project.id;await refresh();S.revisionId=transfer.baseId;render();openRecipe(true,transfer.params);}}
  }
  async function refresh(){const serial=++S.loading;$('#workspaceMessage').hidden=true;const projects=await api('/projects');if(serial!==S.loading)return;S.projects=projects;if(!projects.some(p=>p.id===S.projectId))S.projectId=projects[0]?.id||'';$('#projectSelect').innerHTML=projects.length?projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join(''):'<option value="">아직 프로젝트가 없습니다</option>';$('#projectSelect').value=S.projectId;$('#projectPurpose').textContent=projects.find(p=>p.id===S.projectId)?.description||'';$('#exportProject').disabled=!S.projectId;const data=S.projectId?await api('/projects/'+S.projectId):null;if(serial!==S.loading)return;S.data=data;if(!data?.revisions.some(r=>r.id===S.revisionId))S.revisionId=data?.revisions[0]?.id||'';render();}
  function render(){const [title,description]=titles[S.tab];$('#viewTitle').textContent=title;$('#viewDescription').textContent=description;$('#reviewBreadcrumb').textContent=title;$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===S.tab);b.setAttribute('aria-current',b.dataset.tab===S.tab?'page':'false');});$('#queueCount').textContent=S.data?.revisions.filter(r=>r.status==='submitted').length||0;
    if(S.tab==='team'){renderTeam();return;}if(S.tab==='audit'){renderAudit();return;}
    if(!S.data){$('#reviewContent').innerHTML=`<div class="empty-state"><div class="empty-icon">▤</div><h2>첫 공정 검토 프로젝트를 만드세요.</h2><p>프로젝트 안에서 레시피 버전, 시뮬레이션, 계측 CSV와 검토 의견을 함께 관리합니다.</p>${authoring()?'<button class="primary" data-action="project">＋ 프로젝트 만들기</button>':'<p>관리자나 엔지니어가 프로젝트를 만들면 이곳에서 확인할 수 있습니다.</p>'}</div>`;return;}
    const {revisions,experiments,recipes}=S.data;const pending=revisions.filter(r=>r.status==='submitted').length;
    const metrics=`<div class="metrics-row"><article class="summary-card"><span>관리 레시피</span><strong>${recipes.length}</strong><small>버전 ${revisions.length}개 · 원본 보존</small></article><article class="summary-card review-summary"><span>검토 대기</span><strong>${pending.toString().padStart(2,'0')}</strong><small>승인 ${revisions.filter(r=>r.status==='approved').length} · 반려 ${revisions.filter(r=>r.status==='rejected').length}</small></article><article class="summary-card"><span>연결된 실험</span><strong>${experiments.length}</strong><small>기록 당시 결과 고정</small></article><article class="summary-card"><span>사용자 제공 계측</span><strong>${experiments.filter(e=>e.kind==='measurement').length}</strong><small>합성 모델·예시 데이터 제외</small></article></div>`;
    $('#reviewContent').innerHTML=metrics+(S.tab==='experiments'?experimentPage():S.tab==='reviews'?reviewPage():recipePage());
  }
  function recipePage(){const data=S.data,r=current();const list=data.recipes.map(recipe=>{const revisions=data.revisions.filter(v=>v.recipe_id===recipe.id).sort((a,b)=>b.number-a.number);return `<div class="recipe-group-title">${esc(recipe.name)}<span>${revisions.length} REV</span></div>${revisions.map(v=>`<button class="revision-item ${v.id===S.revisionId?'active':''}" data-revision="${v.id}" aria-pressed="${v.id===S.revisionId}"><strong>Revision ${String(v.number).padStart(2,'0')}</strong>${statusPill(v)}<small>${esc(v.author)}</small><small>${esc(time(v.created_at).slice(0,13))}</small></button>`).join('')}`;}).join('');return `<div class="workspace-grid"><section class="white-panel"><div class="panel-top"><h2>레시피 라이브러리</h2>${authoring()?'<button class="quiet" data-action="recipe">＋ 새 레시피</button>':''}</div><div class="recipe-list">${list||'<p class="inline-empty">첫 레시피를 등록해 검토를 시작하세요.</p>'}</div></section>${r?revisionPanel(r):'<div class="empty-state"><div class="empty-icon">◈</div><h2>비교 가능한 첫 버전</h2><p>12개 공정 조건과 변경 사유를 입력해 첫 레시피를 만드세요. 이후 수정은 새 버전으로 기록됩니다.</p>'+(authoring()?'<button class="primary" data-action="recipe">새 레시피 작성</button>':'')+'</div>'}</div>`;}
  function revisionPanel(r){const parent=S.data.revisions.find(v=>v.id===r.parent_id),base=parent?.params||S.catalog.defaults;const evidence=S.data.experiments.filter(e=>e.revision_id===r.id);const owner=r.created_by===S.user.id,canEdit=authoring()&&owner&&r.status==='draft',canReview=['admin','reviewer'].includes(S.user.role)&&!owner&&r.status==='submitted';
    const changes=Object.keys(base).filter(k=>base[k]!==r.params[k]);return `<section class="white-panel"><div class="revision-title"><div>${statusPill(r)}<h2>${esc(r.recipe_name)}</h2><p>${esc(r.author)} · ${esc(time(r.created_at))} · ${esc(r.model_version)}</p></div><span class="revision-num">r${String(r.number).padStart(2,'0')}</span></div><div class="revision-reason"><span>CHANGE RATIONALE</span><p>${esc(r.change_reason)}</p></div><div class="revision-actions"><a class="secondary" href="photo-lab.html?revision=${r.id}">◈ 3D 장비에서 확인 ↗</a>${authoring()?'<button class="secondary" data-action="revise">새 버전 작성</button>':''}${canEdit?'<button class="primary" data-action="simulate">＋ 시뮬레이션</button><button class="secondary" data-action="import">계측 CSV 연결</button><button class="quiet" data-transition="submit" '+(evidence.length?'':'disabled')+'>검토 요청 →</button>':''}${canReview?'<button class="primary" data-transition="approve">승인</button><button class="danger" data-transition="reject">반려</button>':''}</div>${canEdit&&!evidence.length?'<p class="review-requirement">실험 근거를 하나 이상 연결하면 검토를 요청할 수 있습니다.</p>':''}${r.status==='submitted'&&owner?'<p class="review-requirement">다른 관리자 또는 검토자가 검토 의견과 함께 판정합니다.</p>':''}${r.review_note?`<div class="review-note"><strong>${statuses[r.status]} · ${esc(time(r.reviewed_at))}</strong>${esc(r.review_note)}</div>`:''}<div class="comparison-heading"><h3>공정 조건 · ${parent?'이전 r'+String(parent.number).padStart(2,'0')+'과 비교':'모델 기본값과 비교'}</h3><span>${changes.length} CHANGES</span></div><div class="table-scroll"><table><thead><tr><th>파라미터</th><th>단위</th><th>비교 기준</th><th>현재 버전</th><th>변화량</th></tr></thead><tbody>${Object.entries(S.catalog.fields).map(([k,f])=>{const delta=r.params[k]-base[k];return `<tr><td>${esc(f.label)}</td><td class="mono">${esc(f.unit)}</td><td class="mono">${fmt(base[k])}</td><td class="mono ${delta?'change':''}">${fmt(r.params[k])}</td><td class="mono ${delta?'change':''}">${delta?(delta>0?'+':'')+fmt(delta):'—'}</td></tr>`;}).join('')}</tbody></table></div><div class="evidence-heading">연결된 실험 근거<span>${evidence.length} RECORDS</span></div><div class="evidence-list">${evidence.map(e=>`<button class="evidence-item" data-experiment="${e.id}"><div>${sourcePill(e.kind)} <b>${esc(e.name)}</b><small>LOT ${esc(e.lot_id)} · ${esc(e.author)}</small></div><strong>${fmt(e.kind==='simulation'?e.result.cd_nm:e.result.cd_mean_nm)} <small>CD nm</small></strong></button>`).join('')||'<p class="inline-empty">아직 이 버전에 연결된 실험이 없습니다.</p>'}</div><p class="scope-note">이 화면의 승인은 변경안에 대한 동료 검토 상태입니다. 내장 모델은 실제 공정 데이터로 보정되지 않았으며 양산 투입 판정을 대신하지 않습니다.</p></section>`;}
  function experimentPage(){const experiments=S.data.experiments;return `<section class="white-panel"><div class="panel-top"><h2>실험 레지스터</h2><div class="toolbar-inline"><select id="experimentFilter" aria-label="데이터 출처 필터"><option value="all">모든 출처</option><option value="measurement">사용자 제공 계측</option><option value="simulation">합성 모델</option><option value="demo">합성 CSV 예시</option></select><small>${experiments.length} RECORDS</small></div></div><div class="table-scroll"><table><thead><tr><th>실험 / Lot</th><th>데이터 출처</th><th>레시피 버전</th><th>CD (nm)</th><th>식각 (nm)</th><th>기록</th></tr></thead><tbody>${experiments.map(e=>`<tr data-kind="${e.kind}"><td><button class="table-button" data-experiment="${e.id}">${esc(e.name)}</button><small>${esc(e.lot_id)}</small></td><td>${sourcePill(e.kind)}</td><td><button class="table-button" data-open-revision="${e.revision_id}">${esc(e.recipe_name)} · r${e.revision_number}</button></td><td class="mono">${fmt(e.kind==='simulation'?e.result.cd_nm:e.result.cd_mean_nm)}</td><td class="mono">${fmt(e.kind==='simulation'?e.result.etch_depth_nm:e.result.etch_depth_mean_nm)}</td><td>${esc(e.author)}<small>${esc(time(e.created_at))}</small></td></tr>`).join('')||'<tr><td colspan="6" class="inline-empty">레시피 초안에서 시뮬레이션을 실행하거나 계측 CSV를 연결하세요.</td></tr>'}</tbody></table></div><p class="scope-note">CSV의 CD·식각 값은 표본 평균, 합성 모델 값은 모델의 대표값입니다. 데이터 출처와 표본 수를 확인한 뒤 비교하세요.</p></section>`;}
  function reviewPage(){const pending=S.data.revisions.filter(r=>r.status==='submitted');return `<div class="review-queue">${pending.map(r=>`<article class="queue-card"><div>${statusPill(r)}<h3>${esc(r.recipe_name)} · r${r.number}</h3><p>${esc(r.author)} · 근거 ${S.data.experiments.filter(e=>e.revision_id===r.id).length}개 · ${esc(time(r.created_at))}</p></div><div><button class="primary" data-open-revision="${r.id}">변경점과 근거 검토 →</button></div></article>`).join('')||'<div class="empty-state"><div class="empty-icon">✓</div><h2>검토 대기 중인 변경안이 없습니다.</h2><p>작성자가 실험 근거와 함께 검토를 요청하면 이곳에 표시됩니다.</p></div>'}</div>`;}
  async function renderAudit(){const tab=S.tab;$('#reviewContent').innerHTML='<p class="inline-empty">변경 이력을 불러오는 중입니다.</p>';try{const entries=await api('/audit');if(S.tab!==tab||!S.user)return;$('#reviewContent').innerHTML=`<section class="white-panel"><div class="panel-top"><h2>워크스페이스 변경 이력</h2><small>조직 전체 · 최근 300개</small></div><div class="table-scroll"><table><thead><tr><th>순서</th><th>시각</th><th>수행자</th><th>작업</th><th>대상</th></tr></thead><tbody>${entries.map(e=>`<tr><td class="mono">${e.sequence}</td><td class="audit-time">${esc(time(e.created_at))}</td><td>${esc(e.actor||'시스템')}</td><td class="event-name">${esc(e.action)}</td><td class="mono">${esc(e.entity_id.slice(0,12))}</td></tr>`).join('')}</tbody></table></div><p class="scope-note">서버에 기록된 변경 이력입니다. 외부 공증 또는 변경 불가능한 보관 시스템에 해당하지 않습니다.</p></section>`;}catch(e){toast(e.message,true);}}
  async function renderTeam(){if(S.user.role!=='admin')return;$('#reviewContent').innerHTML='<p class="inline-empty">구성원을 불러오는 중입니다.</p>';try{const users=await api('/users');if(S.tab!=='team'||!S.user)return;$('#reviewContent').innerHTML=`<section class="white-panel"><div class="panel-top"><h2>조직 구성원</h2><button class="primary" data-action="user">＋ 구성원 등록</button></div><div class="table-scroll"><table><thead><tr><th>이름</th><th>아이디</th><th>역할</th><th>상태</th><th>관리</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.display_name)}</td><td>${esc(u.username)}</td><td class="team-role">${roles[u.role]}</td><td><span class="pill ${u.active?'approved':'rejected'}">${u.active?'활성':'비활성'}</span></td><td>${u.id!==S.user.id?`<button class="table-button" data-user-id="${u.id}" data-active="${u.active?'false':'true'}">${u.active?'비활성화':'활성화'}</button>`:'내 계정'}</td></tr>`).join('')}</tbody></table></div><p class="scope-note">엔지니어: 레시피·실험 작성 / 검토자: 승인·반려 / 관리자: 구성원 관리 및 두 역할. 모든 구성원은 같은 조직의 프로젝트를 열람합니다.</p></section>`;}catch(e){toast(e.message,true);}}
  function dialog(title,content){$('#reviewDialogTitle').textContent=title;$('#reviewDialogBody').innerHTML=content;$('#reviewDialog').showModal();}
  function form(content,label='저장',action=''){return `<form id="workspaceForm" data-form-action="${action}">${content}<p id="dialogError" class="form-error" role="alert"></p><div class="dialog-actions"><button type="button" class="secondary" data-close-dialog>취소</button><button type="submit" class="primary">${label}</button></div></form>`;}
  function projectDialog(){dialog('새 공정 검토 프로젝트',form('<label>프로젝트 이름<input name="name" required maxlength="100" placeholder="예: PR 현상 조건 검토"></label><label>검토 목적<textarea name="description" maxlength="1000" placeholder="검토할 공정, 문제와 목표를 기록하세요."></textarea></label>','프로젝트 만들기','project'));}
  function openRecipe(revising=false,transferredParams=null){const r=revising?current():null;if(revising&&!r)throw new Error('기준 버전을 선택하세요.');const latest=r?S.data.revisions.filter(v=>v.recipe_id===r.recipe_id).sort((a,b)=>b.number-a.number)[0]:null;if(r&&latest.id!==r.id){toast('새 버전은 가장 최신 버전을 기준으로 작성하세요.',true);return;}const p=transferredParams||r?.params||S.catalog.defaults;dialog(revising?'새 레시피 버전 작성':'첫 레시피 버전 작성',form(`<p class="form-tip">${r?'r'+r.number+'에서 분기합니다. 저장하면 별도의 초안 버전이 생성됩니다.':'초기 버전의 공정 조건과 설정 근거를 기록하세요.'}</p><input type="hidden" name="recipe_id" value="${r?.recipe_id||''}"><input type="hidden" name="base_revision_id" value="${r?.id||''}">${r?'': '<label>레시피 이름<input name="name" required maxlength="100" placeholder="예: Positive PR / DEV 조건"></label>'}<label>합성 모델 시나리오<select name="scenario">${S.catalog.missions.map(m=>`<option value="${m.id}" ${m.id===(r?.scenario||'residue')?'selected':''}>${esc(m.subtitle)} · 교육용</option>`).join('')}</select></label><div class="field-grid">${Object.entries(S.catalog.fields).map(([k,f])=>`<label>${esc(f.label)}<small>${esc(f.unit)}</small><input type="number" name="${k}" required min="${f.min}" max="${f.max}" step="${f.step}" value="${esc(p[k])}"></label>`).join('')}</div><label>변경 사유 · 검토 가설<textarea name="change_reason" required maxlength="2000" placeholder="어떤 조건을 왜 변경하며, 어떤 결과로 가설을 확인할 것인지 기록하세요."></textarea></label>`,'초안 버전 저장','recipe'));}
  function simulationDialog(){const r=current();dialog('시뮬레이션 근거 기록',form(`<div class="data-source-note">버전 r${r.number}의 고정된 조건으로 서버에서 다시 계산합니다. 결과는 미보정 합성 모델의 출력이며 실제 장비 계측값과 분리됩니다.</div><div class="form-grid"><label class="full">실험 이름<input name="name" required maxlength="100" value="${esc(r.recipe_name)} · 합성 실행"></label><label>Lot 식별자<input name="lot_id" required maxlength="80" placeholder="SIM-LOT-001"></label><label>재현 시드<input name="seed" type="number" min="0" max="2147483647" step="1" required value="${S.catalog.missions.find(m=>m.id===r.scenario).seed}"></label></div><input type="hidden" name="revision_id" value="${r.id}">`,'실행하고 결과 저장','simulate'));}
  function importDialog(){const r=current();dialog('계측 CSV 연결',form(`<div class="data-source-note measured-note">UTF-8 CSV · 최대 2,000행 / 1 MB. wafer_id + site_id는 중복될 수 없습니다. CD와 식각 깊이의 단위는 nm입니다.</div><div class="form-grid"><label>실험 이름<input name="name" required maxlength="100" placeholder="예: DEV 이후 CD 계측"></label><label>Lot ID<input name="lot_id" required maxlength="80" placeholder="LOT-001"></label><label>데이터 구분<select name="kind"><option value="measurement">사용자 제공 계측 · 미검증</option><option value="demo">합성 예시 데이터</option></select></label><label>원본 출처<input name="source_name" required maxlength="200" placeholder="계측 장비·파일명·기록 번호"></label><label>CD 규격 하한 (nm)<input name="cd_lsl_nm" type="number" min="0" max="100000" step="any" required placeholder="직접 입력"></label><label>CD 규격 상한 (nm)<input name="cd_usl_nm" type="number" min="0" max="100000" step="any" required placeholder="직접 입력"></label></div><label>CSV 파일 선택<input id="csvFile" type="file" accept=".csv,text/csv"></label><div class="toolbar-inline"><button type="button" class="quiet" data-action="csv-demo">합성 CSV 예시 채우기</button><small class="form-tip">예시를 사용하면 데이터 구분도 ‘합성 예시’로 바뀝니다.</small></div><label>가져올 원본 내용<textarea class="csv-editor" name="csv" required spellcheck="false" placeholder="wafer_id,site_id,cd_nm,etch_depth_nm"></textarea></label><p class="form-tip">규격은 사용자가 정의합니다. 규격 충족 비율은 업로드한 사이트의 관측 비율이며 공정 수율이 아닙니다.</p><input type="hidden" name="revision_id" value="${r.id}">`,'검증하고 데이터 저장','import'));}
  function transitionDialog(action){const r=current();const names={submit:'검토 요청',approve:'변경안 승인',reject:'변경안 반려'};dialog(names[action],form(`<p class="form-tip">${esc(r.recipe_name)} · r${r.number}${action==='submit'?'의 조건과 연결된 근거를 고정하고 동료 검토를 요청합니다.':'의 변경점과 연결된 근거를 검토한 의견을 기록하세요.'}</p><input type="hidden" name="revision_id" value="${r.id}"><input type="hidden" name="lock_version" value="${r.lock_version}"><input type="hidden" name="transition" value="${action}">${action==='submit'?'<div class="data-source-note">검토 요청 후에는 해당 버전에 실험 근거를 추가할 수 없습니다. 추가 실험이나 수정은 새 버전으로 기록하세요.</div>':'<label>검토 의견<textarea name="note" required maxlength="2000" placeholder="검토한 근거, 판단 이유 및 후속 조치를 기록하세요."></textarea></label>'}`,names[action],'transition'));}
  function chart(rows,limits){const values=rows.map(r=>r.cd_nm),lo=Math.min(...values,limits.cd_lsl_nm),hi=Math.max(...values,limits.cd_usl_nm),span=hi-lo||1,min=lo-span*.15,max=hi+span*.15;const x=i=>45+i*540/Math.max(1,values.length-1),y=v=>165-(v-min)/(max-min)*140;return `<svg class="measurement-chart" viewBox="0 0 620 210" role="img" aria-label="업로드 순서에 따른 사이트별 CD와 입력 규격. 시간 관리도가 아닙니다."><rect x="45" y="${y(limits.cd_usl_nm)}" width="540" height="${y(limits.cd_lsl_nm)-y(limits.cd_usl_nm)}" fill="#eff6ec"/>${[limits.cd_lsl_nm,limits.cd_usl_nm].map(v=>`<line x1="45" y1="${y(v)}" x2="585" y2="${y(v)}" stroke="#a8b78a" stroke-dasharray="4 4"/><text x="2" y="${y(v)+3}">${fmt(v)}</text>`).join('')}<polyline points="${values.map((v,i)=>x(i)+','+y(v)).join(' ')}" fill="none" stroke="#387d80" stroke-width="1.5"/>${values.length<=150?values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="2.8" fill="${v<limits.cd_lsl_nm||v>limits.cd_usl_nm?'#ba735c':'#387d80'}"/>`).join(''):''}<text x="45" y="196">SITE 1</text><text x="510" y="196">SITE ${values.length}</text><text x="260" y="196">CD / nm</text></svg>`;}
  async function evidenceDialog(id){if(!S.data.experiments.some(x=>x.id===id))return;const e=await api('/experiments/'+id);detailRecords.set(id,e);const r=e.result,sim=e.kind==='simulation';dialog(e.name,`${sourcePill(e.kind)}<div class="result-summary"><div><span>${sim?'모델 대표 CD':'CD 표본 평균'}</span><strong>${fmt(sim?r.cd_nm:r.cd_mean_nm)}</strong><small>nm</small></div><div><span>${sim?'합성 다이 수':'표본 사이트'}</span><strong>${sim?r.total:r.count}</strong><small>${sim?'합성 판정 대상':r.wafer_count+' wafers'}</small></div><div><span>${sim?'합성 수율':'사이트 규격 충족'}</span><strong>${fmt(sim?r.yield_percent:r.within_spec_percent,1)}%</strong><small>${sim?'모델 내 비율':'입력 규격 기준'}</small></div></div>${sim?`<div class="data-source-note">${esc(r.model_notice)}<br>시드 ${r.seed} · ${esc(r.version)}</div>`:chart(r.rows,r.limits)+`<p class="form-tip">${esc(r.interpretation)}<br>CD 표본 표준편차: ${fmt(r.cd_stdev_nm)} nm · 최소 ${fmt(r.cd_min_nm)} / 최대 ${fmt(r.cd_max_nm)} nm<br>출처: ${esc(r.source_name)} · ${esc(kinds[e.kind])}</p>`}<div class="record-meta">REVISION ${esc(e.revision_id)}<br>LOT ${esc(e.lot_id)} · ${esc(e.author)} · ${esc(time(e.created_at))}<br>RESULT SHA-256 ${esc(e.digest)}</div><div class="dialog-actions"><button class="secondary" data-download-evidence="${e.id}">원본 결과 JSON 저장</button><button class="primary" data-close-dialog>확인</button></div>`);}
  function userDialog(){dialog('구성원 계정 등록',form('<div class="form-grid"><label>표시 이름<input name="display_name" required maxlength="60"></label><label>아이디<input name="username" required minlength="3" maxlength="60" autocomplete="off"></label><label>역할<select name="role"><option value="engineer">공정 엔지니어</option><option value="reviewer">검토자</option><option value="admin">관리자</option></select></label><label>초기 비밀번호<input name="password" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label></div><p class="form-tip">초기 비밀번호는 안전한 경로로 전달하고, 사용자는 로그인 후 자신의 비밀번호로 변경하세요.</p>','계정 만들기','user'));}
  function passwordDialog(){dialog('내 계정 · 비밀번호 변경',form(`<p class="form-tip">${esc(S.user.display_name)} · ${roles[S.user.role]}</p><label>현재 비밀번호<input name="current_password" type="password" required autocomplete="current-password" maxlength="128"></label><label>새 비밀번호<input name="new_password" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label><p class="form-tip">변경하면 다른 기기의 세션은 종료됩니다.</p><button type="button" class="quiet" data-action="logout">이 기기에서 로그아웃</button>`,'비밀번호 변경','password'));}
  async function submitForm(formEl){const values=Object.fromEntries(new FormData(formEl));const action=formEl.dataset.formAction;const button=formEl.querySelector('[type="submit"]');await task(button,async()=>{let response;
    if(action==='project'){response=await api('/projects','POST',values);S.projectId=response.id;}
    if(action==='recipe'){const params=Object.fromEntries(Object.keys(S.catalog.fields).map(k=>[k,Number(values[k])]));const payload={name:values.name,params,scenario:values.scenario,change_reason:values.change_reason,base_revision_id:values.base_revision_id};response=await api(values.recipe_id?'/recipes/'+values.recipe_id+'/revisions':'/projects/'+S.projectId+'/recipes','POST',payload);S.revisionId=response.revision_id;}
    if(action==='simulate'){await api('/revisions/'+values.revision_id+'/experiments','POST',{kind:'simulation',name:values.name,lot_id:values.lot_id,seed:Number(values.seed)});}
    if(action==='import'){await api('/revisions/'+values.revision_id+'/experiments','POST',{...values,cd_lsl_nm:Number(values.cd_lsl_nm),cd_usl_nm:Number(values.cd_usl_nm)});}
    if(action==='transition'){await api('/revisions/'+values.revision_id+'/transition','POST',{action:values.transition,lock_version:Number(values.lock_version),note:values.note});}
    if(action==='user')await api('/users','POST',values);
    if(action==='password')await api('/password','POST',values);
    $('#reviewDialog').close();await refresh();toast('서버에 기록했습니다.');});}
  function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function logout(){await api('/logout','POST',{});S.user=null;S.csrf='';S.data=null;S.projects=[];detailRecords.clear();S.projectId='';S.revisionId='';$('#reviewContent').innerHTML='';showAuth(true);}
  document.addEventListener('submit',e=>{if(e.target.id==='workspaceForm'){e.preventDefault();submitForm(e.target);}});
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close-dialog')){$('#reviewDialog').close();return;}if(b.dataset.tab){S.tab=b.dataset.tab;render();return;}if(b.dataset.revision){S.revisionId=b.dataset.revision;render();return;}if(b.dataset.openRevision){S.revisionId=b.dataset.openRevision;S.tab='revisions';render();return;}if(b.dataset.experiment){task(b,()=>evidenceDialog(b.dataset.experiment));return;}if(b.dataset.transition){transitionDialog(b.dataset.transition);return;}if(b.dataset.downloadEvidence){const entry=detailRecords.get(b.dataset.downloadEvidence);download('waferflow-experiment-'+entry.id+'.json',entry);return;}
    if(b.dataset.userId){dialog(b.dataset.active==='true'?'구성원 활성화':'구성원 비활성화',`<p class="form-tip">${b.dataset.active==='true'?'이 계정으로 다시 로그인할 수 있습니다.':'현재 로그인 세션을 종료하고 새 로그인을 차단합니다. 기존 작성 기록은 유지합니다.'}</p><div class="dialog-actions"><button class="secondary" data-close-dialog>취소</button><button class="primary" data-confirm-user="${b.dataset.userId}" data-active="${b.dataset.active}">적용</button></div>`);return;}
    if(b.dataset.confirmUser){task(b,async()=>{await api('/users/'+b.dataset.confirmUser+'/active','POST',{active:b.dataset.active==='true'});$('#reviewDialog').close();renderTeam();toast('구성원 상태를 변경했습니다.');});return;}
    const action=b.dataset.action;if(action==='project')projectDialog();else if(action==='recipe')openRecipe();else if(action==='revise')openRecipe(true);else if(action==='simulate')simulationDialog();else if(action==='import')importDialog();else if(action==='user')userDialog();else if(action==='logout')task(b,logout);else if(action==='csv-demo'){const f=$('#workspaceForm');f.querySelector('[name="csv"]').value='wafer_id,site_id,cd_nm,etch_depth_nm\n'+Array.from({length:12},(_,i)=>'DEMO-W01,S'+String(i+1).padStart(2,'0')+','+[498,502,505,499,501,496,503,508,510,497,501,525][i]+','+(98+i*.4).toFixed(1)).join('\n');f.querySelector('[name="kind"]').value='demo';f.querySelector('[name="source_name"]').value='WaferFlow 합성 예시 · 실측 아님';f.querySelector('[name="name"]').value='합성 CSV 가져오기 실습';f.querySelector('[name="lot_id"]').value='DEMO-LOT';f.querySelector('[name="cd_lsl_nm"]').value=480;f.querySelector('[name="cd_usl_nm"]').value=520;}});
  document.addEventListener('change',e=>{if(e.target.id==='csvFile'){task(null,async()=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1000000)throw new Error('CSV 파일은 최대 1 MB입니다.');$('#workspaceForm [name="csv"]').value=await file.text();$('#workspaceForm [name="source_name"]').value=file.name;});}if(e.target.id==='experimentFilter')$$('[data-kind]').forEach(tr=>tr.hidden=e.target.value!=='all'&&tr.dataset.kind!==e.target.value);});
  $('#authForm').addEventListener('submit',async e=>{e.preventDefault();const button=$('#authSubmit');button.disabled=true;$('#authError').textContent='';try{const values=Object.fromEntries(new FormData(e.target));const me=await api(S.initialized?'/login':'/bootstrap','POST',values);await enter(me);}catch(error){$('#authError').textContent=error.message;}finally{button.disabled=false;}});
  $('#newProject').addEventListener('click',projectDialog);$('#projectSelect').addEventListener('change',e=>{S.projectId=e.target.value;S.revisionId='';task(null,refresh);});$('#refreshButton').addEventListener('click',e=>task(e.currentTarget,refresh));$('#logoutButton').addEventListener('click',e=>task(e.currentTarget,logout));$('#passwordButton').addEventListener('click',passwordDialog);$('#accountMenu').addEventListener('click',passwordDialog);$('#closeReviewDialog').addEventListener('click',()=>$('#reviewDialog').close());$('#retryConnection').addEventListener('click',start);$('#exportProject').addEventListener('click',e=>task(e.currentTarget,async()=>{download('waferflow-review-'+S.projectId+'.json',await api('/projects/'+S.projectId+'/export'));toast('버전·결과·검토 이력을 내보냈습니다.');}));
  window.WaferReview={refresh,getState:()=>({user:S.user,projectId:S.projectId,revisionId:S.revisionId,tab:S.tab})};
  start();
})();
