import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {Blob} from 'node:buffer';
import {parseHTML,Event} from './linkedom.worker.mjs';

export async function runEvidenceTests(root){
  const files=Object.fromEntries(await Promise.all(['evidence.html','memory-fab-engine.js','evidence-engine.js','evidence-app.js'].map(async f=>[f,await fs.readFile(root+'/'+f,'utf8')]))),ctx=vm.createContext({crypto:webcrypto,TextEncoder});vm.runInContext(files['memory-fab-engine.js'],ctx);vm.runInContext(files['evidence-engine.js'],ctx);const E=ctx.EvidenceEngine,M=ctx.MemoryFab,clone=x=>JSON.parse(JSON.stringify(x)),tests=[];
  const test=async(name,fn)=>{try{await fn();tests.push({name,status:'passed'});}catch(e){tests.push({name,status:'failed',error:e.stack});}};
  const config=kind=>({method:'affine',trainFraction:.7,limits:E.profiles[kind].limits});
  await test('Each supported response uses the same deterministic term as the fab model',()=>{const r=M.run({scenario:'normal'});for(const kind of ['har','cvd','cmp']){const row=r.records.find(r=>r.tool===kind),op=M.products[row.product].route[row.operation];const p=kind==='har'?{target_nm:op.depth,power_w:row.recipe.power,pressure_mtorr:row.recipe.pressure,time_s:row.recipe.time}:kind==='cvd'?{target_nm:op.film,temperature_c:row.recipe.temperature,flow_sccm:row.recipe.flow}:{before_nm:row.before.topography_nm,pressure_psi:row.recipe.pressure,rpm:row.recipe.rpm,time_s:row.recipe.time};const expected=M.referenceResponse(kind,p),actual=row.after[E.profiles[kind].metric];assert(Math.abs(actual/expected-1)<.0031);}});
  await test('All three synthetic demonstrations complete chronological held-out checks with explicit synthetic provenance',()=>{for(const kind of ['har','cvd','cmp']){const d=E.demo(kind),p=E.prepare(d,config(kind)),r=E.evaluate(p);assert.equal(r.after.lots,5);assert.equal(r.after.n,10);assert(r.after.mae<r.before.mae);assert(r.criteriaMet);assert.equal(r.provenance,'synthetic');assert.equal(r.manufacturingRelease,false);assert.equal(r.wholeFabValidated,false);assert.equal(r.sourceVerified,false);}});
  await test('Independent known affine response is recovered from training LOT means',()=>{const d=clone(E.demo('har'));for(const row of d.observations)row.measured=2*M.referenceResponse('har',row.inputs)+7;const p=E.prepare(d,config('har'));assert(Math.abs(p.fit.slope-2)<1e-10);assert(Math.abs(p.fit.intercept-7)<1e-7);assert(E.evaluate(p).after.maxError<1e-7);});
  await test('Changing future measured values never changes fitted coefficients or training domain',()=>{const d=clone(E.demo('har')),original=E.prepare(d,config('har'));d.observations.filter(r=>original.fit.validationLotIds.includes(r.lotId)).forEach(r=>r.measured+=1000);const altered=E.prepare(d,config('har'));assert.equal(JSON.stringify(altered.fit),JSON.stringify(original.fit));assert(E.evaluate(altered).after.mae>900);});
  await test('No LOT is split between calibration and validation, regardless of observation input order',()=>{const d=clone(E.demo('cvd'));d.observations.reverse();const p=E.prepare(d,config('cvd'));assert(!p.fit.trainingLotIds.some(id=>p.fit.validationLotIds.includes(id)));assert.equal(p.fit.trainingRows,20);assert.equal(p.fit.validationRows,10);assert(p.fit.cutoff<p.fit.firstValidation);});
  await test('Time overlap and late training metrology are rejected to prevent future-label leakage',()=>{const d=clone(E.demo('har'));d.observations[0].measuredAt='2026-01-12T15:00:00Z';assert.throws(()=>E.prepare(d,config('har')),/겹칩니다/);});
  await test('Minimum numbers count LOT groups, not correlated wafer observations',()=>{const d=clone(E.demo('har'));d.observations.forEach(r=>r.lotId='ONE-LOT');assert.throws(()=>E.prepare(d,config('har')),/6 LOT/);});
  await test('Unknown or missing units, null labels and numeric strings are not guessed or filled with zero',()=>{for(const mutate of [d=>d.units.measured='µm',d=>delete d.units.time_s,d=>d.observations[0].measured=null,d=>d.observations[0].measured='4200',d=>d.observations[0].inputs.power_w='1000',d=>d.observations[0].inputs.power_w=Infinity]){const d=clone(E.demo('har'));mutate(d);assert.throws(()=>E.normalize(d));}});
  await test('Duplicate observation and measurement join keys are rejected',()=>{const d=clone(E.demo('har'));d.observations[1].id=d.observations[0].id;assert.throws(()=>E.normalize(d),/重複|중복/);const b=clone(E.demo('har'));Object.assign(b.observations[1],{lotId:b.observations[0].lotId,waferId:b.observations[0].waferId,runId:b.observations[0].runId});assert.throws(()=>E.normalize(b),/중복/);});
  await test('Invalid dates, missing timezones, reversed measurement time and impossible zone offsets are rejected',()=>{for(const value of ['2026-02-30T00:00:00Z','2026-01-01T00:00:00','2026-01-01T24:00:00Z','2026-01-01T00:00:00+15:00']){const d=clone(E.demo('har'));d.observations[0].processedAt=value;assert.throws(()=>E.normalize(d));}const d=clone(E.demo('har'));d.observations[0].measuredAt='2025-12-31T00:00:00Z';assert.throws(()=>E.normalize(d),/빠릅니다/);});
  await test('ISO offsets normalize correctly before temporal splitting',()=>{const d=clone(E.demo('har'));d.observations[0].processedAt='2026-01-01T10:00:00+09:00';assert.equal(E.normalize(d).observations.find(r=>r.id===d.observations[0].id).processedAt,'2026-01-01T01:00:00.000Z');});
  await test('Profile, step and model version mismatches prevent mixing unrelated process evidence',()=>{for(const mutate of [d=>d.scope.referenceStepId='B05',d=>d.profile='scanner',d=>d.modelVersion='next',d=>d.scope.product='unknown']){const d=clone(E.demo('har'));mutate(d);assert.throws(()=>E.normalize(d));}});
  await test('Constant reference predictions reject slope fit but allow a declared offset-only model',()=>{const d=clone(E.demo('har'));d.observations.forEach(r=>{r.inputs.power_w=1000;r.measured=4210;});assert.throws(()=>E.prepare(d,config('har')),/변화가 너무/);const p=E.prepare(d,{...config('har'),method:'bias'});assert.equal(p.fit.slope,1);assert.equal(p.fit.intercept,10);assert.equal(E.evaluate(p).after.mae,0);});
  await test('A large future outlier fails fixed maximum-error criteria without being discarded',()=>{const d=clone(E.demo('har'));d.observations.at(-1).measured+=5000;const r=E.evaluate(E.prepare(d,config('har')));assert.equal(r.rows.length,10);assert(r.after.maxError>4900);assert.equal(r.criteriaMet,false);assert(!r.checks.find(c=>c.id==='maxError').passed);});
  await test('Out-of-domain validation conditions remain included in all-row metrics and fail scope check',()=>{const d=clone(E.demo('har'));d.observations.at(-1).inputs.power_w=1400;const r=E.evaluate(E.prepare(d,config('har')));assert(r.outOfDomainIds.includes(d.observations.at(-1).id));assert.equal(r.after.n,10);assert.equal(r.inDomain.n,9);assert.equal(r.criteriaMet,false);});
  await test('Negative calibrated predictions cannot be marked usable even inside an input box',()=>{const p=clone(E.prepare(E.demo('har'),config('har')));p.fit.intercept=-10000;const out=E.predict(p,E.demo('har').observations[0].inputs);assert(out.value<0);assert.equal(out.usable,false);});
  await test('Signed bias, RMSE, MAE and P95 follow the specified residual convention',()=>{const d=clone(E.demo('har'));d.observations.forEach(r=>{r.inputs.power_w=1000;r.measured=4200;});const errors=[-2,2,-2,2,-2,2,-2,2,-2,2];d.observations.slice(20).forEach((r,i)=>r.measured=4200-errors[i]);const r=E.evaluate(E.prepare(d,{...config('har'),method:'bias'}));assert.equal(r.after.bias,0);assert.equal(r.after.mae,2);assert.equal(r.after.rmse,2);assert.equal(r.after.p95,2);assert.equal(r.after.maxError,2);});
  await test('Offset fit weights each LOT mean equally rather than each wafer row',()=>{const d=clone(E.demo('har'));d.observations.forEach(r=>{r.inputs.power_w=1000;r.measured=4200;});d.observations.filter(r=>r.lotId==='DEMO-L01').forEach(r=>r.measured=4300);const extra=clone(d.observations[0]);for(let i=0;i<20;i++)d.observations.push({...extra,id:'extra'+i,waferId:'extra'+i,runId:'extra'+i});const p=E.prepare(d,{...config('har'),method:'bias'});assert(Math.abs(p.fit.intercept-10)<1e-9);});
  await test('Uploaded assertions never authorize source verification or manufacturing release',()=>{const d=clone(E.demo('har'));d.origin.kind='user-measurement';d.origin.verification='verified';d.manufacturingRelease=true;const p=E.prepare(d,config('har')),r=E.evaluate(p,{priorEvaluations:1});assert.equal(p.dataset.origin.verification,'unverified');assert.equal(r.sourceVerified,false);assert.equal(r.manufacturingRelease,false);assert(r.exploratory);});
  await test('Results and model are immutable; normalization and evaluation do not mutate input',()=>{const d=clone(E.demo('har')),before=JSON.stringify(d),p=E.prepare(d,config('har')),r=E.evaluate(p);assert.equal(JSON.stringify(d),before);assert(Object.isFrozen(p.fit));assert(Object.isFrozen(r.rows[0]));assert.throws(()=>{r.criteriaMet=true;});});
  await test('Template contains missing measured data rather than fabricated real observations',()=>{const d=E.template('har');assert.equal(d.observations[0].measured,null);assert.equal(d.observations[0].inputs.power_w,null);assert.throws(()=>E.normalize(d));});
  await test('Canonical SHA-256 ignores object key order but changes when measurements change',async()=>{assert.equal(await E.digest({a:1,b:2}),await E.digest({b:2,a:1}));assert.notEqual(await E.digest({a:1}),await E.digest({a:2}));assert.match(await E.digest(E.demo('har')),/^[a-f0-9]{64}$/);});

  function mount(storage=new Map([['waferflow-fab-v05','unchanged-fab'],['waferflow-memory-fab-v1','unchanged-plan']])){
    const {document:d}=parseHTML(files['evidence.html']),downloads=[];const proto=Object.getPrototypeOf(d.querySelector('select'));Object.defineProperty(proto,'value',{configurable:true,get(){return this.testValue??this.querySelector('option[selected]')?.getAttribute('value')??this.querySelector('option')?.getAttribute('value')??'';},set(v){this.testValue=String(v);}});
    const c=vm.createContext({document:d,console,crypto:webcrypto,TextEncoder,TextDecoder,Blob,URLSearchParams,location:{search:''},URL:{createObjectURL(b){downloads.push(b);return'blob:test'},revokeObjectURL(){}},setTimeout:()=>0,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)}});c.window=c;for(const name of ['memory-fab-engine.js','evidence-engine.js','evidence-app.js'])vm.runInContext(files[name],c,{filename:name});
    return{d,c,app:c.EvidenceApp,storage,downloads,click(selector){const el=d.querySelector(selector);assert(el);assert(!el.disabled);el.dispatchEvent(new Event('click',{bubbles:true}));},input(selector,value){const el=d.querySelector(selector);el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));}};
  }
  await test('Workspace starts without sample metrics or a verified manufacturing claim',()=>{const u=mount();assert.equal(u.app.snapshot().dataset,null);assert(u.d.querySelector('#freezePlan').disabled);assert(u.d.querySelector('#evidenceState').textContent.includes('미완료'));assert(u.d.querySelector('#resultContent').hidden);});
  await test('Full data → frozen fit → held-out validation workflow renders evidence and charts',async()=>{const u=mount();assert(await u.app.loadData(E.demo('har')));assert(await u.app.freezePlan());assert.equal(u.app.snapshot().result,null);assert(!u.d.querySelector('#evaluateButton').disabled);assert(await u.app.evaluate());assert.equal(u.app.snapshot().result.after.n,10);assert.equal(u.d.querySelectorAll('#lotResults tr').length,5);assert.equal(u.d.querySelectorAll('#observationRows tr').length,10);assert(u.d.querySelector('#parityPlot svg'));assert(u.d.querySelector('#residualPlot svg'));assert(u.d.querySelector('#resultNotice').textContent.includes('합성'));});
  await test('Changing thresholds marks the plan dirty and cannot change the frozen report',async()=>{const u=mount();await u.app.loadData(E.demo());await u.app.freezePlan();await u.app.evaluate();const before=u.app.snapshot().plan.config.limits.mae;u.input('#limitMae',999);assert(u.app.snapshot().dirty);assert(u.d.querySelector('#evaluateButton').disabled);assert.equal(u.app.bundle().plan.config.limits.mae,before);assert(await u.app.freezePlan());assert.equal(u.app.snapshot().plan.config.limits.mae,999);});
  await test('Empty or negative tolerance cannot silently become a valid acceptance rule',async()=>{const u=mount();await u.app.loadData(E.demo());u.input('#limitMae','');assert.equal(await u.app.freezePlan(),false);assert.equal(u.app.snapshot().plan,null);u.input('#limitMae',-1);assert.equal(await u.app.freezePlan(),false);assert(u.d.querySelector('#planError').textContent.length>0);});
  await test('Invalid file import is atomic and retains the previous dataset and result',async()=>{const u=mount();await u.app.loadData(E.demo());await u.app.freezePlan();await u.app.evaluate();const before=JSON.stringify(u.app.snapshot().result),id=u.app.snapshot().datasetHash;assert.equal(await u.app.loadData({schema:'wrong'}),false);assert.equal(JSON.stringify(u.app.snapshot().result),before);assert.equal(u.app.snapshot().datasetHash,id);});
  await test('Repeated evaluation marks the holdout exploratory even after dataset renaming',async()=>{const u=mount();const d=clone(E.demo());await u.app.loadData(d);await u.app.freezePlan();await u.app.evaluate();d.datasetId='renamed';await u.app.loadData(d);await u.app.freezePlan();await u.app.evaluate();assert(u.app.snapshot().result.exploratory);assert(u.d.querySelector('#resultNotice').textContent.includes('이전 평가'));});
  await test('Partial validation LOT reuse is detected when other training observations change',async()=>{const u=mount(),d=clone(E.demo());await u.app.loadData(d);await u.app.freezePlan();await u.app.evaluate();d.observations[0].measured+=1;await u.app.loadData(d);await u.app.freezePlan();await u.app.evaluate();assert(u.app.snapshot().result.exploratory);});
  await test('Validation history persists only hashes/counts and leaves existing fab storage intact',async()=>{const u=mount();await u.app.loadData(E.demo());await u.app.freezePlan();await u.app.evaluate();assert.equal(u.storage.get('waferflow-fab-v05'),'unchanged-fab');assert.equal(u.storage.get('waferflow-memory-fab-v1'),'unchanged-plan');const ledger=u.storage.get('waferflow-evidence-ledger-v1');assert(ledger);assert(!ledger.includes('DEMO'));assert(!ledger.includes('measured'));const v=mount(u.storage);await v.app.loadData(E.demo());await v.app.freezePlan();await v.app.evaluate();assert(v.app.snapshot().result.exploratory);});
  await test('Corrupt local validation history never silently implies an independent holdout',async()=>{const u=mount(new Map([['waferflow-evidence-ledger-v1','broken']]));await u.app.loadData(E.demo());await u.app.freezePlan();await u.app.evaluate();assert(u.app.snapshot().result.exploratory);assert.equal(u.app.snapshot().historyAvailable,false);});
  await test('New-condition preview identifies unsupported extrapolation',async()=>{const u=mount();await u.app.loadData(E.demo());await u.app.freezePlan();u.input('[data-predict="power_w"]',1400);const p=u.app.predict();assert(p.outOfDomain.includes('power_w'));assert(!p.usable);assert(u.d.querySelector('#predictionResult').classList.contains('error'));});
  await test('Review package import disregards cached results and marks prior evaluation reuse',async()=>{const u=mount();await u.app.loadData(E.demo());await u.app.freezePlan();await u.app.evaluate();const bundle=clone(u.app.bundle());bundle.result.criteriaMet=false;const v=mount();await v.app.loadData(bundle);assert.equal(v.app.snapshot().result,null);await v.app.freezePlan();await v.app.evaluate();assert(v.app.snapshot().result.criteriaMet);assert(v.app.snapshot().result.exploratory);});
  await test('Report escapes user labels and includes exact split, scope, metrics, hashes and observations',async()=>{const u=mount(),d=clone(E.demo());d.datasetId='<img src=x onerror=alert(1)>';d.origin.source='<script>private</script>';await u.app.loadData(d);await u.app.freezePlan();await u.app.evaluate();const report=u.app.reportHTML(),parsed=parseHTML(report).document;assert(!parsed.querySelector('script,img,iframe'));assert(report.includes('&lt;img'));assert(report.includes(u.app.snapshot().datasetHash));assert(report.includes('trainingLotIds'));assert(report.includes('validationLotIds'));assert(report.includes('전자서명'));assert(report.includes('DEMO-14-1'));assert(!u.d.querySelector('#datasetInfo img'));});
  await test('JSON and HTML downloads use evaluated evidence, not the pending draft',async()=>{const u=mount();await u.app.loadData(E.demo());await u.app.freezePlan();await u.app.evaluate();u.input('#limitMae',12345);u.click('#downloadBundle');u.click('#downloadReport');const data=JSON.parse(await u.downloads[0].text());assert.equal(data.plan.config.limits.mae,30);assert.equal(data.sourceVerified,false);assert.equal(data.manufacturingRelease,false);assert.equal(data.dataset.observations.length,30);assert((await u.downloads[1].text()).includes('검증 오차'));});
  await test('Only the latest asynchronous dataset load becomes active',async()=>{const u=mount();await Promise.all([u.app.loadData(E.demo('har')),u.app.loadData(E.demo('cvd'))]);assert.equal(u.app.snapshot().dataset.profile,'cvd');assert.equal(u.app.snapshot().busy,false);});
  await test('Tampered review package data or frozen-plan fingerprint cannot be silently accepted',async()=>{const u=mount();await u.app.loadData(E.demo());await u.app.freezePlan();await u.app.evaluate();const b=clone(u.app.bundle()),v=mount();b.dataset.observations[0].measured+=100;assert.equal(await v.app.loadData(b),false);assert.equal(v.app.snapshot().dataset,null);const c=clone(u.app.bundle());c.plan.config.limits.mae=999;assert.equal(await v.app.loadData(c),false);assert(v.d.querySelector('#evidenceFeedback').textContent.includes('지문'));});
  const result={total:tests.length,passed:tests.filter(t=>t.status==='passed').length,failed:tests.filter(t=>t.status==='failed').length,tests};await fs.writeFile(root+'/tests/evidence-results.json',JSON.stringify(result,null,2));return result;
}
