import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {Blob} from 'node:buffer';
import {parseHTML,Event} from './linkedom.worker.mjs';

export async function runFabTests(root){
  const tests=[],test=async(name,fn)=>{await fn();tests.push({name,status:'passed'});};
  const files=Object.fromEntries(await Promise.all(['cmos-lab.html','fab-engine.js','fab-app.js','fab-guide.js','fab-view.js','equipment-detail.js','vendor/three.js'].map(async f=>[f,await fs.readFile(root+'/'+f,'utf8')])));
  const ctx=vm.createContext({});vm.runInContext(files['fab-engine.js'],ctx);const E=ctx.FabEngine;
  let w=E.createWafer(),snapshots=[w];
  await test('117 ordered operations cover all 18 equipment types and 8 modules',()=>{assert.equal(E.route.length,117);assert.equal(new Set(E.route.map(s=>s.tool)).size,18);assert.equal(E.modules.length,8);E.route.forEach((s,i)=>assert.equal(s.index,i));});
  await test('Full reference CMOS route completes with nonnegative finite material and no warnings',()=>{for(const s of E.route){const result=E.execute(w);w=result.wafer;snapshots.push(w);assert.equal(w.cursor,s.index+1);assert.equal(result.warnings.length,0,s.name);for(const c of w.columns)for(const l of c)assert(Number.isFinite(l.nm)&&l.nm>=0,s.name);}assert.equal(E.summarize(w).films.PR.max,0);assert(E.summarize(w).films.W.max>100);assert(E.summarize(w).films.Al.max>400);assert.equal(w.dopants.length,6);});
  await test('Replay exactly reconstructs geometry, dopants, elapsed time and original timestamps',()=>{const restored=E.replay(w.id,w.records);assert.equal(JSON.stringify(restored),JSON.stringify(w));});
  await test('Processing does not mutate its input or prior history',()=>{const before=JSON.stringify(snapshots[31]);E.execute(snapshots[31],{time:2500});assert.equal(JSON.stringify(snapshots[31]),before);});
  await test('Thermal oxide growth consumes 0.44 nm Si per nm oxide',()=>{const i=E.route.findIndex(s=>s.tool==='oxidation'),before=E.summarize(snapshots[i]),after=E.summarize(snapshots[i+1]);assert(Math.abs((before.films.Si.mean-after.films.Si.mean)-.44*(after.films.SiO2.mean-before.films.SiO2.mean))<.002);});
  await test('Partial process at zero does not deposit spacer material',()=>{const i=E.route.findIndex(s=>s.op==='spacerDeposit');const result=E.process(snapshots[i],E.route[i],{},0);assert.equal(JSON.stringify(result.wafer.columns),JSON.stringify(snapshots[i].columns));assert.equal(result.wafer.cursor,i);});
  await test('PR remains after exposure and open regions clear only after development',()=>{const i=E.route.findIndex(s=>s.op==='expose');assert.equal(E.summarize(snapshots[i]).films.PR.mean,E.summarize(snapshots[i+1]).films.PR.mean);assert(E.summarize(snapshots[i+2]).films.PR.mean<E.summarize(snapshots[i+1]).films.PR.mean*.7);});
  await test('Underexposure propagates into PR residue and lower implant transmission',()=>{const i=E.route.findIndex(s=>s.op==='expose');let bad=E.execute(snapshots[i],{},'dose').wafer;const dev=E.execute(bad);assert(dev.warnings.some(a=>a.code==='PR_RESIDUE'));bad=E.execute(dev.wafer).wafer;assert(bad.dopants[0].transmission[120]<snapshots[i+3].dopants[0].transmission[120]);});
  await test('Etch respects the patterned mask and retains two finite-width gates',()=>{const i=E.route.findIndex(s=>s.name==='폴리 게이트 패턴 식각'),after=snapshots[i+1];assert(after.columns[40].some(l=>l.material==='Poly'));assert(!after.columns[60].some(l=>l.material==='Poly'&&l.nm>20));assert(E.summarize(after).gateCD>300&&E.summarize(after).gateCD<500);});
  await test('STI CMP reduces topography and preserves SiN stop layer',()=>{const i=E.route.findIndex(s=>s.stop==='SiN');assert(E.summarize(snapshots[i+1]).topography<E.summarize(snapshots[i]).topography);assert(E.summarize(snapshots[i+1]).films.SiN.mean>0);});
  await test('Vacuum interlock rejects processing without mutating wafer',()=>{const i=E.route.findIndex(s=>s.tool==='implant'),before=JSON.stringify(snapshots[i]);assert.throws(()=>E.execute(snapshots[i],{},'vacuum'),/INTERLOCK/);assert.equal(before,JSON.stringify(snapshots[i]));});
  await test('Out-of-order operation, invalid numbers, sample counts and unknown faults are rejected',()=>{assert.throws(()=>E.process(snapshots[0],E.route[3]));assert.throws(()=>E.execute(snapshots[0],{time:NaN}));assert.throws(()=>E.process(snapshots[0],E.route[0],{},NaN));assert.throws(()=>E.execute(snapshots[0],{},'unknown'));const s=E.route.find(s=>s.tool==='metrology');assert.throws(()=>E.recipeFor(s,{samples:5.5}));});
  await test('Implant dose and tilt affect the depth profile; anneal activates stored dopants',()=>{const i=E.route.findIndex(s=>s.tool==='implant'),a=E.execute(snapshots[i],{dose:1e13,tilt:0}).wafer,b=E.execute(snapshots[i],{dose:2e13,tilt:15}).wafer;assert.equal(b.dopants[0].dose,a.dopants[0].dose*2);assert(b.dopants[0].rp<a.dopants[0].rp);assert.equal(a.dopants[0].activation,0);assert(snapshots[15].dopants[0].activation>0);});
  await test('Metrology returns exactly the selected number of actual geometric sample sites',()=>{const s=E.route.find(s=>s.tool==='metrology'),r=E.execute(snapshots[s.index],{samples:9});assert.equal(r.wafer.lastMeasurement.sites.length,9);for(const site of r.wafer.lastMeasurement.sites)assert(Math.abs(site.surface_nm-E.height(r.wafer.columns[site.index]))<.001);});
  await test('Incomplete strip causes the next coating interlock',()=>{const i=E.route.findIndex(s=>s.op==='strip'),bad=E.execute(snapshots[i],{time:20,power:100});assert(bad.warnings.length);assert.throws(()=>E.execute(bad.wafer),/RESIST RESIDUE/);});
  await test('Partial silicidation retains unreacted Ni above NiSi and wet strip removes it',()=>{const i=E.route.findIndex(s=>s.op==='silicide'),partial=E.execute(snapshots[i],{time:5,temperature:400}).wafer;assert(E.summarize(partial).films.Ni.max>0);const full=E.execute(partial).wafer;assert.equal(E.summarize(full).films.Ni.max,0);assert(E.summarize(full).films.NiSi.mean>0);});

  const storage=new Map(),downloads=[];let clock=0,frames=new Map(),fid=0;
  function mount(){const {document:d}=parseHTML(files['cmos-lab.html']);
    const selectProto=Object.getPrototypeOf(d.querySelector('select'));Object.defineProperty(selectProto,'value',{get(){return this.testValue??this.querySelector('option[selected]')?.getAttribute('value')??this.querySelector('option')?.getAttribute('value')??''},set(v){this.testValue=String(v)},configurable:true});
    for(const input of d.querySelectorAll('input[type="checkbox"]'))input.checked=input.hasAttribute('checked');
    for(const dialog of d.querySelectorAll('dialog')){dialog.showModal=function(){this.setAttribute('open','')};dialog.close=function(){this.removeAttribute('open')};}
    const sandbox={document:d,console,Blob,URL:{createObjectURL(b){downloads.push(b);return 'blob:test'},revokeObjectURL(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout:(fn,ms)=>{if(ms===0)return setTimeout(fn,0);return 0;},clearTimeout(){},requestAnimationFrame:fn=>{frames.set(++fid,fn);return fid},cancelAnimationFrame:id=>frames.delete(id),performance:{now:()=>clock},addEventListener(){},devicePixelRatio:1};sandbox.window=sandbox;
    const c=vm.createContext(sandbox);vm.runInContext(files['fab-engine.js'],c);vm.runInContext(files['fab-view.js'],c);vm.runInContext(files['fab-guide.js'],c);vm.runInContext(files['fab-app.js'],c);
    const click=s=>{const el=d.querySelector(s);assert(el,s);assert(!el.disabled,s+' disabled');el.dispatchEvent(new Event('click',{bubbles:true}));};
    const input=(s,value)=>{const el=d.querySelector(s);el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));};
    const advance=n=>{for(let i=0;i<n;i++){clock+=100;const queue=[...frames.values()];frames.clear();queue.forEach(fn=>fn(clock));}};
    return {d,c,click,input,advance,app:c.FabApp};
  }
  let ui=mount();
  await test('Fab UI renders equipment, material section and all 117 routes without WebGL',()=>{assert.equal(ui.d.querySelectorAll('[data-step]').length,117);assert(ui.d.querySelector('#crossSection svg'));assert.equal(ui.d.querySelector('#operationName').textContent,'입고 웨이퍼 세정');assert(ui.d.querySelector('.webgl-fallback'));});
  await test('Process play/pause commits exactly once and preserves executed conditions',()=>{ui.input('#recipe-time',120);ui.click('#runButton');ui.advance(15);ui.click('#runButton');ui.advance(80);assert.equal(ui.app.snapshot().wafers[0].records.length,0);ui.click('#runButton');ui.advance(70);assert.equal(ui.app.snapshot().wafers[0].records.length,1);assert.equal(ui.app.snapshot().wafers[0].records[0].recipe.time,120);ui.advance(80);assert.equal(ui.app.snapshot().wafers[0].records.length,1);});
  await test('Completed operation stays editable, before/after can be inspected, fork preserves original',()=>{assert(!ui.d.querySelector('#recipe-time').disabled);ui.click('#beforeButton');assert.equal(ui.d.querySelector('#beforeButton').getAttribute('aria-pressed'),'true');ui.click('#forkButton');const state=ui.app.snapshot();assert.equal(state.wafers.length,2);assert.equal(state.wafers[0].records.length,1);assert.equal(state.wafers[1].records.length,0);assert.equal(state.wafers[1].parent.id,'W01');assert(!ui.d.querySelector('#recipe-time').disabled);});
  await test('Jump-to-process executes actual upstream operations and opens matching tool',async()=>{const i=E.route.findIndex(s=>s.name==='폴리 게이트 패턴 식각');ui.app.select(i);assert(ui.d.querySelector('#runButton').disabled);await ui.app.advance();const s=ui.app.snapshot();assert.equal(s.wafers.find(w=>w.id===s.active).records.length,i);assert.equal(ui.d.querySelector('#toolTitle').textContent,E.tools.etch.english);assert(!ui.d.querySelector('#runButton').disabled);});
  await test('Recipe range errors are visible and interlocks preserve committed history',()=>{ui.input('#recipe-time',99999);assert(ui.d.querySelector('#runFeedback').textContent.includes('범위'));const count=ui.app.snapshot().wafers[1].records.length;ui.click('#runButton');assert.equal(ui.app.snapshot().wafers[1].records.length,count);ui.input('#recipe-time',75);ui.d.querySelector('#faultSelect').value='vacuum';ui.d.querySelector('#faultSelect').dispatchEvent(new Event('change',{bubbles:true}));ui.click('#runButton');assert.equal(ui.app.snapshot().wafers[1].records.length,count);assert(ui.d.querySelector('#runFeedback').textContent.includes('VACUUM'));});
  await test('JSON export contains replayable records and import merges without overwriting',async()=>{ui.click('#exportButton');const data=JSON.parse(await downloads.at(-1).text());assert.equal(data.schema,'waferflow-fab-history-v1');ui.app.importData(data);assert.equal(ui.app.snapshot().wafers.length,4);assert.equal(new Set(ui.app.snapshot().wafers.map(w=>w.id)).size,4);});
  await test('Import rejects forged history order and invalid parameters atomically',()=>{const before=JSON.stringify(ui.app.snapshot().wafers),bad=ui.app.snapshot();bad.wafers[0].records[0].stepId='OP999';assert.throws(()=>ui.app.importData(bad));assert.equal(JSON.stringify(ui.app.snapshot().wafers),before);const invalid=ui.app.snapshot();invalid.wafers[0].records[0].recipe={};assert.throws(()=>ui.app.importData(invalid));});
  await test('CSV export contains actual records and recipe provenance',async()=>{ui.click('#csvButton');const csv=await downloads.at(-1).text();assert(csv.includes('topography_nm'));assert(csv.includes(E.VERSION));assert(csv.includes('OP001'));assert(csv.includes('120'));});
  await test('Reload reconstructs saved wafer history and equipment selection',()=>{const saved=ui.app.snapshot();frames.clear();ui=mount();assert.equal(JSON.stringify(ui.app.snapshot().wafers),JSON.stringify(saved.wafers));assert.equal(ui.app.snapshot().active,saved.active);});
  await test('Comparison aligns results at a common completed operation',()=>{ui.click('[data-tab="compare"]');assert(ui.d.querySelector('#comparePanel').textContent.includes('동일 공정 시점'));assert(ui.d.querySelector('#comparePanel table'));});
  await test('History selection displays recorded conditions in an editable draft; info dialog works',()=>{ui.click('[data-tab="history"]');ui.click('[data-history="0"]');assert.equal(ui.d.querySelector('#recipe-time').value,'120');assert(!ui.d.querySelector('#recipe-time').disabled);ui.click('#aboutButton');assert(ui.d.querySelector('#infoDialog').hasAttribute('open'));ui.click('#closeInfo');assert(!ui.d.querySelector('#infoDialog').hasAttribute('open'));});
  await test('Full-route import displays sampled measurement rows from the final process',()=>{const payload={schema:'waferflow-fab-history-v1',modelVersion:E.VERSION,wafers:[{id:'FULL',records:w.records}]};ui.app.importData(payload);assert.equal(ui.d.querySelectorAll('.measurement-details tbody tr').length,49);assert(ui.d.querySelector('.measurement-details summary').textContent.includes('표본 표준편차'));});
  await test('Continuous execution advances operations and stops at the completed route',async()=>{ui.click('#newWafer');ui.app.select(E.route.length-2);await ui.app.advance();ui.d.querySelector('#autoRun').checked=true;ui.d.querySelector('#speedSelect').value='8';ui.click('#runButton');ui.advance(25);const s=ui.app.snapshot();assert.equal(s.wafers.find(w=>w.id===s.active).records.length,117);assert.equal(ui.d.querySelector('#runState').textContent,'RECORDED');});
  await test('Equipment descriptions cover all tools, current process, parameters and sources without changing records',()=>{const records=JSON.stringify(ui.app.snapshot().wafers);for(const tool of Object.keys(E.tools)){const step=E.route.find(s=>s.tool===tool);ui.app.select(step.index);ui.click('#equipmentHelpButton');const dialog=ui.d.querySelector('#equipmentDialog');assert(dialog.hasAttribute('open'));assert.equal(ui.d.querySelector('#equipmentDialogTitle').textContent,E.tools[tool].name);assert(ui.d.querySelector('#equipmentDialogBody').textContent.includes(step.name));assert.equal(ui.d.querySelectorAll('.guide-steps li').length,3);assert.equal(ui.d.querySelectorAll('.guide-parts article').length,3);assert.equal(ui.d.querySelectorAll('.guide-parameters>div').length,Object.keys(E.tools[tool].fields).length);assert(ui.d.querySelector('.guide-references a').href.startsWith('https://'));assert(!ui.d.querySelector('#equipmentDialogBody').textContent.includes('undefined'));ui.click('#equipmentDialogDone');assert(!dialog.hasAttribute('open'));}assert.equal(JSON.stringify(ui.app.snapshot().wafers),records);});
  await test('Reading equipment help pauses an active process until explicit resume',()=>{ui.click('#newWafer');ui.d.querySelector('#autoRun').checked=false;ui.d.querySelector('#speedSelect').value='1';ui.input('#recipe-time',135);ui.click('#runButton');ui.advance(12);ui.click('#equipmentHelpButton');assert(ui.d.querySelector('#equipmentDialogBody').textContent.includes('135'));assert.equal(ui.d.querySelector('#runState').textContent,'PAUSED');assert(ui.d.querySelector('#equipmentDialogStatus').textContent.includes('일시 정지'));ui.advance(80);ui.click('#closeEquipmentDialog');ui.advance(80);let state=ui.app.snapshot();assert.equal(state.wafers.find(w=>w.id===state.active).records.length,0);ui.click('#runButton');ui.advance(65);state=ui.app.snapshot();assert.equal(state.wafers.find(w=>w.id===state.active).records.length,1);});
  await test('Editing a completed recipe preserves original evidence and runs a new branch with the changed value',()=>{const original=ui.app.snapshot(),source=original.wafers.find(w=>w.id===original.active),records=JSON.stringify(source.records),input=ui.d.querySelector('#recipe-time');ui.input('#recipe-time','');assert(!input.disabled);ui.input('#recipe-time',240);assert.equal(ui.d.querySelector('#recipe-time'),input);assert.equal(ui.d.querySelector('#recipe-time').value,'240');assert(ui.d.querySelector('#runButton').textContent.includes('새 실험'));assert.equal(JSON.stringify(ui.app.snapshot().wafers.find(w=>w.id===source.id).records),records);ui.click('#runButton');ui.advance(70);const result=ui.app.snapshot(),branch=result.wafers.find(w=>w.id===result.active);assert.notEqual(branch.id,source.id);assert.equal(branch.parent.id,source.id);assert.equal(ui.d.querySelector('#compareSelect').value,source.id);assert.equal(branch.records[0].recipe.time,240);assert.equal(JSON.stringify(result.wafers.find(w=>w.id===source.id).records),records);});
  await test('Completed recipe edits restore their original values or survive a reload without overwriting evidence',()=>{ui.input('#recipe-time',200);ui.click('#restoreRecordButton');assert.equal(ui.d.querySelector('#recipe-time').value,'240');ui.input('#recipe-time',260);const saved=ui.app.snapshot();frames.clear();ui=mount();assert.equal(ui.d.querySelector('#recipe-time').value,'260');assert(!ui.d.querySelector('#recipe-time').disabled);assert.equal(ui.app.snapshot().wafers.find(w=>w.id===saved.active).records[0].recipe.time,240);});
  await test('Paused recipe edits restart from the committed wafer and commit only the new settings',()=>{ui.click('#newWafer');ui.click('#runButton');ui.advance(35);assert(ui.d.querySelector('#recipe-time').disabled);ui.click('#runButton');assert(!ui.d.querySelector('#recipe-time').disabled);ui.input('#recipe-time','');ui.click('#runButton');assert.equal(ui.d.querySelector('#runState').textContent,'PAUSED');ui.input('#recipe-time',210);assert(ui.d.querySelector('#runButton').textContent.includes('다시 시작'));ui.click('#runButton');ui.advance(70);const s=ui.app.snapshot(),wafer=s.wafers.find(w=>w.id===s.active);assert.equal(wafer.records.length,1);assert.equal(wafer.records[0].recipe.time,210);assert.equal(wafer.records[0].seconds,210);});
  await test('Preview computes new conditions without advancing or overwriting the wafer and clears when edited',()=>{const original=ui.app.snapshot(),records=JSON.stringify(original.wafers.map(w=>w.records));ui.app.select(1);ui.input('#recipe-rpm',4000);ui.click('#previewButton');assert(ui.d.querySelector('#sectionStatus').textContent.includes('미리 계산'));assert(ui.d.querySelector('#viewContext').textContent.includes('미리 계산 결과'));assert(ui.d.querySelector('#materialLegend').textContent.includes('PR'));assert(!ui.d.querySelector('#beforeButton').disabled);assert.equal(JSON.stringify(ui.app.snapshot().wafers.map(w=>w.records)),records);ui.click('#beforeButton');assert(!ui.d.querySelector('#materialLegend').textContent.includes('PR'));ui.input('#recipe-rpm',3500);assert(!ui.d.querySelector('#sectionStatus').textContent.includes('미리 계산'));assert(!ui.d.querySelector('.preview-result-note'));});
  await test('Condition sweep recomputes independent recipes from one input wafer and exports its provenance',async()=>{ui.click('[data-tab="sweep"]');const before=JSON.stringify(ui.app.snapshot().wafers);ui.d.querySelector('#sweepLow').value='2000';ui.d.querySelector('#sweepHigh').value='4000';ui.click('#sweepRun');assert.equal(ui.d.querySelectorAll('[data-sweep-row]').length,5);ui.click('#exportSweep');const output=JSON.parse(await downloads.at(-1).text());assert.equal(output.schema,'waferflow-fab-sweep-v1');assert.equal(output.stepId,'OP002');assert.equal(output.field,'rpm');assert.equal(output.inputHistory.length,1);const input=E.replay(output.waferId,output.inputHistory);for(const row of output.rows){const result=E.process(input,E.route[1],row.recipe,1,output.fault);assert.equal(row.measure.value,result.metrics.films.PR.mean);}assert(output.rows[0].measure.value>output.rows.at(-1).measure.value);assert.equal(JSON.stringify(ui.app.snapshot().wafers),before);ui.click('[data-sweep-row="4"]');assert.equal(ui.d.querySelector('#recipe-rpm').value,'4000');assert(ui.d.querySelector('#sweepPanel').textContent.includes('OP002'));});
  await test('Sweep rejects reversed bounds and future-process preview is unavailable until upstream execution',()=>{ui.d.querySelector('#sweepLow').value='4500';ui.d.querySelector('#sweepHigh').value='2000';ui.click('#sweepRun');assert(ui.d.querySelector('#sweepHint').textContent.includes('시작값'));ui.app.select(10);assert(ui.d.querySelector('#previewButton').disabled);assert(ui.d.querySelector('#sweepRun').disabled);});
  await test('Sweep respects both the requested interval and supported parameter spacing',async()=>{ui.app.select(1);ui.click('[data-tab="sweep"]');ui.d.querySelector('#sweepLow').value='2050';ui.d.querySelector('#sweepHigh').value='4090';ui.click('#sweepRun');ui.click('#exportSweep');const output=JSON.parse(await downloads.at(-1).text());assert.equal(output.rows.length,5);for(const row of output.rows){assert(row.value>=2050&&row.value<=4090);assert.equal(row.value%100,0);}ui.d.querySelector('#sweepLow').value='2001';ui.d.querySelector('#sweepHigh').value='2099';ui.click('#sweepRun');assert.equal(ui.d.querySelectorAll('[data-sweep-row]').length,0);assert(ui.d.querySelector('#sweepHint').textContent.includes('입력 간격'));});
  await test('Cancelling an unfinished operation preserves committed history and editable draft while stopping auto-run',()=>{ui.app.select(1);ui.input('#recipe-rpm',3800);const original=JSON.stringify(ui.app.snapshot().wafers.map(w=>w.records));ui.d.querySelector('#autoRun').checked=true;ui.click('#runButton');ui.advance(35);assert(!ui.d.querySelector('#cancelRunButton').hidden);ui.click('#cancelRunButton');ui.advance(80);assert.equal(JSON.stringify(ui.app.snapshot().wafers.map(w=>w.records)),original);assert.equal(ui.d.querySelector('#recipe-rpm').value,'3800');assert(!ui.d.querySelector('#recipe-rpm').disabled);assert(!ui.d.querySelector('#autoRun').checked);assert(ui.d.querySelector('#cancelRunButton').hidden);ui.app.select(2);assert(ui.d.querySelector('#operationName').textContent.includes('소프트베이크'));});

  await test('Branch comparison aligns a chosen stage, traces executed recipe differences and exports reproducible profiles',async()=>{
    const start=E.execute(E.createWafer()).wafer,left=E.execute(start,{rpm:2000}).wafer,right=E.execute(start,{rpm:4000}).wafer;
    ui.app.importData({schema:'waferflow-fab-history-v1',modelVersion:E.VERSION,wafers:[{id:'COMPARE_A',records:left.records},{id:'COMPARE_B',records:right.records}]});
    ui.click('[data-tab="compare"]');ui.d.querySelector('#compareSelect').value='COMPARE_B';ui.d.querySelector('#compareSelect').dispatchEvent(new Event('change',{bubbles:true}));
    assert.equal(ui.d.querySelectorAll('.comparison-differences tbody tr').length,1);assert(!ui.d.querySelector('.compare-chart').outerHTML.includes('NaN'));
    ui.app.select(1);ui.input('#recipe-rpm',4500);ui.click('#exportComparison');const output=JSON.parse(await downloads.at(-1).text());
    assert.equal(output.schema,'waferflow-fab-comparison-v1');assert.equal(output.completedOperations,2);assert.equal(output.differences.length,1);assert.equal(output.differences[0].current,2000);assert.equal(output.differences[0].reference,4000);
    const a=E.replay(output.reference.waferId,output.reference.records),b=E.replay(output.current.waferId,output.current.records);
    assert.equal(output.profile.length,E.NX);output.profile.forEach((p,i)=>{assert.equal(p.reference_nm,E.height(a.columns[i]));assert.equal(p.current_nm,E.height(b.columns[i]));});
    ui.d.querySelector('#compareOperation').value='1';ui.d.querySelector('#compareOperation').dispatchEvent(new Event('change',{bubbles:true}));ui.click('#exportComparison');const earlier=JSON.parse(await downloads.at(-1).text());
    assert.equal(earlier.completedOperations,1);assert.equal(earlier.differences.length,0);assert.equal(earlier.reference.records.length,1);assert(earlier.profile.every(p=>p.current_nm===p.reference_nm));
  });

  await test('Bulk upstream calculation can stop at a saved checkpoint and resume from committed progress',async()=>{
    ui.click('#newWafer');ui.app.select(40);const promise=ui.app.advance();assert(!ui.d.querySelector('#cancelRunButton').hidden);ui.click('#cancelRunButton');await promise;
    let data=ui.app.snapshot(),wafer=data.wafers.find(w=>w.id===data.active);assert(wafer.records.length>0&&wafer.records.length<40);assert.equal(data.selected,wafer.records.length);assert(ui.d.querySelector('#runFeedback').textContent.includes('중단'));
    const recorded=JSON.stringify(wafer.records);ui.app.select(40);await ui.app.advance();data=ui.app.snapshot();wafer=data.wafers.find(w=>w.id===data.active);assert.equal(wafer.records.length,40);assert.equal(JSON.stringify(wafer.records.slice(0,JSON.parse(recorded).length)),recorded);
  });
  await test('Hiding the page pauses a running operation until explicitly resumed',()=>{
    ui.d.querySelector('#speedSelect').value='1';ui.click('#runButton');ui.advance(20);Object.defineProperty(ui.d,'hidden',{value:true,configurable:true});ui.d.dispatchEvent(new Event('visibilitychange'));assert.equal(ui.d.querySelector('#runState').textContent,'PAUSED');
    Object.defineProperty(ui.d,'hidden',{value:false,configurable:true});ui.d.dispatchEvent(new Event('visibilitychange'));ui.advance(90);let data=ui.app.snapshot();assert.equal(data.wafers.find(w=>w.id===data.active).records.length,40);ui.click('#runButton');ui.advance(70);data=ui.app.snapshot();assert.equal(data.wafers.find(w=>w.id===data.active).records.length,41);
  });

  await test('Experiment notes survive reload and export without altering results or injecting markup',async()=>{
    const before=JSON.stringify(ui.app.snapshot().wafers.map(w=>w.records));ui.click('#editExperiment');assert(ui.d.querySelector('#experimentDialog').hasAttribute('open'));
    ui.input('#experimentNameInput','<img src=x onerror=alert(1)> 비교');ui.input('#experimentNoteInput','=SUM(1,2)\n관찰: 원본 조건 유지');ui.d.querySelector('#experimentForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));
    assert(!ui.d.querySelector('#experimentDialog').hasAttribute('open'));assert(!ui.d.querySelector('#experimentTitle img'));assert(ui.d.querySelector('#experimentTitle').textContent.includes('<img'));
    let data=ui.app.snapshot(),wafer=data.wafers.find(w=>w.id===data.active);assert.equal(wafer.note,'=SUM(1,2)\n관찰: 원본 조건 유지');assert.equal(JSON.stringify(data.wafers.map(w=>w.records)),before);
    ui.click('#csvButton');const csv=await downloads.at(-1).text();assert(csv.includes('experiment_title'));assert(csv.includes("'=SUM(1,2)"));frames.clear();ui=mount();data=ui.app.snapshot();assert.equal(data.wafers.find(w=>w.id===data.active).note,wafer.note);
    const invalid=ui.app.snapshot();invalid.wafers[0].title={html:'<b>bad</b>'};const original=JSON.stringify(ui.app.snapshot().wafers);assert.throws(()=>ui.app.importData(invalid));assert.equal(JSON.stringify(ui.app.snapshot().wafers),original);
    const imported=JSON.parse(JSON.stringify(wafer));imported.id='CSV_GUARD';imported.note=' \t=1+1\n관찰: 원본 조건 유지';ui.app.importData({schema:'waferflow-fab-history-v1',modelVersion:E.VERSION,wafers:[imported]});ui.click('#csvButton');assert((await downloads.at(-1).text()).includes("' \t=1+1"));
  });

  await test('Invalid recipe fields identify their own error and corrections preserve committed records',()=>{
    ui.app.select(1);const before=JSON.stringify(ui.app.snapshot().wafers.map(w=>w.records));ui.input('#recipe-rpm','');assert.equal(ui.d.querySelector('#recipe-rpm').getAttribute('aria-invalid'),'true');assert(!ui.d.querySelector('#recipe-error-rpm').hidden);assert(ui.d.querySelector('#recipe-error-rpm').textContent.includes('입력'));
    ui.input('#recipe-rpm',99999);assert.equal(ui.d.querySelector('#recipe-rpm').getAttribute('aria-invalid'),'true');assert(ui.d.querySelector('#recipe-error-rpm').textContent.includes('범위'));
    ui.input('#recipe-rpm',3000);assert.equal(ui.d.querySelector('#recipe-rpm').getAttribute('aria-invalid'),'false');assert(ui.d.querySelector('#recipe-error-rpm').hidden);assert.equal(JSON.stringify(ui.app.snapshot().wafers.map(w=>w.records)),before);
  });

  await test('Result tabs support keyboard navigation and route search can return to the actual next operation',()=>{
    ui.click('[data-tab="metrics"]');const key=new Event('keydown',{bubbles:true,cancelable:true});key.key='End';ui.d.querySelector('#tab-metrics').dispatchEvent(key);
    assert.equal(ui.d.querySelector('#tab-compare').getAttribute('aria-selected'),'true');assert(!ui.d.querySelector('#comparePanel').hidden);assert(ui.d.querySelector('#metricsPanel').hidden);assert.equal(ui.d.querySelector('#comparePanel').getAttribute('aria-labelledby'),'tab-compare');
    ui.input('#routeSearch','NO_MATCH_999');assert(ui.d.querySelector('.route-no-results'));ui.click('#jumpCurrent');const data=ui.app.snapshot();assert.equal(data.selected,data.wafers.find(w=>w.id===data.active).records.length);assert.equal(ui.d.querySelector('#routeSearch').value,'');assert.equal(ui.d.querySelectorAll('[data-step]').length,117);
  });

  await test('Standalone report includes the complete committed experiment, escaped notes and units while excluding draft values',async()=>{
    const snapshot=ui.app.snapshot(),wafer=snapshot.wafers.find(w=>w.id===snapshot.active);ui.app.select(1);ui.input('#recipe-rpm',4300);ui.click('#previewButton');ui.click('#reportButton');const html=await downloads.at(-1).text(),report=parseHTML(html).document;
    assert.equal(report.querySelectorAll('.history tbody tr').length,wafer.records.length);assert.equal(report.querySelectorAll('script,img,iframe').length,0);assert(report.querySelector('h1').textContent.includes('<img'));assert(report.querySelector('.memo').textContent.includes('관찰: 원본 조건 유지'));
    assert(report.querySelector('.history').textContent.includes('rpm'));assert(!report.querySelector('.history').textContent.includes('4,300'));assert(!html.includes('NaN'));assert(report.querySelector('footer').textContent.includes('JSON'));
    assert.equal(JSON.stringify(ui.app.snapshot().wafers.map(w=>w.records)),JSON.stringify(snapshot.wafers.map(w=>w.records)));
  });

  // Real Three.js geometries with only the renderer/canvas drawing stubbed: no GPU/visual claims.
  const d=ui.d,c=ui.c,create=d.createElement.bind(d);d.createElement=tag=>{const el=create(tag);if(tag==='canvas'){const gradient={addColorStop(){}};el.getContext=()=>({fillRect(){},fillText(){},strokeRect(){},beginPath(){},arc(){},fill(){},stroke(){},createLinearGradient:()=>gradient,createRadialGradient:()=>gradient});el.setPointerCapture=()=>{};}return el;};
  c.ResizeObserver=class{constructor(fn){this.fn=fn}observe(){this.fn()}disconnect(){}};
  c.AbortController=class{constructor(){this.signal={aborted:false}}abort(){this.signal.aborted=true}};
  vm.runInContext(files['vendor/three.js'],c);class Renderer{constructor(){this.domElement=d.createElement('canvas');this.shadowMap={}}setPixelRatio(){}setClearColor(){}setSize(){}render(){}dispose(){}}c.THREE.WebGLRenderer=Renderer;
  vm.runInContext(files['equipment-detail.js'],c);vm.runInContext(files['fab-view.js'],c);
  const host=d.querySelector('#fabViewport');Object.defineProperty(host,'clientWidth',{value:1100});Object.defineProperty(host,'clientHeight',{value:500});const inspections=[],contextLosses=[],viewport=c.FabViewport.mount(host,{onInspect:step=>inspections.push(step.id),onContextLoss:()=>contextLosses.push('lost')});
  await test('All 18 equipment scenes mount and contain finite geometry and transforms',()=>{for(const tool of Object.keys(E.tools)){const s=E.route.find(s=>s.tool===tool);viewport.select(s);viewport.update({wafer:snapshots[s.index],running:true,phase:'process',progress:.5});ui.advance(2);assert.equal(viewport.parts().length,3);viewport.scene.traverse(o=>{assert([o.position.x,o.position.y,o.position.z].every(Number.isFinite));if(o.geometry?.attributes.position)assert([...o.geometry.attributes.position.array].every(Number.isFinite));});}});
  await test('Implant and CMP use vertical and face-down wafer orientations',()=>{viewport.select(E.route.find(s=>s.tool==='implant'));viewport.update({wafer:w,running:false,phase:'process',progress:.5});ui.advance(2);assert(Math.abs(viewport.wafer.rotation.z+Math.PI/2)<1e-6);viewport.select(E.route.find(s=>s.tool==='cmp'));viewport.update({wafer:w,running:false,phase:'process',progress:.5});ui.advance(2);assert(Math.abs(viewport.wafer.rotation.x-Math.PI)<1e-6);});
  await test('Real equipment raycast opens help; rotation drags and empty floor clicks do not',()=>{viewport.select(E.route.find(s=>s.tool==='cmp'));viewport.update({wafer:w,running:false,phase:'process',progress:.5});ui.advance(80);viewport.scene.updateMatrixWorld(true);viewport.viewCamera.updateMatrixWorld(true);const canvas=viewport.renderer.domElement;canvas.getBoundingClientRect=()=>({left:0,top:0,width:1100,height:500});const point=new c.THREE.Vector3(0,.8,1.68).project(viewport.viewCamera),x=(point.x+1)*550,y=(1-point.y)*250;const emit=(name,props)=>{const event=new Event(name,{bubbles:true});Object.assign(event,{pointerId:1,button:0,isPrimary:true},props);canvas.dispatchEvent(event);};const tap=(px,py)=>{emit('pointerdown',{clientX:px,clientY:py});emit('pointerup',{clientX:px,clientY:py});};tap(x,y);assert.equal(inspections.length,1);emit('pointerdown',{clientX:x,clientY:y});emit('pointermove',{clientX:x+60,clientY:y});emit('pointermove',{clientX:x,clientY:y});emit('pointerup',{clientX:x,clientY:y});assert.equal(inspections.length,1);tap(1099,1);assert.equal(inspections.length,1);emit('pointerdown',{clientX:x,clientY:y});emit('pointercancel',{});emit('pointerup',{clientX:x,clientY:y});assert.equal(inspections.length,1);emit('keydown',{key:'Enter',repeat:false});assert.equal(inspections.length,2);emit('keydown',{key:'Enter',repeat:true});assert.equal(inspections.length,2);});
  await test('Handling curves join continuously and pause freezes moving equipment',()=>{const curves=c.FabViewport.motion;for(const [a,b] of [['idle','load'],['load','condition'],['condition','process'],['process','unload'],['unload','idle']]){const end=curves(a,a==='idle'?0:1),start=curves(b,0);for(const k of ['travel','rise','lower','orientation','closed','nozzle','processing'])assert(Math.abs(end[k]-start[k])<1e-9,a+' to '+b+' '+k);}for(const p of [0,.01,.5,.99,1])for(const value of Object.values(curves('load',p)))assert(Number.isFinite(value)&&value>=0&&value<=1);viewport.select(E.route.find(s=>s.tool==='coat'));viewport.update({wafer:w,running:true,phase:'process',progress:.4,speed:1});ui.advance(3);viewport.update({wafer:w,running:false,phase:'process',progress:.4,speed:1});ui.advance(1);const position=viewport.wafer.position.clone(),rotation=viewport.wafer.rotation.clone();ui.advance(20);assert.equal(viewport.wafer.position.distanceTo(position),0);assert.equal(viewport.wafer.rotation.y,rotation.y);});
  await test('Wafer transport has smooth departure/arrival and returns to the same load port',()=>{viewport.select(E.route.find(s=>s.tool==='implant'));const pose=(phase,p)=>{viewport.update({wafer:w,running:false,phase,progress:p});ui.advance(1);return viewport.wafer.position.clone();};const home=pose('idle',0),early=pose('load',.001),start=pose('load',0);assert(home.distanceTo(start)<1e-9);assert(early.distanceTo(start)<.0001);const seated=pose('load',1),nearly=pose('load',.999);assert(seated.distanceTo(nearly)<.0001);assert(seated.distanceTo(pose('condition',0))<1e-9);assert(seated.distanceTo(pose('unload',0))<1e-9);assert(home.distanceTo(pose('unload',1))<1e-9);});
  await test('Exposure and probe stage hold still during contact and move only between sites',()=>{const sample=c.FabViewport.stageMotion;for(let i=0;i<4;i++){const a=sample(i*.225+.225*.55),b=sample(i*.225+.225*.72);assert.equal(a.x,b.x);assert.equal(a.z,b.z);assert(a.contact>.99&&b.contact>.99);const moving=sample(i*.225+.225*.15);assert.equal(moving.contact,0);}const end=sample(1);assert(Math.abs(end.x)<1e-12);assert(Math.abs(end.z)<1e-12);assert.equal(end.contact,0);});
  await test('Reopening the same equipment preserves geometry and camera instead of rebuilding it',()=>{const step=E.route.find(s=>s.tool==='scanner');viewport.select(step);const children=[...viewport.scene.children];viewport.camera('top');ui.advance(60);const position=viewport.viewCamera.position.clone();viewport.select(step);ui.advance(1);assert(children.every((o,i)=>o===viewport.scene.children[i]));assert(viewport.viewCamera.position.distanceTo(position)<.01);});
  await test('Equipment camera and cutaway modes can switch without corrupting scene',()=>{for(const mode of ['equipment','top','wafer',0,1,2]){viewport.camera(mode);viewport.cutaway(false);ui.advance(3);viewport.cutaway(true);}assert(viewport.scene.environment.isDataTexture);});
  await test('CMP wafer rotates with the carrier, freezes on pause and handles context loss without dropping the scene',()=>{
    viewport.select(E.route.find(s=>s.tool==='cmp'));viewport.update({wafer:w,running:true,phase:'process',progress:.5,speed:1});ui.advance(2);const initial=viewport.wafer.rotation.y;ui.advance(3);assert.notEqual(viewport.wafer.rotation.y,initial);
    viewport.update({wafer:w,running:false,phase:'process',progress:.5,speed:1});ui.advance(1);const stopped=viewport.wafer.rotation.y;ui.advance(5);assert.equal(viewport.wafer.rotation.y,stopped);
    const canvas=viewport.renderer.domElement;canvas.dispatchEvent(new Event('webglcontextlost',{cancelable:true}));assert.equal(contextLosses.length,1);assert(host.querySelector('.webgl-recovery'));viewport.update({wafer:w,running:true,phase:'process',progress:.5,speed:1});ui.advance(5);assert.equal(viewport.wafer.rotation.y,stopped);
    canvas.dispatchEvent(new Event('webglcontextrestored'));assert(!host.querySelector('.webgl-recovery'));ui.advance(3);assert.notEqual(viewport.wafer.rotation.y,stopped);
  });
  await test('Disposing the viewport releases every remaining geometry, texture and input listener exactly once',()=>{
    const resources=new Set(),disposed=[];viewport.scene.traverse(o=>{if(o.geometry)resources.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material])if(m){resources.add(m);for(const value of Object.values(m))if(value?.isTexture)resources.add(value);}});resources.add(viewport.scene.environment);resources.forEach(r=>r.addEventListener('dispose',()=>disposed.push(r)));
    const canvas=viewport.renderer.domElement,count=inspections.length;viewport.dispose();viewport.dispose();assert.equal(disposed.length,resources.size);assert.equal(new Set(disposed).size,resources.size);assert.equal(canvas.parentNode,null);const key=new Event('keydown');key.key='Enter';canvas.dispatchEvent(key);assert.equal(inspections.length,count);
  });
  const result={date:new Date().toISOString(),model:E.VERSION,passed:tests.length,scope:'Deterministic process model, DOM behavior and real Three.js scene geometry using a renderer stub. Browser layout and GPU appearance were not tested.',tests};await fs.writeFile(root+'/tests/fab-results.json',JSON.stringify(result,null,2));return result;
}
