import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { Blob } from 'node:buffer';
import { parseHTML, Event } from './linkedom.worker.mjs';

// DOM behavior tests only: this does not render CSS or replace browser visual QA.
export async function runTests(rootPath) {
  const tests=[];
  const test=async(name,fn)=>{await fn();tests.push({name,status:'passed'});};
  const files=Object.fromEntries(await Promise.all(['index.html','engine.js','visuals.js','app.js'].map(async f=>[f,await fs.readFile(`${rootPath}/${f==='index.html'?'photo-lab.html':f}`,'utf8')])));
  const modelContext=vm.createContext({});vm.runInContext(files['engine.js'],modelContext);const E=modelContext.WaferEngine;
  await test('Same recipe and seed reproduce every die exactly',()=>assert.equal(JSON.stringify(E.simulate(E.defaults)),JSON.stringify(E.simulate(E.defaults))));
  await test('All missions are solvable and improve over their baseline',()=>{for(const m of E.missions){const base=E.simulate(m.defaults,m.id),good=E.simulate(E.defaults,m.id);assert(good.passed);assert(good.yield>base.yield+10);}});
  await test('Oxidation increases with time and temperature',()=>{const b=E.simulate(E.defaults);assert(E.simulate({...E.defaults,temperature:1050}).oxide>b.oxide);assert(E.simulate({...E.defaults,oxidationTime:60}).oxide>b.oxide);});
  await test('Spin speed changes PR thickness and etching balances residue with damage',()=>{assert(E.simulate({...E.defaults,rpm:4000}).pr<E.simulate(E.defaults).pr);const short=E.simulate({...E.defaults,etchTime:30}),good=E.simulate(E.defaults),long=E.simulate({...E.defaults,etchTime:150});assert(short.yield<good.yield);assert(long.yield<good.yield);assert(short.dies.some(d=>d.residue>20));});
  await test('Every control influences the model',()=>{for(const [key,f] of Object.entries(E.fields)){const a=E.simulate(E.defaults),b=E.simulate({...E.defaults,[key]:f.max});assert.notEqual(JSON.stringify(a.dies)+a.cost+a.pr,JSON.stringify(b.dies)+b.cost+b.pr,key);}});
  await test('Parameter bounds and invalid input produce finite, consistent results',()=>{for(const value of [NaN,Infinity,-99999,99999]){const p=Object.fromEntries(Object.keys(E.fields).map(k=>[k,value]));const r=E.simulate(p);assert(Number.isFinite(r.yield));assert(r.yield>=0&&r.yield<=100);assert.equal(r.bad+r.good,r.total);assert.equal(r.histogram.counts.reduce((a,b)=>a+b,0),r.total);assert.equal(r.distribution.reduce((a,b)=>a+b.count,0),r.bad);}});
  await test('Statistical outputs contain actual recomputed samples',()=>{const a=E.monteCarlo(E.defaults,'residue');assert.equal(a.samples.length,30);assert(a.interval[0]<=a.mean&&a.mean<=a.interval[1]);assert(a.sd>0);const sweep=E.sweep(E.defaults,'residue','dose');assert.equal(sweep.length,9);for(const p of sweep)assert.equal(p.yield,E.simulate({...E.defaults,dose:p.value},'residue').yield);});

  let stored=new Map(),downloads=[],timers=[],frames=new Map(),frameId=0;
  function mount(){
    const {document}=parseHTML(files['index.html']);
    for(const d of document.querySelectorAll('dialog')){d.showModal=function(){this.setAttribute('open','')};d.close=function(){this.removeAttribute('open')};}
    for(const input of document.querySelectorAll('input')){input.setCustomValidity=function(text){this.testValidity=text};input.reportValidity=()=>true;}
    // linkedom intentionally has no writable HTMLSelectElement.value implementation.
    for(const select of document.querySelectorAll('select'))Object.defineProperty(select,'value',{get(){return this.testValue||this.querySelector('option[selected]')?.getAttribute('value')||this.querySelector('option')?.getAttribute('value')||''},set(v){this.testValue=v},configurable:true});
    const sandbox={document,console,crypto:{randomUUID},Blob,URL:{createObjectURL(blob){downloads.push(blob);return 'blob:test'},revokeObjectURL(){}},localStorage:{getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v)},setTimeout:(fn,ms)=>{timers.push({fn,ms});return timers.length},clearTimeout(){},requestAnimationFrame:fn=>{frames.set(++frameId,fn);return frameId},cancelAnimationFrame:id=>frames.delete(id),performance:{now:()=>0}};
    sandbox.window=sandbox;const ctx=vm.createContext(sandbox);for(const f of ['engine.js','visuals.js','app.js'])vm.runInContext(files[f],ctx,{filename:f});
    const click=selector=>{const element=document.querySelector(selector);assert(element,selector);element.dispatchEvent(new Event('click',{bubbles:true}));};
    const input=(selector,value)=>{const el=document.querySelector(selector);el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));};
    const completeRun=async()=>{const task=timers.find(t=>t.ms===650);assert(task);timers=timers.filter(t=>t!==task);task.fn();await Promise.resolve();await Promise.resolve();};
    return {document,ctx,click,input,completeRun};
  }
  let app=mount(),d=app.document;
  await test('Initial UI renders exposure, all 8 stages, 3 views and baseline',()=>{assert.equal(d.querySelectorAll('[data-stage]').length,8);assert.equal(d.querySelectorAll('[data-view]').length,3);assert(d.querySelector('#visualization svg'));assert(d.querySelector('#stageName').textContent.includes('노광'));assert.equal(d.querySelector('#yieldValue').textContent,'39.0');});
  await test('Exposure retains PR; development removes exposed regions',()=>{app.click('[data-view="section"]');assert(d.querySelector('#visualization').textContent.includes('아직 제거되지 않음'));app.click('[data-stage="5"]');assert(d.querySelector('#visualization').textContent.includes('현상 부족'));app.click('[data-view="scene"]');});
  await test('Recipe preview updates while executed KPI stays unchanged',()=>{app.click('[data-stage="3"]');app.input('#param-dose',100);assert(d.querySelector('#draftStatus').textContent.includes('변경됨'));assert.equal(d.querySelector('#yieldValue').textContent,'39.0');app.click('[data-stage="5"]');app.input('#param-developTime',60);});
  await test('Run snapshots values, hypothesis and computed result',async()=>{app.input('#hypothesis','노광량과 현상 시간을 기준으로 복원하여 잔사를 줄인다.');app.click('#runSimulation');assert(d.querySelector('#runSimulation').disabled);await app.completeRun();assert(!d.querySelector('#runSimulation').disabled);assert.equal(d.querySelector('#yieldValue').textContent,'97.5');assert(d.querySelector('#historyBody').textContent.includes('RUN 001'));assert(d.querySelector('#goalTitle').textContent.includes('목표 달성'));});
  await test('Map click reveals matching die measurement, A/B SVG IDs are unique',()=>{app.click('[data-view="map"]');app.click('[data-die="0"]');assert(d.querySelector('#dieInspector').textContent.includes('식각'));app.click('#compareToggle');const ids=[...d.querySelectorAll('#visualization [id]')].map(el=>el.id);assert.equal(new Set(ids).size,ids.length);assert.equal(d.querySelectorAll('#visualization svg').length,2);});
  await test('Recipe saves and notebook escapes user strings',()=>{app.click('#saveRecipe');app.input('#recipeName','<img src=x onerror=alert(1)>');d.querySelector('#saveForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));app.click('[data-page="notebook"]');assert(d.querySelector('#savedRecipes').textContent.includes('<img'));assert.equal(d.querySelectorAll('#savedRecipes img').length,0);assert(d.querySelector('#reportCards').textContent.includes('잔사를 줄인다'));});
  await test('CSV and HTML export contain results with escaped notes',async()=>{app.click('#exportAll');assert(downloads.length>0);const csv=await downloads.at(-1).text();assert(csv.includes('97.5'));assert(csv.includes('bakeTemp'));app.click('[data-page="lab"]');app.click('#exportReport');const html=await downloads.at(-1).text();assert(html.includes('97.5'));assert(html.includes('교육용 합성 모델'));});
  await test('Analysis computes 9 sweep rows and 30 seed samples',async()=>{app.click('[data-page="analytics"]');assert.equal(d.querySelectorAll('[data-sweep]').length,9);assert(d.querySelector('#analysisOutput').textContent.includes('30회'));app.click('#exportStats');const data=JSON.parse(await downloads.at(-1).text());assert.equal(data.repeat.samples.length,30);assert.equal(data.sweep.length,9);});
  await test('Sweep applies its snapshot to the correct stage',()=>{app.click('[data-sweep="4"]');assert.equal(d.querySelector('#param-dose').value,'110');assert(d.querySelector('#draftStatus').textContent.includes('변경됨'));});
  await test('Mission switching isolates records and restore returns exact recipe',()=>{app.click('[data-page="missions"]');app.click('[data-mission="edge"]');assert(!d.querySelector('#historyBody').textContent.includes('RUN 001'));assert.equal(d.querySelector('#yieldValue').textContent,'56.8');app.click('[data-page="notebook"]');app.click('#reportCards [data-restore]');assert.equal(d.querySelector('#yieldValue').textContent,'97.5');});
  await test('Reload restores local recipe, experiment and saved library',()=>{app=mount();d=app.document;assert.equal(d.querySelector('#yieldValue').textContent,'97.5');app.click('[data-page="notebook"]');assert.equal(d.querySelectorAll('.saved-recipe').length,1);assert.equal(d.querySelectorAll('.report-card').length,1);});
  await test('Unexecuted edits stay previews after reload',()=>{app.click('[data-page="lab"]');app.click('[data-stage="3"]');app.input('#param-dose',145);app=mount();d=app.document;assert.equal(d.querySelector('#param-dose').value,'145');assert.equal(d.querySelector('#yieldValue').textContent,'97.5');assert(d.querySelector('#draftStatus').textContent.includes('변경됨'));});
  await test('Playback advances through all stages and stops',()=>{app.click('[data-page="lab"]');app.click('#playProcess');for(const t of [0,2700,5300,7900,10500,13100,15700,18300,20900]){const callbacks=[...frames.values()];frames.clear();callbacks.forEach(fn=>fn(t));}assert.equal(d.querySelector('#stageFraction').textContent,'8 / 8');assert(d.querySelector('#playbackDescription').textContent.includes('완료'));assert.equal(d.querySelector('#playProcess').getAttribute('aria-label'),'공정 순서 재생');});
  await test('Research links and all source references render',()=>{app.click('[data-page="research"]');assert(d.querySelector('#researchContent').textContent.includes('비공개 IP'));assert(d.querySelectorAll('#researchContent a').length>=10);});
  // Exercise the real Three.js scene graph and timeline with only WebGL/Canvas rendering stubbed.
  // These assertions do not validate GPU rendering, lighting, typography or visual appearance.
  let machineClock=0;
  const createOriginal=d.createElement.bind(d);
  d.createElement=(tag)=>{const el=createOriginal(tag);if(tag==='canvas'){
    const gradient={addColorStop(){}};
    const context={fillRect(){},fillText(){},strokeRect(){},beginPath(){},arc(){},fill(){},stroke(){},createLinearGradient:()=>gradient,createRadialGradient:()=>gradient};
    el.getContext=()=>context;el.setPointerCapture=()=>{};el.getBoundingClientRect=()=>({left:0,top:0,width:1400,height:570});
  }return el;};
  const viewport=d.querySelector('#machineViewport');Object.defineProperty(viewport,'clientWidth',{value:1400});Object.defineProperty(viewport,'clientHeight',{value:570});
  app.ctx.ResizeObserver=class{constructor(fn){this.fn=fn}observe(){this.fn()}disconnect(){}};
  app.ctx.AbortController=class{constructor(){this.signal={aborted:false}}abort(){this.signal.aborted=true}};
  app.ctx.IntersectionObserver=class{constructor(fn){this.fn=fn}observe(){this.fn([{isIntersecting:true}])}disconnect(){}};
  vm.runInContext(await fs.readFile(`${rootPath}/vendor/three.js`,'utf8'),app.ctx,{filename:'three.js'});
  class RendererStub{constructor(){this.domElement=d.createElement('canvas');this.shadowMap={};this.capabilities={getMaxAnisotropy:()=>4}}setPixelRatio(){}setClearColor(){}setSize(){}render(scene,camera){scene.updateMatrixWorld();camera.updateMatrixWorld()}dispose(){}}
  app.ctx.THREE.WebGLRenderer=RendererStub;
  vm.runInContext(await fs.readFile(`${rootPath}/equipment-detail.js`,'utf8'),app.ctx,{filename:'equipment-detail.js'});
  vm.runInContext(await fs.readFile(`${rootPath}/machine.js`,'utf8'),app.ctx,{filename:'machine.js'});
  const machine=app.ctx.WaferMachine;
  const advance=count=>{for(let i=0;i<count;i++){machineClock+=100;const cbs=[...frames.values()];frames.clear();cbs.forEach(fn=>fn(machineClock));}};
  await test('Equipment scene contains eight real 3D stations and one workpiece',()=>{assert(machine);assert.equal(machine.stations.length,8);assert.equal(d.querySelectorAll('.station-label').length,8);assert(machine.wafer.isGroup);let meshCount=0;machine.scene.traverse(o=>{if(o.isMesh){meshCount++;assert(o.geometry.attributes.position.count>0);}});assert(meshCount>250);});
  await test('3D transfer moves a single wafer from load port onto the first module',()=>{app.click('[data-page="lab"]');app.click('#machineOverview');app.click('#machineReset');advance(1);assert.equal(machine.getState().position[0],-10);app.click('#machinePlay');advance(45);const s=machine.getState();assert.equal(s.active,0);assert.equal(s.phase,'PROCESS');assert(Math.abs(s.position[0]+6)<.01);assert(Math.abs(s.position[2]+3)<.01);});
  await test('Equipment pause freezes wafer position and spin',()=>{app.click('#machinePlay');const before=JSON.stringify(machine.getState().position),spin=machine.wafer.rotation.y,time=machine.getState().elapsed;advance(15);assert.equal(JSON.stringify(machine.getState().position),before);assert.equal(machine.wafer.rotation.y,spin);assert.equal(machine.getState().elapsed,time);});
  await test('Manual stage selection controls both real scene and detail view',()=>{app.click('[data-stage="1"]');advance(1);assert.equal(machine.getState().active,1);assert.equal(d.querySelector('#stageName').textContent,'감광액 도포');assert(!machine.getState().playing);});
  await test('Cutaway and camera controls change actual scene properties',()=>{const initial=machine.stations[0].shellMat.opacity;app.click('#machineCutaway');assert.notEqual(machine.stations[0].shellMat.opacity,initial);assert(machine.stations[0].shell.children[0].castShadow);app.click('[data-camera="close"]');advance(12);assert(d.querySelector('#machineViewLabel').textContent.includes('내부 확대'));app.click('#machineCutaway');assert(!machine.stations[0].shell.children[0].castShadow);});
  await test('Equipment tab isolates only the selected machine',()=>{app.click('[data-equipment="5"]');advance(1);assert.equal(machine.getState().displayMode,'detail');assert.equal(machine.stations.filter(s=>s.group.visible).length,1);assert(machine.stations[5].group.visible);assert.equal(d.querySelector('#machineEquipmentTitle').textContent,'현상기');});
  await test('A single equipment run stops locally and Next opens the next device',()=>{app.click('#machinePlay');advance(120);assert.equal(machine.getState().active,5);assert(!machine.getState().playing);assert.equal(d.querySelector('#machinePhase').textContent,'이 장비의 가공 완료');app.click('#machineNext');advance(1);assert.equal(machine.getState().active,6);assert.equal(d.querySelector('#machineEquipmentTitle').textContent,'플라즈마 식각기');});
  await test('Complete 3D cycle visits every processing module and finishes',()=>{app.click('#machineOverview');app.click('#machineReset');app.click('#machinePlay');const seen=new Set();for(let i=0;i<910;i++){advance(1);seen.add(machine.getState().active);}assert.equal(seen.size,8);assert.equal(machine.getState().active,7);assert(!machine.getState().playing);assert.equal(machine.getState().elapsed,88);assert.equal(d.querySelector('#machinePhase').textContent,'전체 가공 완료');});
  await test('Scene transforms and model geometry remain finite after a full cycle',()=>{machine.scene.traverse(o=>{for(const value of [...o.position.toArray(),...o.rotation.toArray().slice(0,3),...o.scale.toArray()])assert(Number.isFinite(value));if(o.geometry?.attributes.position)assert([...o.geometry.attributes.position.array].every(Number.isFinite));});});
  await test('Every equipment exposes three working component explanations',()=>{for(let i=0;i<8;i++){app.click('[data-equipment="'+i+'"]');advance(2);assert.equal(d.querySelectorAll('[data-component]').length,3);app.click('[data-component="2"]');assert.equal(machine.getState().componentIndex,2);assert.equal(d.querySelector('#componentName').textContent,machine.stations[i].components[2].name);assert(d.querySelector('#componentDescription').textContent.length>10);for(const line of d.querySelectorAll('[data-leader]'))for(const a of ['x1','y1','x2','y2'])assert(Number.isFinite(Number(line.getAttribute(a))));}});
  await test('Component visibility preference survives equipment switching',()=>{app.click('#machineAnnotationsToggle');assert(d.querySelector('#machineAnnotations').hidden);app.click('[data-equipment="1"]');assert(d.querySelector('#machineComponentInfo').hidden);app.click('#machineAnnotationsToggle');assert(!d.querySelector('#machineAnnotations').hidden);assert(!d.querySelector('#machineComponentInfo').hidden);});
  await test('Scrubbing rewinds actual wafer motion and resumes from the chosen position',()=>{app.input('#machineScrubber','100');advance(2);assert.equal(machine.getState().phase,'TRANSFER');assert(!machine.getState().playing);assert(machine.robot.visible);const t=machine.getState().elapsed;advance(5);assert.equal(machine.getState().elapsed,t);app.click('#machinePlay');advance(2);assert(machine.getState().elapsed>t);app.input('#machineScrubber','700');advance(2);assert.equal(machine.getState().phase,'PROCESS');assert(!machine.robot.visible);assert(!machine.getState().playing);assert(Math.abs(machine.getState().elapsed-18.7)<1e-6);});
  await test('Phase shortcuts update process state and preserve completed material through inspection',()=>{app.click('[data-phase-position="0.96"]');advance(2);assert.equal(machine.getState().phase,'INSPECT');assert(d.querySelector('[data-phase-position="0.96"]').classList.contains('active'));app.click('[data-phase-position="0"]');advance(2);assert.equal(machine.getState().phase,'TRANSFER');assert.equal(machine.getState().phaseProgress,0);});
  await test('Global scrubbing selects the matching stage and handles both timeline boundaries',()=>{app.click('#machineOverview');machine.seek(.7);advance(2);assert.equal(machine.getState().active,5);assert.equal(d.querySelector('#stageName').textContent,E.stages[5].name);machine.seek(1);advance(2);assert.equal(machine.getState().elapsed,88);assert.equal(machine.getState().phase,'INSPECT');machine.seek(0);advance(2);assert.equal(machine.getState().active,0);assert.equal(machine.getState().phase,'TRANSFER');assert.equal(machine.getState().position[0],-10);const before=machine.getState().elapsed;machine.seek(NaN);assert.equal(machine.getState().elapsed,before);});
  await test('Wafer surface stays above each support and transfer lands without a height jump',()=>{const tops=[1.8,1.8,1.78,1.82,1.78,1.8,1.81,1.8];for(let i=0;i<8;i++){machine.selectStage(i);machine.seek(.29999);advance(1);const before=machine.wafer.position.y;machine.seek(.3);advance(1);assert(machine.wafer.position.y-.013>=tops[i],JSON.stringify({index:i,height:machine.wafer.position.y,support:tops[i],state:machine.getState()}));assert(Math.abs(before-machine.wafer.position.y)<.001);}});
  await test('Detail top camera remains centered on the selected machine',()=>{machine.selectStage(5);app.click('[data-camera="top"]');advance(120);const p=machine.stations[5].point;assert(Math.abs(machine.camera.position.x-p.x)<.05);assert(Math.abs(machine.camera.position.z-p.z)<1);assert(machine.camera.position.y>p.y+6);assert(d.querySelector('#machineViewLabel').textContent.includes('현상기'));});
  await test('Hardware materials, reflection texture and rounded normals are finite',()=>{assert(machine.scene.environment?.isDataTexture);assert([...machine.scene.environment.image.data].every(Number.isFinite));machine.scene.traverse(o=>{if(o.geometry?.attributes.normal)assert([...o.geometry.attributes.normal.array].every(Number.isFinite));});});
  await test('Server recipe handoff applies its parameters and scenario to the visual lab',()=>{app.ctx.WaferAppBridge.loadRecipe({params:{...E.defaults,dose:120},scenario:'focus',reason:'Server revision evidence'});advance(2);assert.equal(d.querySelector('#param-dose').value,'120');assert.equal(app.ctx.WaferAppBridge.snapshot().missionId,'focus');assert.equal(machine.getState().active,3);assert.equal(d.querySelector('#hypothesis').value,'Server revision evidence');assert.throws(()=>app.ctx.WaferAppBridge.loadRecipe({params:{},scenario:'invalid'}));});
  machine.dispose();
  const output={date:new Date().toISOString(),engine:E.version,passed:tests.length,scope:'Model + DOM + real Three.js geometry/timeline with renderer stub. No browser/GPU rendering or screenshot assertion.',tests};
  await fs.writeFile(`${rootPath}/tests/results.json`,JSON.stringify(output,null,2));
  return output;
}
